/*

Copyright (C) University of Oxford, 2005-2011

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Chaste is free software: you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

Chaste is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details. The offer of Chaste under the terms of the
License is subject to the License being interpreted in accordance with
English Law and subject to any action against the University of Oxford
being under the jurisdiction of the English Courts.

You should have received a copy of the GNU Lesser General Public License
along with Chaste. If not, see <http://www.gnu.org/licenses/>.

*/

#ifndef TESTINAPROTOCOL_HPP_
#define TESTINAPROTOCOL_HPP_

#include <cxxtest/TestSuite.h>
#include <boost/assign/list_of.hpp>
using boost::assign::list_of;

#include "ProtocolRunner.hpp"
#include "ProtocolLanguage.hpp"
#include "ProtoHelperMacros.hpp"
#include "OutputFileHandler.hpp"

#include "UsefulFunctionsForProtocolTesting.hpp"
#include "PetscSetupAndFinalize.hpp"

class TestINaProtocol : public CxxTest::TestSuite
{
private:
    /** Keep track of the current directory */
    boost::shared_ptr<OutputFileHandler> mpHandler;

    /**
     * Sets up #mpHandler to point to correct model and protocol subfolder.
     *
     * @param rCellMLFileBaseName  The name of the cellML file (without .cellml on the end).
     * @param rProtocolName  The protocol name.
     * @param reset  Whether to wipe the directory (defaults to false).
     *
     * @return  The directory path relative to $CHASTE_TEST_OUTPUT
     */
    std::string SetupOutputFileHandler(const std::string& rCellMLFileBaseName, const std::string& rProtocolName, bool reset=false)
    {
        std::string dirname = "FunctionalCuration/" + rCellMLFileBaseName + "/" + rProtocolName;
        mpHandler.reset(new OutputFileHandler(dirname, reset)); // Create a new directory for this model
        return dirname;
    }

    /**
     * Creates the gnuplots of the full voltage timecourses
     */
    void GenerateGnuplotsFullTraces(const std::string& rDirectory,
                                    const std::string& rFilenamePrefix)
    {
        std::string filename = "Na_IV.gp";
        unsigned num_cols = 10; // Hardcoded - \todo get this out of protocol somehow.
        out_stream p_gnuplot_script = mpHandler->OpenOutputFile(filename);
        std::string output_dir = mpHandler->GetOutputDirectoryFullPath();
        *p_gnuplot_script << "# Gnuplot script file generated by Chaste." << std::endl;

        // Write the plot data to a single file
        std::string steppers_file = output_dir + rFilenamePrefix + "_final_membrane_voltage.csv";
        std::string data_file = output_dir + rFilenamePrefix + "_min_sodium_current.csv";

        std::string cmd = "paste -d , " + steppers_file + " " + data_file + " | tail -n +3 > " + output_dir + "IV_curve.dat";
        //std::cout << cmd << "\n" << std::flush;
        EXPECT0(system, cmd);

        // Write out a gnuplot script
        *p_gnuplot_script << "# Maximum current - Voltage relationship for fast sodium current." << std::endl;
        *p_gnuplot_script << "set terminal postscript eps enhanced size 3, 2" << std::endl;
        *p_gnuplot_script << "set output \"" << output_dir << "Na_IV_curve.eps\"" << std::endl;
        *p_gnuplot_script << "set title \"" << GetTitleFromDirectory(rDirectory) << "\"" << std::endl;
        *p_gnuplot_script << "set xlabel \"Voltage (mV)\"" << std::endl;
        *p_gnuplot_script << "set ylabel \"Maximum Current ({/Symbol m}A/cm^{2})\"" << std::endl;
        *p_gnuplot_script << "set grid" << std::endl;
        *p_gnuplot_script << "set autoscale" << std::endl;
        *p_gnuplot_script << "set style data lines" << std::endl;
        *p_gnuplot_script << "set key off" << std::endl;
        *p_gnuplot_script << "set datafile separator \",\"" << std::endl;
        *p_gnuplot_script << "plot \"" + output_dir + "IV_curve.dat\" using 1:2 with linespoints pointtype 7 "<< std::endl;
        p_gnuplot_script->close();

        // Run Gnuplot on the script written above to generate image files.
        EXPECT0(system, "gnuplot " + output_dir + filename);
    }

    /**
     * Run the Hypokalaemia protocol on the given model.
     *
     * @param rCellMLFileBaseName  the cellml file to dynamically load and use.
     * @return  whether the protocol was completed successfully
     */
    bool RunProtocol(std::string& rCellMLFileBaseName)
    {
        std::string protocol_name = "INa_IV_curve";
        std::string dirname = SetupOutputFileHandler(rCellMLFileBaseName, protocol_name);
        FileFinder cellml_file("projects/FunctionalCuration/cellml/" + rCellMLFileBaseName + ".cellml", RelativeTo::ChasteSourceRoot);
        FileFinder proto_xml_file("projects/FunctionalCuration/test/private/protocols/" + protocol_name + ".xml", RelativeTo::ChasteSourceRoot);

        try
        {
            ProtocolRunner runner(cellml_file, proto_xml_file, dirname);
            runner.RunProtocol();
        }
        catch (Exception& e)
        {
            OUR_WARN(e.GetMessage(), rCellMLFileBaseName, protocol_name);
            return false;
        }

        // Successful run
        return true;
    }

public:

    void TestProtocolsForManyCellModels() throw(Exception, std::bad_alloc)
    {
        std::vector<std::string> cellml_files = GetAListOfCellMLFiles();
        if (CommandLineArguments::Instance()->OptionExists("--models"))
        {
            cellml_files = CommandLineArguments::Instance()->GetStringsCorrespondingToOption("--models");
        }

        for (unsigned i=0; i<cellml_files.size(); ++i)
        {
            std::cout << "\nRunning protocols for " << cellml_files[i] << std::endl << std::flush;

            // Protocols and graphs must be done together so that
            // mpHandler points to the correct protocol subfolder.
            if (RunProtocol(cellml_files[i]))
            {
                try
                {
                	GenerateGnuplotsFullTraces(cellml_files[i], "outputs");
                }
                catch (Exception &e)
                {
                    OUR_WARN(e.GetMessage(), cellml_files[i], "Hypokalaemia");
                }
            }
        }
    }
};

#endif // TESTINAPROTOCOL_HPP_
