#ifdef CHASTE_CVODE
//! @file
//!
//! This source file was generated from CellML.
//!
//! Model: aslanidi_2009
//!
//! Processed by pycml - CellML Tools in Python
//!     (translators: 11498, pycml: 11498, optimize: 11490)
//! on Wed Feb 23 17:09:47 2011
//!
//! <autogenerated>

#include "aslanidi_Purkinje_model_2009_LHopitaled.hpp"
#include <cmath>
#include <cassert>
#include <memory>
#include "Exception.hpp"
#include "OdeSystemInformation.hpp"
#include "RegularStimulus.hpp"
#include "HeartConfig.hpp"
#include "IsNan.hpp"

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_Ca_i__Ca_i()
    {
        return var_Ca_i__Ca_i;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_Ca_r__Ca_r()
    {
        return var_Ca_r__Ca_r;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_environment__time()
    {
        return var_environment__time;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ca_L__g_Ca_L()
    {
        return var_i_Ca_L__g_Ca_L;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ca_L__i_Ca_L()
    {
        return var_i_Ca_L__i_Ca_L;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ca_L_d_gate__d()
    {
        return var_i_Ca_L_d_gate__d;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ca_L_f2_gate__f2()
    {
        return var_i_Ca_L_f2_gate__f2;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ca_L_f2_gate__tau_f2()
    {
        return var_i_Ca_L_f2_gate__tau_f2;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ca_L_f_Ca2_gate__f_Ca2()
    {
        return var_i_Ca_L_f_Ca2_gate__f_Ca2;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ca_L_f_Ca2_gate__tau_f_Ca2()
    {
        return var_i_Ca_L_f_Ca2_gate__tau_f_Ca2;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ca_L_f_Ca_gate__f_Ca()
    {
        return var_i_Ca_L_f_Ca_gate__f_Ca;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ca_L_f_Ca_gate__tau_f_Ca()
    {
        return var_i_Ca_L_f_Ca_gate__tau_f_Ca;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ca_L_f_gate__f()
    {
        return var_i_Ca_L_f_gate__f;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ca_L_f_gate__tau_f()
    {
        return var_i_Ca_L_f_gate__tau_f;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_K1__g_K1()
    {
        return var_i_K1__g_K1;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_K1__i_K1()
    {
        return var_i_K1__i_K1;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Kr__g_Kr_max()
    {
        return var_i_Kr__g_Kr_max;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Kr__i_Kr()
    {
        return var_i_Kr__i_Kr;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ks__g_Ks()
    {
        return var_i_Ks__g_Ks;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Ks__i_Ks()
    {
        return var_i_Ks__i_Ks;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_NaCa__i_NaCa()
    {
        return var_i_NaCa__i_NaCa;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_NaCa__i_NaCa_max()
    {
        return var_i_NaCa__i_NaCa_max;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Na__g_Na()
    {
        return var_i_Na__g_Na;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Na__i_Na()
    {
        return var_i_Na__i_Na;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Na__perc_reduced_inact_for_IpNa()
    {
        return var_i_Na__perc_reduced_inact_for_IpNa;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Na__shift_INa_inact()
    {
        return var_i_Na__shift_INa_inact;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Na_h_gate__h()
    {
        return var_i_Na_h_gate__h;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Na_h_gate__tau_h()
    {
        return var_i_Na_h_gate__tau_h;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Na_j_gate__j()
    {
        return var_i_Na_j_gate__j;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Na_j_gate__tau_j()
    {
        return var_i_Na_j_gate__tau_j;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_Na_m_gate__m()
    {
        return var_i_Na_m_gate__m;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_to_1__g_to_1()
    {
        return var_i_to_1__g_to_1;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_i_to_1__i_to_1()
    {
        return var_i_to_1__i_to_1;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_intracellular_ion_concentrations__K_i()
    {
        return var_intracellular_ion_concentrations__K_i;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_intracellular_ion_concentrations__Na_i()
    {
        return var_intracellular_ion_concentrations__Na_i;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_intracellular_ion_concentrations__conc_clamp()
    {
        return var_intracellular_ion_concentrations__conc_clamp;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane__V()
    {
        return var_membrane__V;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_protocol__i_stim()
    {
        return var_protocol__i_stim;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_q_rel__q_rel()
    {
        return var_q_rel__q_rel;
    }

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_fast_sodium_current_shift_inactivation_constant()
    {
        // Constant value given in CellML
        var_i_Na__shift_INa_inact = 0.0; // millivolt
        return var_i_Na__shift_INa_inact;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_fast_sodium_current_conductance_constant()
    {
        // Constant value given in CellML
        var_i_Na__g_Na = 8.0; // milliS_per_microF
        return var_i_Na__g_Na;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_fast_sodium_current_reduced_inactivation_constant()
    {
        // Constant value given in CellML
        var_i_Na__perc_reduced_inact_for_IpNa = 0.0; // dimensionless
        return var_i_Na__perc_reduced_inact_for_IpNa;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_rapid_delayed_rectifier_potassium_current_conductance_constant()
    {
        // Constant value given in CellML
        var_i_Kr__g_Kr_max = 0.040008488; // milliS_per_microF
        return var_i_Kr__g_Kr_max;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_L_type_calcium_current_f2_gate_tau_constant()
    {
        // Constant value given in CellML
        const double var_membrane__V = NV_Ith_S(mParameters, 0); // millivolt
        var_i_Ca_L_f2_gate__tau_f2 = 38.0 + (0.07 * pow(var_membrane__V - 18.6, 2.0)); // millisecond
        return var_i_Ca_L_f2_gate__tau_f2;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_L_type_calcium_current_conductance_constant()
    {
        // Constant value given in CellML
        var_i_Ca_L__g_Ca_L = 0.3392328; // dimensionless
        return var_i_Ca_L__g_Ca_L;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_voltage_constant()
    {
        // Constant value given in CellML
        const double var_membrane__V = NV_Ith_S(mParameters, 0); // millivolt
        return var_membrane__V;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_inward_rectifier_potassium_current_conductance_constant()
    {
        // Constant value given in CellML
        var_i_K1__g_K1 = 0.25; // milliS_per_microF
        return var_i_K1__g_K1;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_concentration_clamp_onoff_constant()
    {
        // Constant value given in CellML
        var_intracellular_ion_concentrations__conc_clamp = 1.0; // dimensionless
        return var_intracellular_ion_concentrations__conc_clamp;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_fast_sodium_current_h_gate_tau_constant()
    {
        // Constant value given in CellML
        const double var_membrane__V = NV_Ith_S(mParameters, 0); // millivolt
        var_i_Na__shift_INa_inact = 0.0; // millivolt
        const double var_i_Na_h_gate__beta_h = (var_membrane__V <  -40.0) ? ((3.56 * exp(0.079 * (var_membrane__V - var_i_Na__shift_INa_inact))) + (310000.0 * exp(0.35 * (var_membrane__V - var_i_Na__shift_INa_inact)))) : (1.0 / (0.13 * (1.0 + exp(((var_membrane__V + 10.66) - var_i_Na__shift_INa_inact) *  -0.0900900900901)))); // per_millisecond
        const double var_i_Na_h_gate__alpha_h = (var_membrane__V <  -40.0) ? (0.135 * exp(((var_membrane__V + 80.0) - var_i_Na__shift_INa_inact) *  -0.147058823529)) : 0.0; // per_millisecond
        var_i_Na_h_gate__tau_h = 1.0 / (var_i_Na_h_gate__alpha_h + var_i_Na_h_gate__beta_h); // millisecond
        return var_i_Na_h_gate__tau_h;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_sodium_calcium_exchanger_current_conductance_constant()
    {
        // Constant value given in CellML
        var_i_NaCa__i_NaCa_max = 4.5; // microA_per_microF
        return var_i_NaCa__i_NaCa_max * HeartConfig::Instance()->GetCapacitance();
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_L_type_calcium_current_f_gate_tau_constant()
    {
        // Constant value given in CellML
        const double var_membrane__V = NV_Ith_S(mParameters, 0); // millivolt
        var_i_Ca_L_f_gate__tau_f = 4.0 + (0.005 * pow(var_membrane__V - 2.5, 2.0)); // millisecond
        return var_i_Ca_L_f_gate__tau_f;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_fast_sodium_current_j_gate_tau_constant()
    {
        // Constant value given in CellML
        const double var_membrane__V = NV_Ith_S(mParameters, 0); // millivolt
        var_i_Na__shift_INa_inact = 0.0; // millivolt
        const double var_i_Na_j_gate__beta_j = (var_membrane__V <  -40.0) ? ((0.1212 * exp( -0.01052 * (var_membrane__V - var_i_Na__shift_INa_inact))) / (1.0 + exp( -0.1378 * ((var_membrane__V + 40.14) - var_i_Na__shift_INa_inact)))) : ((0.3 * exp( -2.535e-07 * (var_membrane__V - var_i_Na__shift_INa_inact))) / (1.0 + exp( -0.1 * ((var_membrane__V + 32.0) - var_i_Na__shift_INa_inact)))); // per_millisecond
        const double var_i_Na_j_gate__alpha_j = (var_membrane__V <  -40.0) ? (((( -127140.0 * exp(0.2444 * (var_membrane__V - var_i_Na__shift_INa_inact))) - (3.474e-05 * exp( -0.04391 * (var_membrane__V - var_i_Na__shift_INa_inact)))) * (var_membrane__V + 37.78)) / (1.0 + exp(0.311 * ((var_membrane__V + 79.23) - var_i_Na__shift_INa_inact)))) : 0.0; // per_millisecond
        var_i_Na_j_gate__tau_j = 1.0 / (var_i_Na_j_gate__alpha_j + var_i_Na_j_gate__beta_j); // millisecond
        return var_i_Na_j_gate__tau_j;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Get_membrane_transient_outward_current_conductance_constant()
    {
        // Constant value given in CellML
        var_i_to_1__g_to_1 = 0.14135944; // milliS_per_microF
        return var_i_to_1__g_to_1;
    }


    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::GetIntracellularCalciumConcentration()
    {
        return NV_Ith_S(mStateVariables, 20);
    }

    Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled(boost::shared_ptr<AbstractIvpOdeSolver> pOdeSolver /* unused; should be empty */, boost::shared_ptr<AbstractStimulusFunction> pIntracellularStimulus)
        : AbstractCvodeCell(
                pOdeSolver,
                27,
                -1,
                pIntracellularStimulus)
    {
        // Time units: millisecond
        //
        this->mpSystemInfo = OdeSystemInformation<Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled>::Instance();
        this->mVoltageIndex = GetAnyVariableIndex("membrane_voltage");
        Init();

        NV_Ith_S(this->mParameters, 0) = -83.43812846286808; // (c,protocol__membrane_voltage_value) [millivolt]
        // Protocol outputs
        this->mOutputsInfo.resize(3);
        this->mOutputsInfo[0] = std::make_pair(0, DERIVED);
        this->mOutputsInfo[1] = std::make_pair(1, DERIVED);
        this->mOutputsInfo[2] = std::make_pair(UNSIGNED_UNSET, FREE);

    }

    Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::~Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled()
    {
    }

    void Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::VerifyStateVariables()
    {}

    double Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::GetIIonic(const std::vector<double>* pStateVariables)
    {
        N_Vector rY = rGetStateVariables();
        const double var_i_Ca_L_d_gate__d = NV_Ith_S(rY, 5);
        // Units: dimensionless; Initial value: 0.000002322223865147363
        const double var_i_Ca_L_f_gate__f = NV_Ith_S(rY, 6);
        // Units: dimensionless; Initial value: 0.9985607329462358
        const double var_i_Ca_L_f2_gate__f2 = NV_Ith_S(rY, 7);
        // Units: dimensionless; Initial value: 0.8173435436674658
        const double var_i_Ca_L_f_Ca_gate__f_Ca = NV_Ith_S(rY, 8);
        // Units: dimensionless; Initial value: 0.9610551285529658
        const double var_i_Ca_L_f_Ca2_gate__f_Ca2 = NV_Ith_S(rY, 9);
        // Units: dimensionless; Initial value: 0.868690796671854
        const double var_Ca_r__Ca_r = NV_Ith_S(rY, 24);
        // Units: millimolar; Initial value: 0.00022418117117903934

        const double var_membrane__V = NV_Ith_S(mParameters, 0); // millivolt
        const double var_i_Ca_L__i_Ca_L_max = ((((var_membrane__V - 15.0) * 9048693.2787) * 3.87996927064e-07) * ((1.0 * var_Ca_r__Ca_r * exp(((var_membrane__V - 15.0) * 192970.0) * 3.87996927064e-07)) - 0.6138)) / (exp(((var_membrane__V - 15.0) * 192970.0) * 3.87996927064e-07) - 1.0); // microA_per_microF
        var_i_Ca_L__g_Ca_L = 0.3392328; // dimensionless
        const double var_i_Ca_L__i_Ca_L = var_i_Ca_L__g_Ca_L * var_i_Ca_L_d_gate__d * var_i_Ca_L_f_gate__f * var_i_Ca_L_f2_gate__f2 * var_i_Ca_L_f_Ca_gate__f_Ca * var_i_Ca_L_f_Ca2_gate__f_Ca2 * var_i_Ca_L__i_Ca_L_max; // microA_per_microF

        const double i_ionic = var_i_Ca_L__i_Ca_L;
        EXCEPT_IF_NOT(!std::isnan(i_ionic));
        return i_ionic * HeartConfig::Instance()->GetCapacitance();
    }

    void Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::EvaluateYDerivatives(double var_environment__time, const N_Vector rY, N_Vector rDY)
    {
        // Inputs:
        // Time units: millisecond
        const double var_i_Na_m_gate__m = NV_Ith_S(rY, 0);
        // Units: dimensionless; Initial value: 0.002003390432234504
        const double var_i_Na_h_gate__h = NV_Ith_S(rY, 1);
        // Units: dimensionless; Initial value: 0.9786390933308567
        const double var_i_Na_j_gate__j = NV_Ith_S(rY, 2);
        // Units: dimensionless; Initial value: 0.09866447258167589
        const double var_i_Na_L_m_L_gate__m_L = NV_Ith_S(rY, 3);
        // Units: dimensionless; Initial value: 0.002003390432234504
        const double var_i_Na_L_h_L_gate__h_L = NV_Ith_S(rY, 4);
        // Units: dimensionless; Initial value: 0.8946968372659203
        const double var_i_Ca_L_d_gate__d = NV_Ith_S(rY, 5);
        // Units: dimensionless; Initial value: 0.000002322223865147363
        const double var_i_Ca_L_f_gate__f = NV_Ith_S(rY, 6);
        // Units: dimensionless; Initial value: 0.9985607329462358
        const double var_i_Ca_L_f2_gate__f2 = NV_Ith_S(rY, 7);
        // Units: dimensionless; Initial value: 0.8173435436674658
        const double var_i_Ca_L_f_Ca_gate__f_Ca = NV_Ith_S(rY, 8);
        // Units: dimensionless; Initial value: 0.9610551285529658
        const double var_i_Ca_L_f_Ca2_gate__f_Ca2 = NV_Ith_S(rY, 9);
        // Units: dimensionless; Initial value: 0.868690796671854
        const double var_i_to_1_a_gate__a = NV_Ith_S(rY, 10);
        // Units: dimensionless; Initial value: 0.0004238729429342389
        const double var_i_to_1_i_gate__i = NV_Ith_S(rY, 11);
        // Units: dimensionless; Initial value: 0.9990935802459496
        const double var_i_to_1_i2_gate__i2 = NV_Ith_S(rY, 12);
        // Units: dimensionless; Initial value: 0.9777368439681764
        const double var_i_Kr_xr_gate__xr = NV_Ith_S(rY, 13);
        // Units: dimensionless; Initial value: 0.07084939408222911
        const double var_i_Ks_xs1_gate__xs1 = NV_Ith_S(rY, 14);
        // Units: dimensionless; Initial value: 0.0011737654433043125
        const double var_i_Ks_xs2_gate__xs2 = NV_Ith_S(rY, 15);
        // Units: dimensionless; Initial value: 0.001179442867470093
        const double var_i_to_2_a_gate__a = NV_Ith_S(rY, 16);
        // Units: dimensionless; Initial value: 0.0014909437525000811
        const double var_intracellular_ion_concentrations__Na_i = NV_Ith_S(rY, 17);
        // Units: millimolar; Initial value: 9.927155552932733
        const double var_intracellular_ion_concentrations__Cl_i = NV_Ith_S(rY, 18);
        // Units: millimolar; Initial value: 18.904682470140408
        const double var_intracellular_ion_concentrations__K_i = NV_Ith_S(rY, 19);
        // Units: millimolar; Initial value: 141.9670801746057
        const double var_Ca_i__Ca_i = NV_Ith_S(rY, 20);
        // Units: millimolar; Initial value: 0.00022355433459434943
        const double var_Ca_MK_act__Ca_MK_trap = NV_Ith_S(rY, 21);
        // Units: dimensionless; Initial value: 0.000008789168284782809
        const double var_Ca_NSR__Ca_NSR = NV_Ith_S(rY, 22);
        // Units: millimolar; Initial value: 1.2132524695849454
        const double var_Ca_JSR__Ca_JSR = NV_Ith_S(rY, 23);
        // Units: millimolar; Initial value: 1.1433050636518596
        const double var_Ca_r__Ca_r = NV_Ith_S(rY, 24);
        // Units: millimolar; Initial value: 0.00022418117117903934
        const double var_q_rel_ri_gate__ri = NV_Ith_S(rY, 25);
        // Units: dimensionless; Initial value: 0.7802870066567904
        const double var_q_rel_ro_gate__ro = NV_Ith_S(rY, 26);
        // Units: dimensionless; Initial value: 1.2785734760674763e-9


        // Mathematics
        const double var_membrane__V = NV_Ith_S(mParameters, 0); // millivolt
        double temp;
        double a = 9048693.2787 * 3.87996927064e-07;
        double b = 192970.0 * 3.87996927064e-07;
        double c = - 0.6138;
        double d = var_Ca_r__Ca_r;
        if (var_membrane__V != 15)
        {
            // Express as f(V)/g(V)
            temp = (var_membrane__V - 15.0) * a * (d * exp((var_membrane__V - 15.0)*b) + c) /
                    (exp((var_membrane__V - 15.0) * b) - 1.0);
        }
        else
        {
            // Apply L'Hopital's Rule (if f(15)=0 and g(15)=0, then the limit of f(V)/g(V) as V -> 15 is limit of f'(15)/g'(15) )
            temp = (a*c + a*d*(1.0 - 14*b)*exp((var_membrane__V - 15.0)*b)) /
                    (b*exp((var_membrane__V - 15.0)*b));
            // (May as well auto-evaluate this expression at V = 15 in Maple)
        }
        const double var_i_Ca_L__i_Ca_L_max = temp;
        var_i_Ca_L__g_Ca_L = 0.3392328; // dimensionless
        const double var_i_Ca_L__i_Ca_L = var_i_Ca_L__g_Ca_L * var_i_Ca_L_d_gate__d * var_i_Ca_L_f_gate__f * var_i_Ca_L_f2_gate__f2 * var_i_Ca_L_f_Ca_gate__f_Ca * var_i_Ca_L_f_Ca2_gate__f_Ca2 * var_i_Ca_L__i_Ca_L_max; // microA_per_microF
        const double var_equilibrium_potentials__E_Na = 26.7123387055 * log(140.0 / var_intracellular_ion_concentrations__Na_i); // millivolt
        const double var_background_currents__i_Na_b = 0.0025 * (var_membrane__V - var_equilibrium_potentials__E_Na); // microA_per_microF
        const double var_i_NaK__i_NaK = ((((1.0 / (1.0 + (0.1245 * exp((var_membrane__V *  -9648.5) * 3.87996927064e-07)) + (exp(( -96485.0 * var_membrane__V) * 3.87996927064e-07) * 0.0365332261305))) * 0.61875) / (1.0 + pow(10.0 / var_intracellular_ion_concentrations__Na_i, 2.0))) * 5.4) * 0.144927536232; // microA_per_microF

        a = 3723.74209 * 3.87996927064e-07;
        b = 96485.0 * 3.87996927064e-07;
        c = var_intracellular_ion_concentrations__Cl_i;
        d = 100.0;
        if ( var_membrane__V != 0 )
        {
            // Express as f(V)/g(V)
            temp = (  var_membrane__V * a * (c - d* exp(var_membrane__V * b) ) ) /
                    (1.0 - exp(var_membrane__V * b));
        }
        else
        {
            // Apply L'Hopital's Rule (if f(0)=0 and g(0)=0, then the limit of f(V)/g(V) as V -> 0 is limit of f'(0)/g'(0) )
            temp = ( a*c - a * d * (b*var_membrane__V + 1.0) * exp( b*var_membrane__V )) /
                    (-b * exp( b*var_membrane__V ));
            // (May as well auto-evaluate this expression at V = 0 in Maple)
        }
        const double var_i_to_2__i_to_2 = 20.0 * temp * var_i_to_2_a_gate__a;

        var_i_to_1__g_to_1 = 0.14135944; // milliS_per_microF
        const double var_equilibrium_potentials__E_K = 26.7123387055 * log(5.4 / var_intracellular_ion_concentrations__K_i); // millivolt
        var_i_to_1__i_to_1 = var_i_to_1__g_to_1 * var_i_to_1_a_gate__a * ((0.8 * var_i_to_1_i_gate__i) + (0.2 * var_i_to_1_i2_gate__i2)) * (var_membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        var_i_Na__g_Na = 8.0; // milliS_per_microF
        var_i_Na__i_Na = var_i_Na__g_Na * pow(var_i_Na_m_gate__m, 3.0) * ((0.8 * var_i_Na_h_gate__h) + (0.2 * var_i_Na_j_gate__j)) * (var_membrane__V - var_equilibrium_potentials__E_Na); // microA_per_microF
        const double var_i_K_p__i_K_p = 0.00276 * (1.0 / (1.0 + exp((7.488 - var_membrane__V) * 0.167224080268))) * (var_membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_i_Na_L__i_Na_L = 0.037375 * pow(var_i_Na_L_m_L_gate__m_L, 3.0) * var_i_Na_L_h_L_gate__h_L * (var_membrane__V - var_equilibrium_potentials__E_Na); // microA_per_microF
        var_i_Kr__g_Kr_max = 0.040008488; // milliS_per_microF
        var_i_Kr__i_Kr = (var_i_Kr__g_Kr_max * 1.0) * var_i_Kr_xr_gate__xr * (1.0 / (1.0 + exp((var_membrane__V - 5.4) * 0.0490196078431))) * (var_membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        var_i_NaCa__i_NaCa_max = 4.5; // microA_per_microF
        var_i_NaCa__i_NaCa = ((var_i_NaCa__i_NaCa_max * pow(var_intracellular_ion_concentrations__Na_i, 3.0) * exp((var_membrane__V * 33769.75) * 3.87996927064e-07) * 0.72) - (var_Ca_i__Ca_i * exp((var_membrane__V *  -62715.25) * 3.87996927064e-07) * 4116000.0)) / ((1.0 + pow(0.000125 / (1.5 * var_Ca_i__Ca_i), 2.0)) * (1.0 + (0.27 * exp((var_membrane__V *  -62715.25) * 3.87996927064e-07))) * (((1.3 * pow(var_intracellular_ion_concentrations__Na_i, 3.0)) + (var_Ca_i__Ca_i * 1004882.8125) + ((1.0 + ((1.5 * var_Ca_i__Ca_i) * 277.777777778)) * 3349.5606)) + (((1.0 + (var_intracellular_ion_concentrations__Na_i * 0.0813008130081)) * 9878.4) + (pow(var_intracellular_ion_concentrations__Na_i, 3.0) * 1.8) + (var_Ca_i__Ca_i * 4116000.0)))); // microA_per_microF

        a = 7429.17826389 * 3.87996927064e-07;
        b = 192970.0 * 3.87996927064e-07;
        c = - 0.6138;
        d = var_Ca_i__Ca_i;
        if (var_membrane__V != 0)
        {
            // Express as f(V)/g(V)
            temp = a*var_membrane__V * (d * exp( b * var_membrane__V ) + c) /
                    ( exp( b * var_membrane__V ) - 1.0 );
        }
        else
        {
            // Apply L'Hopital's Rule (if f(0)=0 and g(0)=0, then the limit of f(V)/g(V) as V -> 0 is limit of f'(0)/g'(0) )
            temp = a* (c + d * (b*var_membrane__V + 1.0) * exp(b * var_membrane__V)) /
                    ( b * exp(b * var_membrane__V) ); // (May as well auto-evaluate this expression at V = 0 in Maple)
        }
        const double var_background_currents__i_Ca_b = temp;
        const double var_background_currents__i_K_b = 0.005 * (var_membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_equilibrium_potentials__E_Cl =  -26.7123387055 * log(100.0 / var_intracellular_ion_concentrations__Cl_i); // millivolt
        const double var_background_currents__i_Cl_b = 0.000225 * (var_membrane__V - var_equilibrium_potentials__E_Cl); // microA_per_microF
        const double var_i_Ca_p__i_Ca_p = (0.0575 * var_Ca_i__Ca_i) / (0.0005 + var_Ca_i__Ca_i); // microA_per_microF
        var_i_Ks__g_Ks = 0.052581329 * (1.0 + (0.6 / (1.0 + pow(3.8e-05 / var_Ca_i__Ca_i, 1.4)))); // milliS_per_microF
        var_i_Ks__i_Ks = var_i_Ks__g_Ks * var_i_Ks_xs1_gate__xs1 * var_i_Ks_xs2_gate__xs2 * (var_membrane__V - (26.7123387055 * log(7.9662 / (var_intracellular_ion_concentrations__K_i + (0.01833 * var_intracellular_ion_concentrations__Na_i))))); // microA_per_microF
        var_i_K1__g_K1 = 0.25; // milliS_per_microF
        const double var_i_K1_xK1_gate__alpha_xK1 = 1.02 / (1.0 + exp(0.2385 * (var_membrane__V - (var_equilibrium_potentials__E_K + 59.215)))); // dimensionless
        var_i_K1__i_K1 = ((var_i_K1__g_K1 * (var_i_K1_xK1_gate__alpha_xK1 / (var_i_K1_xK1_gate__alpha_xK1 + (((0.49124 * exp(0.08032 * ((var_membrane__V + 5.476) - var_equilibrium_potentials__E_K))) + exp(0.06175 * (var_membrane__V - (594.31 + var_equilibrium_potentials__E_K)))) / (1.0 + exp( -0.5143 * ((var_membrane__V + 4.753) - var_equilibrium_potentials__E_K))))))) + 0.004) * (var_membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        var_i_Na__shift_INa_inact = 0.0; // millivolt
        var_i_Na__perc_reduced_inact_for_IpNa = 0.0; // dimensionless
        const double var_i_Na_m_gate__beta_m = 0.08 * exp((-var_membrane__V) * 0.0909090909091); // per_millisecond
        const double var_i_Na_m_gate__alpha_m = (0.32 * (var_membrane__V + 47.13)) / (1.0 - exp( -0.1 * (var_membrane__V + 47.13))); // per_millisecond
        const double var_i_Na_h_gate__beta_h = (var_membrane__V <  -40.0) ? ((3.56 * exp(0.079 * (var_membrane__V - var_i_Na__shift_INa_inact))) + (310000.0 * exp(0.35 * (var_membrane__V - var_i_Na__shift_INa_inact)))) : (1.0 / (0.13 * (1.0 + exp(((var_membrane__V + 10.66) - var_i_Na__shift_INa_inact) *  -0.0900900900901)))); // per_millisecond
        const double var_i_Na_h_gate__alpha_h = (var_membrane__V <  -40.0) ? (0.135 * exp(((var_membrane__V + 80.0) - var_i_Na__shift_INa_inact) *  -0.147058823529)) : 0.0; // per_millisecond
        var_i_Na_h_gate__tau_h = 1.0 / (var_i_Na_h_gate__alpha_h + var_i_Na_h_gate__beta_h); // millisecond
        const double var_i_Na_j_gate__beta_j = (var_membrane__V <  -40.0) ? ((0.1212 * exp( -0.01052 * (var_membrane__V - var_i_Na__shift_INa_inact))) / (1.0 + exp( -0.1378 * ((var_membrane__V + 40.14) - var_i_Na__shift_INa_inact)))) : ((0.3 * exp( -2.535e-07 * (var_membrane__V - var_i_Na__shift_INa_inact))) / (1.0 + exp( -0.1 * ((var_membrane__V + 32.0) - var_i_Na__shift_INa_inact)))); // per_millisecond
        const double var_i_Na_j_gate__alpha_j = (var_membrane__V <  -40.0) ? (((( -127140.0 * exp(0.2444 * (var_membrane__V - var_i_Na__shift_INa_inact))) - (3.474e-05 * exp( -0.04391 * (var_membrane__V - var_i_Na__shift_INa_inact)))) * (var_membrane__V + 37.78)) / (1.0 + exp(0.311 * ((var_membrane__V + 79.23) - var_i_Na__shift_INa_inact)))) : 0.0; // per_millisecond
        var_i_Na_j_gate__tau_j = 1.0 / (var_i_Na_j_gate__alpha_j + var_i_Na_j_gate__beta_j); // millisecond
        const double var_i_Na_L_m_L_gate__beta_m_L = 0.08 * exp((-var_membrane__V) * 0.0909090909091); // per_millisecond
        const double var_i_Na_L_m_L_gate__alpha_m_L = (0.32 * (var_membrane__V + 47.13)) / (1.0 - exp( -0.1 * (var_membrane__V + 47.13))); // per_millisecond
        const double var_Ca_MK_act__Ca_MK_bound = (0.05 * (1.0 - var_Ca_MK_act__Ca_MK_trap)) / (1.0 + (0.15 / var_Ca_r__Ca_r)); // dimensionless
        const double var_Ca_MK_act__Ca_MK_act = var_Ca_MK_act__Ca_MK_bound + var_Ca_MK_act__Ca_MK_trap; // dimensionless
        var_i_Ca_L_f_gate__tau_f = 4.0 + (0.005 * pow(var_membrane__V - 2.5, 2.0)); // millisecond
        var_i_Ca_L_f2_gate__tau_f2 = 38.0 + (0.07 * pow(var_membrane__V - 18.6, 2.0)); // millisecond
        var_i_Ca_L_f_Ca_gate__tau_f_Ca = 0.5 + ((var_Ca_MK_act__Ca_MK_act * 10.0) / ((1.0 * var_Ca_MK_act__Ca_MK_act) + 0.15)) + (1.0 / (1.0 + (var_Ca_r__Ca_r * 333.333333333))); // millisecond
        var_i_Ca_L_f_Ca2_gate__tau_f_Ca2 = 125.0 + (300.0 / (1.0 + exp(((-var_i_Ca_L__i_Ca_L) - 0.175) * 25.0))); // millisecond
        const double var_i_to_1_a_gate__alpha_a = (25.0 * exp((var_membrane__V - 76.0) * 0.05)) / (1.0 + exp((var_membrane__V - 76.0) * 0.05)); // per_millisecond
        const double var_i_to_1_a_gate__beta_a = (25.0 * exp((-(var_membrane__V + 54.0)) * 0.05)) / (1.0 + exp((-(var_membrane__V + 54.0)) * 0.05)); // per_millisecond
        const double var_i_to_1_i_gate__alpha_i = 0.03 / (1.0 + exp((var_membrane__V + 25.0) * 0.0666666666667)); // per_millisecond
        const double var_i_to_1_i2_gate__alpha_i2 = 0.00442 / (1.0 + exp((var_membrane__V + 26.0) * 0.0666666666667)); // per_millisecond
        const double var_CT_K_Cl__CT_K_Cl = (7.0756e-06 * (var_equilibrium_potentials__E_K - var_equilibrium_potentials__E_Cl)) / ((var_equilibrium_potentials__E_K + 87.8251) - var_equilibrium_potentials__E_Cl); // millimolar_per_millisecond
        const double var_CT_Na_Cl__CT_Na_Cl = (9.8443e-06 * pow(var_equilibrium_potentials__E_Na - var_equilibrium_potentials__E_Cl, 4.0)) / (pow(var_equilibrium_potentials__E_Na - var_equilibrium_potentials__E_Cl, 4.0) + 59494197.6407); // millimolar_per_millisecond
        var_intracellular_ion_concentrations__conc_clamp = 1.0; // dimensionless
        const double var_q_up__q_up = ((((var_Ca_MK_act__Ca_MK_act * 0.75) / (0.15 + (var_Ca_MK_act__Ca_MK_act * 1.0))) + 1.0) * var_Ca_i__Ca_i * 0.0021875) / ((var_Ca_i__Ca_i + 0.00092) - ((var_Ca_MK_act__Ca_MK_act * 0.00017) / (0.15 + (var_Ca_MK_act__Ca_MK_act * 1.0)))); // millimolar_per_millisecond
        const double var_q_leak__q_leak = (0.004375 * var_Ca_NSR__Ca_NSR) * 0.0666666666667; // millimolar_per_millisecond
        const double var_Ca_r__q_diff = (var_Ca_r__Ca_r - var_Ca_i__Ca_i) * 5.0; // millimolar_per_millisecond
        const double var_q_tr__q_tr = (var_Ca_NSR__Ca_NSR - var_Ca_JSR__Ca_JSR) * 0.00833333333333; // millimolar_per_millisecond
        var_q_rel__q_rel = (3000.0 * (1.0 / (1.0 + exp(((var_i_Ca_L__g_Ca_L * var_i_Ca_L__i_Ca_L_max) + 13.0) * 0.2)))) * var_q_rel_ro_gate__ro * var_q_rel_ri_gate__ri * (var_Ca_JSR__Ca_JSR - var_Ca_r__Ca_r); // millimolar_per_millisecond
        const double var_q_rel_ri_gate__Ca_fac = 1.0 / (1.0 + exp((var_i_Ca_L__i_Ca_L + 0.05) * 66.6666666667)); // millimolar
        const double var_q_rel_ri_gate__tau_Ca_MK = (var_Ca_MK_act__Ca_MK_act * 10.0) / (0.15 + (1.0 * var_Ca_MK_act__Ca_MK_act)); // millisecond
        const double d_dt_i_Na_m_gate__m = ((var_i_Na_m_gate__alpha_m / (var_i_Na_m_gate__alpha_m + var_i_Na_m_gate__beta_m)) - var_i_Na_m_gate__m) / (1.0 / (var_i_Na_m_gate__alpha_m + var_i_Na_m_gate__beta_m)); // per_millisecond
        const double d_dt_i_Na_h_gate__h = ((((var_i_Na_h_gate__alpha_h * (1.0 - (var_i_Na__perc_reduced_inact_for_IpNa * 0.01))) / (var_i_Na_h_gate__alpha_h + var_i_Na_h_gate__beta_h)) + (var_i_Na__perc_reduced_inact_for_IpNa * 0.01)) - var_i_Na_h_gate__h) / var_i_Na_h_gate__tau_h; // per_millisecond
        const double d_dt_i_Na_j_gate__j = ((((var_i_Na_j_gate__alpha_j * (1.0 - (var_i_Na__perc_reduced_inact_for_IpNa * 0.01))) / (var_i_Na_j_gate__alpha_j + var_i_Na_j_gate__beta_j)) + (var_i_Na__perc_reduced_inact_for_IpNa * 0.01)) - var_i_Na_j_gate__j) / var_i_Na_j_gate__tau_j; // per_millisecond
        const double d_dt_i_Na_L_m_L_gate__m_L = ((var_i_Na_L_m_L_gate__alpha_m_L / (var_i_Na_L_m_L_gate__alpha_m_L + var_i_Na_L_m_L_gate__beta_m_L)) - var_i_Na_L_m_L_gate__m_L) / (1.0 / (var_i_Na_L_m_L_gate__alpha_m_L + var_i_Na_L_m_L_gate__beta_m_L)); // per_millisecond
        const double d_dt_i_Na_L_h_L_gate__h_L = ((1.0 / (1.0 + exp((var_membrane__V + 69.0) * 0.16393442623))) - var_i_Na_L_h_L_gate__h_L) / (175.0 + (125.0 / (1.0 + exp((-(var_membrane__V + 25.0)) * 0.166666666667)))); // per_millisecond
        const double d_dt_i_Ca_L_d_gate__d = ((1.0 / (1.0 + exp((-(var_membrane__V - 4.0)) * 0.148367952522))) - var_i_Ca_L_d_gate__d) / (0.59 + ((0.8 * exp(0.052 * (var_membrane__V + 13.0))) / (1.0 + exp(0.132 * (var_membrane__V + 13.0))))); // per_millisecond
        const double d_dt_i_Ca_L_f_gate__f = ((1.0 / (1.0 + exp((var_membrane__V + 18.0) * 0.1))) - var_i_Ca_L_f_gate__f) / var_i_Ca_L_f_gate__tau_f; // per_millisecond
        const double d_dt_i_Ca_L_f2_gate__f2 = ((1.0 / (1.0 + exp((var_membrane__V + 18.0) * 0.1))) - var_i_Ca_L_f2_gate__f2) / var_i_Ca_L_f2_gate__tau_f2; // per_millisecond
        const double d_dt_i_Ca_L_f_Ca_gate__f_Ca = (((0.3 / (1.0 - (var_i_Ca_L__i_Ca_L * 20.0))) + (0.55 / (1.0 + (var_Ca_r__Ca_r * 333.333333333))) + 0.15) - var_i_Ca_L_f_Ca_gate__f_Ca) / var_i_Ca_L_f_Ca_gate__tau_f_Ca; // per_millisecond
        const double d_dt_i_Ca_L_f_Ca2_gate__f_Ca2 = ((1.0 / (1.0 - (var_i_Ca_L__i_Ca_L * 100.0))) - var_i_Ca_L_f_Ca2_gate__f_Ca2) / var_i_Ca_L_f_Ca2_gate__tau_f_Ca2; // per_millisecond
        const double d_dt_i_to_1_a_gate__a = ((var_i_to_1_a_gate__alpha_a / (var_i_to_1_a_gate__alpha_a + var_i_to_1_a_gate__beta_a)) - var_i_to_1_a_gate__a) / (1.0 / (var_i_to_1_a_gate__alpha_a + var_i_to_1_a_gate__beta_a)); // per_millisecond
        const double d_dt_i_to_1_i_gate__i = ((var_i_to_1_i_gate__alpha_i / (var_i_to_1_i_gate__alpha_i + ((0.1 * exp((var_membrane__V - 40.0) * 0.0666666666667)) / (1.0 + exp((var_membrane__V - 40.0) * 0.0666666666667))))) - var_i_to_1_i_gate__i) / (6.0 + (5.0 / (1.0 + exp((var_membrane__V - 16.5) * 0.1)))); // per_millisecond
        const double d_dt_i_to_1_i2_gate__i2 = ((var_i_to_1_i2_gate__alpha_i2 / (var_i_to_1_i2_gate__alpha_i2 + ((0.05 * exp((var_membrane__V - 10.0) * 0.0666666666667)) / (1.0 + exp((var_membrane__V - 10.0) * 0.0666666666667))))) - var_i_to_1_i2_gate__i2) / (21.5 + (30.0 / (1.0 + exp((var_membrane__V - 25.0) * 0.1)))); // per_millisecond
        const double d_dt_i_Kr_xr_gate__xr = ((1.0 / (1.0 + exp((-(var_membrane__V + 0.085)) * 0.0816326530612))) - var_i_Kr_xr_gate__xr) / ((900.0 / (1.0 + exp(var_membrane__V * 0.2))) + 100.0); // per_millisecond
        const double d_dt_i_Ks_xs1_gate__xs1 = ((1.0 / (1.0 + exp((-(var_membrane__V - 9.0)) * 0.0729927007299))) - var_i_Ks_xs1_gate__xs1) / (1.0 / (((7.61e-05 * (var_membrane__V + 44.6)) / (1.0 - exp( -9.97 * (var_membrane__V + 44.6)))) + ((0.00036 * (var_membrane__V - 0.55)) / (exp(0.128 * (var_membrane__V - 0.55)) - 1.0)))); // per_millisecond
        const double d_dt_i_Ks_xs2_gate__xs2 = ((1.0 / (1.0 + exp((-(var_membrane__V - 9.0)) * 0.0729927007299))) - var_i_Ks_xs2_gate__xs2) / (2.0 / (((7.61e-05 * (var_membrane__V + 44.6)) / (1.0 - exp( -9.97 * (var_membrane__V + 44.6)))) + ((0.00036 * (var_membrane__V - 0.55)) / (exp(0.128 * (var_membrane__V - 0.55)) - 1.0)))); // per_millisecond
        const double d_dt_i_to_2_a_gate__a = ((1.0 / (1.0 + (0.1502 / var_Ca_r__Ca_r))) - var_i_to_2_a_gate__a) * 1.0; // per_millisecond
        const double d_dt_intracellular_ion_concentrations__Na_i = var_intracellular_ion_concentrations__conc_clamp * ((((var_i_Na__i_Na + var_i_Na_L__i_Na_L + var_background_currents__i_Na_b + (3.0 * var_i_NaK__i_NaK) + (3.0 * var_i_NaCa__i_NaCa)) *  -0.0001533576) * 4.41274623303e-05) + var_CT_Na_Cl__CT_Na_Cl); // 'millimole per litre per millisecond'
        const double d_dt_intracellular_ion_concentrations__K_i = var_intracellular_ion_concentrations__conc_clamp * (((((var_i_to_1__i_to_1 + var_i_K1__i_K1 + var_i_Kr__i_Kr + var_i_Ks__i_Ks + var_i_K_p__i_K_p + var_background_currents__i_K_b) - (2.0 * var_i_NaK__i_NaK)) *  -0.0001533576) * 4.41274623303e-05) + var_CT_K_Cl__CT_K_Cl); // 'millimole per litre per millisecond'
        const double d_dt_intracellular_ion_concentrations__Cl_i = var_intracellular_ion_concentrations__conc_clamp * ((((var_i_to_2__i_to_2 + var_background_currents__i_Cl_b) *  -0.0001533576) * 4.41274623303e-05) + var_CT_Na_Cl__CT_Na_Cl + var_CT_K_Cl__CT_K_Cl); // 'millimole per litre per millisecond'
        const double d_dt_Ca_i__Ca_i = (-(1.0 / (1.0 + ((var_Ca_i__Ca_i * 0.14) / pow(var_Ca_i__Ca_i + 0.0005, 2.0)) + ((var_Ca_i__Ca_i * 0.1) / pow(var_Ca_i__Ca_i + 0.00238, 2.0))))) * ((((((var_background_currents__i_Ca_b + var_i_Ca_p__i_Ca_p) - (2.0 * var_i_NaCa__i_NaCa)) * 0.0001533576) * 2.20637311651e-05) + (((var_q_up__q_up - var_q_leak__q_leak) * 0.01906608) * 4.25763820294)) - ((var_Ca_r__q_diff * 0.006908) * 4.25763820294)); // 'millimole per litre per millisecond'
        const double d_dt_Ca_MK_act__Ca_MK_trap = (0.05 * var_Ca_MK_act__Ca_MK_bound * (var_Ca_MK_act__Ca_MK_bound + var_Ca_MK_act__Ca_MK_trap)) - (0.00068 * var_Ca_MK_act__Ca_MK_trap); // per_millisecond
        const double d_dt_Ca_NSR__Ca_NSR = var_q_up__q_up - (var_q_leak__q_leak + ((var_q_tr__q_tr * 0.00165792) * 52.4491662681)); // 'millimole per litre per millisecond'
        const double d_dt_Ca_JSR__Ca_JSR = (var_q_tr__q_tr - var_q_rel__q_rel) / (1.0 + (8.0 / pow(0.8 + var_Ca_JSR__Ca_JSR, 2.0))); // 'millimole per litre per millisecond'
        const double d_dt_Ca_r__Ca_r = (1.0 / (1.0 + ((var_Ca_r__Ca_r * 0.094) / pow(var_Ca_r__Ca_r + 0.00087, 2.0)) + ((var_Ca_r__Ca_r * 2.248) / pow(var_Ca_r__Ca_r + 0.0087, 2.0)))) * ((((var_i_Ca_L__i_Ca_L *  -0.0001533576) * 0.000750166859615) + ((var_q_rel__q_rel * 0.00165792) * 144.7596989)) - var_Ca_r__q_diff); // 'millimole per litre per millisecond'
        const double d_dt_q_rel_ri_gate__ri = ((1.0 / (1.0 + exp(((var_Ca_r__Ca_r - 0.0004) + (0.002 * var_q_rel_ri_gate__Ca_fac)) * 40000.0))) - var_q_rel_ri_gate__ri) / (((350.0 - var_q_rel_ri_gate__tau_Ca_MK) / (1.0 + exp(((var_Ca_r__Ca_r - 0.003) + (0.003 * var_q_rel_ri_gate__Ca_fac)) * 5000.0))) + 3.0 + var_q_rel_ri_gate__tau_Ca_MK); // per_millisecond
        const double d_dt_q_rel_ro_gate__ro = ((((pow(var_Ca_JSR__Ca_JSR, 1.9) / (pow(var_Ca_JSR__Ca_JSR, 1.9) + pow((49.28 * var_Ca_r__Ca_r) / (var_Ca_r__Ca_r + 0.0028), 1.9))) * pow(var_i_Ca_L__i_Ca_L, 2.0)) / (pow(var_i_Ca_L__i_Ca_L, 2.0) + 1.0)) - var_q_rel_ro_gate__ro) * 0.333333333333; // per_millisecond

        NV_Ith_S(rDY, 0) = d_dt_i_Na_m_gate__m;
        NV_Ith_S(rDY, 1) = d_dt_i_Na_h_gate__h;
        NV_Ith_S(rDY, 2) = d_dt_i_Na_j_gate__j;
        NV_Ith_S(rDY, 3) = d_dt_i_Na_L_m_L_gate__m_L;
        NV_Ith_S(rDY, 4) = d_dt_i_Na_L_h_L_gate__h_L;
        NV_Ith_S(rDY, 5) = d_dt_i_Ca_L_d_gate__d;
        NV_Ith_S(rDY, 6) = d_dt_i_Ca_L_f_gate__f;
        NV_Ith_S(rDY, 7) = d_dt_i_Ca_L_f2_gate__f2;
        NV_Ith_S(rDY, 8) = d_dt_i_Ca_L_f_Ca_gate__f_Ca;
        NV_Ith_S(rDY, 9) = d_dt_i_Ca_L_f_Ca2_gate__f_Ca2;
        NV_Ith_S(rDY, 10) = d_dt_i_to_1_a_gate__a;
        NV_Ith_S(rDY, 11) = d_dt_i_to_1_i_gate__i;
        NV_Ith_S(rDY, 12) = d_dt_i_to_1_i2_gate__i2;
        NV_Ith_S(rDY, 13) = d_dt_i_Kr_xr_gate__xr;
        NV_Ith_S(rDY, 14) = d_dt_i_Ks_xs1_gate__xs1;
        NV_Ith_S(rDY, 15) = d_dt_i_Ks_xs2_gate__xs2;
        NV_Ith_S(rDY, 16) = d_dt_i_to_2_a_gate__a;
        NV_Ith_S(rDY, 17) = d_dt_intracellular_ion_concentrations__Na_i;
        NV_Ith_S(rDY, 18) = d_dt_intracellular_ion_concentrations__Cl_i;
        NV_Ith_S(rDY, 19) = d_dt_intracellular_ion_concentrations__K_i;
        NV_Ith_S(rDY, 20) = d_dt_Ca_i__Ca_i;
        NV_Ith_S(rDY, 21) = d_dt_Ca_MK_act__Ca_MK_trap;
        NV_Ith_S(rDY, 22) = d_dt_Ca_NSR__Ca_NSR;
        NV_Ith_S(rDY, 23) = d_dt_Ca_JSR__Ca_JSR;
        NV_Ith_S(rDY, 24) = d_dt_Ca_r__Ca_r;
        NV_Ith_S(rDY, 25) = d_dt_q_rel_ri_gate__ri;
        NV_Ith_S(rDY, 26) = d_dt_q_rel_ro_gate__ro;
    }

    N_Vector Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::ComputeDerivedQuantities(double var_environment__time, const N_Vector & rY)
    {
        // Inputs:
        // Time units: millisecond
        const double var_i_Ca_L_d_gate__d = NV_Ith_S(rY, 5);
        // Units: dimensionless; Initial value: 0.000002322223865147363
        const double var_i_Ca_L_f_gate__f = NV_Ith_S(rY, 6);
        // Units: dimensionless; Initial value: 0.9985607329462358
        const double var_i_Ca_L_f2_gate__f2 = NV_Ith_S(rY, 7);
        // Units: dimensionless; Initial value: 0.8173435436674658
        const double var_i_Ca_L_f_Ca_gate__f_Ca = NV_Ith_S(rY, 8);
        // Units: dimensionless; Initial value: 0.9610551285529658
        const double var_i_Ca_L_f_Ca2_gate__f_Ca2 = NV_Ith_S(rY, 9);
        // Units: dimensionless; Initial value: 0.868690796671854
        const double var_Ca_r__Ca_r = NV_Ith_S(rY, 24);
        // Units: millimolar; Initial value: 0.00022418117117903934


        // Mathematics
        const double var_membrane__V = NV_Ith_S(mParameters, 0); // millivolt
        const double var_i_Ca_L__i_Ca_L_max = ((((var_membrane__V - 15.0) * 9048693.2787) * 3.87996927064e-07) * ((1.0 * var_Ca_r__Ca_r * exp(((var_membrane__V - 15.0) * 192970.0) * 3.87996927064e-07)) - 0.6138)) / (exp(((var_membrane__V - 15.0) * 192970.0) * 3.87996927064e-07) - 1.0); // microA_per_microF
        var_i_Ca_L__g_Ca_L = 0.3392328; // dimensionless
        const double var_i_Ca_L__i_Ca_L = var_i_Ca_L__g_Ca_L * var_i_Ca_L_d_gate__d * var_i_Ca_L_f_gate__f * var_i_Ca_L_f2_gate__f2 * var_i_Ca_L_f_Ca_gate__f_Ca * var_i_Ca_L_f_Ca2_gate__f_Ca2 * var_i_Ca_L__i_Ca_L_max; // microA_per_microF

        N_Vector dqs = N_VNew_Serial(2);
        NV_Ith_S(dqs, 0) = var_i_Ca_L__i_Ca_L;
        NV_Ith_S(dqs, 1) = var_membrane__V;
        return dqs;
    }

    void Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled::SolveModel(double endPoint)
    {
        SolveAndUpdateState(this->mFreeVariable, endPoint);
        this->mFreeVariable = endPoint;
    }

template<>
void OdeSystemInformation<Aslanidi_Purkinje_model_2009FromCellMLCvodeLHopitaled>::Initialise(void)
{
    // Time units: millisecond
    //
    this->mSystemName = "aslanidi_2009_lhopitaled";

    this->mVariableNames.push_back("membrane_fast_sodium_current_m_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.002003390432234504);

    this->mVariableNames.push_back("membrane_fast_sodium_current_h_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9786390933308567);

    this->mVariableNames.push_back("membrane_fast_sodium_current_j_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.09866447258167589);

    this->mVariableNames.push_back("i_Na_L_m_L_gate__m_L");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.002003390432234504);

    this->mVariableNames.push_back("i_Na_L_h_L_gate__h_L");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.8946968372659203);

    this->mVariableNames.push_back("membrane_L_type_calcium_current_d_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.000002322223865147363);

    this->mVariableNames.push_back("membrane_L_type_calcium_current_f_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9985607329462358);

    this->mVariableNames.push_back("membrane_L_type_calcium_current_f2_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.8173435436674658);

    this->mVariableNames.push_back("membrane_L_type_calcium_current_fCa_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9610551285529658);

    this->mVariableNames.push_back("membrane_L_type_calcium_current_fCa2_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.868690796671854);

    this->mVariableNames.push_back("i_to_1_a_gate__a");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0004238729429342389);

    this->mVariableNames.push_back("i_to_1_i_gate__i");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9990935802459496);

    this->mVariableNames.push_back("i_to_1_i2_gate__i2");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9777368439681764);

    this->mVariableNames.push_back("i_Kr_xr_gate__xr");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.07084939408222911);

    this->mVariableNames.push_back("i_Ks_xs1_gate__xs1");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0011737654433043125);

    this->mVariableNames.push_back("i_Ks_xs2_gate__xs2");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.001179442867470093);

    this->mVariableNames.push_back("i_to_2_a_gate__a");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0014909437525000811);

    this->mVariableNames.push_back("cytosolic_sodium_concentration");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(9.927155552932733);

    this->mVariableNames.push_back("intracellular_ion_concentrations__Cl_i");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(18.904682470140408);

    this->mVariableNames.push_back("cytosolic_potassium_concentration");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(141.9670801746057);

    this->mVariableNames.push_back("cytosolic_calcium_concentration");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(0.00022355433459434943);

    this->mVariableNames.push_back("Ca_MK_act__Ca_MK_trap");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.000008789168284782809);

    this->mVariableNames.push_back("Ca_NSR__Ca_NSR");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(1.2132524695849454);

    this->mVariableNames.push_back("Ca_JSR__Ca_JSR");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(1.1433050636518596);

    this->mVariableNames.push_back("diadicspace_calcium_concentration");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(0.00022418117117903934);

    this->mVariableNames.push_back("q_rel_ri_gate__ri");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.7802870066567904);

    this->mVariableNames.push_back("q_rel_ro_gate__ro");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(1.2785734760674763e-9);

    this->mParameterNames.push_back("membrane_voltage_value");
    this->mParameterUnits.push_back("millivolt");

    this->mDerivedQuantityNames.push_back("membrane_L_type_calcium_current");
    this->mDerivedQuantityUnits.push_back("microA_per_microF");

    this->mDerivedQuantityNames.push_back("membrane_voltage");
    this->mDerivedQuantityUnits.push_back("millivolt");

    this->mInitialised = true;
}


#endif // CHASTE_CVODE
