# Gnuplot script file generated by Chaste.
# Second plot is of the resulting restitution curve.
set terminal postscript eps size 3, 2 font 16
set output "/export/wolf1768/testoutput/CellModelTests/bondarenko_szigeti_bett_kim_rasmusson_2004_apical/S1S2/bondarenko_szigeti_bett_kim_rasmusson_2004_apical_s1s2_curve.eps"
set title "Bondarenko Szigeti Bett Kim Rasmusson 2004 Apical"
set xlabel "Diastolic Interval (ms)"
set xtics 400
set ylabel "APD90 (ms)"
set grid
set autoscale
set key off
plot "/export/wolf1768/testoutput/CellModelTests/bondarenko_szigeti_bett_kim_rasmusson_2004_apical/S1S2/s1s2_curve.dat" using 1:2 with linespoints pointtype 7
