#ifdef CHASTE_CVODE
//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: bondarenko_2004_apical
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translators: 12282, pycml: 12383, optimize: 12047)
//! on Tue Apr 12 18:31:55 2011
//! 
//! <autogenerated>

#include "bondarenko_szigeti_bett_kim_rasmusson_2004_apical.hpp"
#include <cmath>
#include <cassert>
#include <memory>
#include "Exception.hpp"
#include "OdeSystemInformation.hpp"
#include "RegularStimulus.hpp"
#include "HeartConfig.hpp"
#include "IsNan.hpp"

    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__calcium_concentration__CaJSR()
    {
        return var_chaste_interface__calcium_concentration__CaJSR;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_calcium_fluxes__J_rel()
    {
        return var_calcium_fluxes__J_rel;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__calcium_concentration__Cai()
    {
        return var_chaste_interface__calcium_concentration__Cai;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__potassium_concentration__Ki()
    {
        return var_chaste_interface__potassium_concentration__Ki;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__sodium_concentration__Nai()
    {
        return var_chaste_interface__sodium_concentration__Nai;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__calcium_concentration__Cass()
    {
        return var_chaste_interface__calcium_concentration__Cass;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__i_ionic()
    {
        return var_chaste_interface__i_ionic;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__L_type_calcium_current__i_CaL()
    {
        return var_chaste_interface__L_type_calcium_current__i_CaL;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane__Cm()
    {
        return var_membrane__Cm;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__fast_sodium_current__i_Na()
    {
        return var_chaste_interface__fast_sodium_current__i_Na;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__time_independent_potassium_current__i_K1()
    {
        return var_chaste_interface__time_independent_potassium_current__i_K1;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__rapid_delayed_rectifier_potassium_current__i_Kr()
    {
        return var_chaste_interface__rapid_delayed_rectifier_potassium_current__i_Kr;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__slow_delayed_rectifier_potassium_current__i_Ks()
    {
        return var_chaste_interface__slow_delayed_rectifier_potassium_current__i_Ks;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__sodium_calcium_exchange_current__i_NaCa()
    {
        return var_chaste_interface__sodium_calcium_exchange_current__i_NaCa;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__membrane__i_stim()
    {
        return var_chaste_interface__membrane__i_stim;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__membrane__stim_amplitude()
    {
        return var_chaste_interface__membrane__stim_amplitude;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__membrane__stim_duration()
    {
        return var_chaste_interface__membrane__stim_duration;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__membrane__stim_start()
    {
        return var_chaste_interface__membrane__stim_start;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__membrane__stim_period()
    {
        return var_chaste_interface__membrane__stim_period;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__fast_transient_outward_potassium_current__i_Kto_f()
    {
        return var_chaste_interface__fast_transient_outward_potassium_current__i_Kto_f;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__membrane__V()
    {
        return var_chaste_interface__membrane__V;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_chaste_interface__environment__time()
    {
        return var_chaste_interface__environment__time;
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_SR_leak_current_max_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 0);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_SR_release_current_max_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 1);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_SR_uptake_current_max_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 2);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_concentration_clamp_onoff_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 3);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_extracellular_calcium_concentration_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 4);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_extracellular_potassium_concentration_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 5);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_L_type_calcium_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 6);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_fast_sodium_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 7);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_fast_sodium_current_shift_inactivation_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 8);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_inward_rectifier_potassium_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 9);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_rapid_delayed_rectifier_potassium_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 10);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_slow_delayed_rectifier_potassium_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 11);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_sodium_calcium_exchanger_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 12);
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_stimulus_current_amplitude_constant()
    {
        // Constant value given in CellML
        var_chaste_interface__membrane__stim_amplitude =  -80.0 * HeartConfig::Instance()->GetCapacitance(); // uA_per_cm2
        return var_chaste_interface__membrane__stim_amplitude;
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_stimulus_current_duration_constant()
    {
        // Constant value given in CellML
        var_chaste_interface__membrane__stim_duration = 0.5; // millisecond
        return var_chaste_interface__membrane__stim_duration;
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_stimulus_current_offset_constant()
    {
        // Constant value given in CellML
        var_chaste_interface__membrane__stim_start = 100.0; // millisecond
        return var_chaste_interface__membrane__stim_start;
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_stimulus_current_period_constant()
    {
        // Constant value given in CellML
        var_chaste_interface__membrane__stim_period = 71.43; // millisecond
        return var_chaste_interface__membrane__stim_period;
    }
    
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Get_membrane_transient_outward_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 13);
    }
    
    
    void Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::UseCellMLDefaultStimulus()
    {
        // Use the default stimulus specified by CellML metadata
        var_chaste_interface__membrane__stim_start = 100.0; // millisecond
        var_chaste_interface__membrane__stim_period = 71.43; // millisecond
        var_chaste_interface__membrane__stim_duration = 0.5; // millisecond
        var_chaste_interface__membrane__stim_amplitude =  -80.0 * HeartConfig::Instance()->GetCapacitance(); // uA_per_cm2
        mpIntracellularStimulus.reset(new RegularStimulus(
                -fabs(var_chaste_interface__membrane__stim_amplitude),
                var_chaste_interface__membrane__stim_duration,
                var_chaste_interface__membrane__stim_period,
                var_chaste_interface__membrane__stim_start));
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::GetIntracellularCalciumConcentration()
    {
        return NV_Ith_S(mStateVariables, 1);
    }
    
    Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode(boost::shared_ptr<AbstractIvpOdeSolver> pOdeSolver /* unused; should be empty */, boost::shared_ptr<AbstractStimulusFunction> pIntracellularStimulus)
        : AbstractCvodeCell(
                pOdeSolver,
                41,
                0,
                pIntracellularStimulus)
    {
        // Time units: millisecond
        // 
        this->mpSystemInfo = OdeSystemInformation<Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode>::Instance();
        Init();

        // We have a default stimulus specified in the CellML file metadata
        this->mHasDefaultStimulusFromCellML = true;
        NV_Ith_S(this->mParameters, 0) = 1.74e-5; // (c,calcium_fluxes__v2) [per_millisecond]
        NV_Ith_S(this->mParameters, 1) = 4.5; // (c,calcium_fluxes__v1) [per_millisecond]
        NV_Ith_S(this->mParameters, 2) = 0.45; // (c,calcium_fluxes__v3) [micromolar_per_millisecond]
        NV_Ith_S(this->mParameters, 3) = 1; // (c,sodium_concentration__conc_clamp) [dimensionless]
        NV_Ith_S(this->mParameters, 4) = 1800; // (c,membrane__Cao) [micromolar]
        NV_Ith_S(this->mParameters, 5) = 5400; // (c,membrane__Ko) [micromolar]
        NV_Ith_S(this->mParameters, 6) = 0.1729; // (c,L_type_calcium_current__g_CaL) [milliS_per_microF]
        NV_Ith_S(this->mParameters, 7) = 13; // (c,fast_sodium_current__g_Na) [milliS_per_microF]
        NV_Ith_S(this->mParameters, 8) = 0; // (c,fast_sodium_current__shift_INa_inact) [millivolt]
        NV_Ith_S(this->mParameters, 9) = 0.2938; // (c,time_independent_potassium_current__g_K1) [milliS_per_microF]
        NV_Ith_S(this->mParameters, 10) = 0.078; // (c,rapid_delayed_rectifier_potassium_current__g_Kr) [milliS_per_microF]
        NV_Ith_S(this->mParameters, 11) = 0.00575; // (c,slow_delayed_rectifier_potassium_current__g_Ks) [milliS_per_microF]
        NV_Ith_S(this->mParameters, 12) = 292.8; // (c,sodium_calcium_exchange_current__k_NaCa) [picoA_per_picoF]
        NV_Ith_S(this->mParameters, 13) = 0.4067; // (c,fast_transient_outward_potassium_current__g_Kto_f) [milliS_per_microF]
        // Protocol outputs
        this->mOutputsInfo.resize(2);
        this->mOutputsInfo[0] = std::make_pair(0, STATE);
        this->mOutputsInfo[1] = std::make_pair(UNSIGNED_UNSET, FREE);
        
    }
    
    Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::~Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode()
    {
    }
    
    void Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::VerifyStateVariables()
    {
        
    }
    
    double Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::GetIIonic(const std::vector<double>* pStateVariables)
    {
        N_Vector rY = rGetStateVariables();
        double var_chaste_interface__membrane__V = NV_Ith_S(rY, 0);
        // Units: millivolt; Initial value: -82.4202
        double var_chaste_interface__calcium_concentration__Cai = NV_Ith_S(rY, 1);
        // Units: micromolar; Initial value: 0.115001
        double var_chaste_interface__L_type_calcium_current__O = NV_Ith_S(rY, 11);
        // Units: dimensionless; Initial value: 0.930308e-18
        double var_chaste_interface__sodium_concentration__Nai = NV_Ith_S(rY, 18);
        // Units: micromolar; Initial value: 14237.1
        double var_chaste_interface__fast_sodium_current__O_Na = NV_Ith_S(rY, 19);
        // Units: dimensionless; Initial value: 0.713483e-6
        double var_chaste_interface__potassium_concentration__Ki = NV_Ith_S(rY, 27);
        // Units: micromolar; Initial value: 143720
        double var_chaste_interface__fast_transient_outward_potassium_current__ato_f = NV_Ith_S(rY, 28);
        // Units: dimensionless; Initial value: 0.265563e-2
        double var_chaste_interface__fast_transient_outward_potassium_current__ito_f = NV_Ith_S(rY, 29);
        // Units: dimensionless; Initial value: 0.999977
        double var_chaste_interface__slow_transient_outward_potassium_current__ato_s = NV_Ith_S(rY, 30);
        // Units: dimensionless; Initial value: 0.417069e-3
        double var_chaste_interface__slow_transient_outward_potassium_current__ito_s = NV_Ith_S(rY, 31);
        // Units: dimensionless; Initial value: 0.998543
        double var_chaste_interface__slow_delayed_rectifier_potassium_current__nKs = NV_Ith_S(rY, 32);
        // Units: dimensionless; Initial value: 0.262753e-3
        double var_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__aur = NV_Ith_S(rY, 33);
        // Units: dimensionless; Initial value: 0.417069e-3
        double var_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__iur = NV_Ith_S(rY, 34);
        // Units: dimensionless; Initial value: 0.998543
        double var_chaste_interface__non_inactivating_steady_state_potassium_current__aKss = NV_Ith_S(rY, 35);
        // Units: dimensionless; Initial value: 0.417069e-3
        double var_chaste_interface__non_inactivating_steady_state_potassium_current__iKss = NV_Ith_S(rY, 36);
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K = NV_Ith_S(rY, 37);
        // Units: dimensionless; Initial value: 0.175298e-3
        
        const double var_L_type_calcium_current__i_CaL = NV_Ith_S(mParameters, 6) * var_chaste_interface__L_type_calcium_current__O * (var_chaste_interface__membrane__V - 63.0); // picoA_per_picoF
        const double var_calcium_pump_current__i_pCa = (1.0 * pow(var_chaste_interface__calcium_concentration__Cai, 2.0)) / (0.25 + pow(var_chaste_interface__calcium_concentration__Cai, 2.0)); // picoA_per_picoF
        const double var_sodium_calcium_exchange_current__i_NaCa = ((((((NV_Ith_S(mParameters, 12) * 1.0) * 2.92918243772e-16) * 1.0) / (1380.0 + NV_Ith_S(mParameters, 4))) * 1.0) / (1.0 + (0.1 * exp((var_chaste_interface__membrane__V *  -62.725) * 0.000403620964396)))) * ((exp((var_chaste_interface__membrane__V * 33.775) * 0.000403620964396) * pow(var_chaste_interface__sodium_concentration__Nai, 3.0) * NV_Ith_S(mParameters, 4)) - (exp((var_chaste_interface__membrane__V *  -62.725) * 0.000403620964396) * 2.744e+15 * var_chaste_interface__calcium_concentration__Cai)); // picoA_per_picoF
        const double var_calcium_background_current__i_Cab = 0.000367 * (var_chaste_interface__membrane__V - (12.8371606218 * log(NV_Ith_S(mParameters, 4) / var_chaste_interface__calcium_concentration__Cai))); // picoA_per_picoF
        const double var_fast_sodium_current__E_Na = 25.6743212435 * log((126000.0 + (0.1 * NV_Ith_S(mParameters, 5))) / ((0.9 * var_chaste_interface__sodium_concentration__Nai) + (0.1 * var_chaste_interface__potassium_concentration__Ki))); // millivolt
        const double var_fast_sodium_current__i_Na = NV_Ith_S(mParameters, 7) * var_chaste_interface__fast_sodium_current__O_Na * (var_chaste_interface__membrane__V - var_fast_sodium_current__E_Na); // picoA_per_picoF
        const double var_sodium_background_current__i_Nab = 0.0026 * (var_chaste_interface__membrane__V - var_fast_sodium_current__E_Na); // picoA_per_picoF
        const double var_sodium_potassium_pump_current__i_NaK = ((((1.0 / (1.0 + (0.1245 * exp((var_chaste_interface__membrane__V *  -9.65) * 0.000403620964396)) + (exp(((-var_chaste_interface__membrane__V) * 96.5) * 0.000403620964396) * 0.0365332261305))) * 0.88) / (1.0 + pow(21000.0 / var_chaste_interface__sodium_concentration__Nai, 1.5))) * NV_Ith_S(mParameters, 5)) / (NV_Ith_S(mParameters, 5) + 1500.0); // picoA_per_picoF
        const double var_fast_transient_outward_potassium_current__E_K = 25.6743212435 * log(NV_Ith_S(mParameters, 5) / var_chaste_interface__potassium_concentration__Ki); // millivolt
        const double var_fast_transient_outward_potassium_current__i_Kto_f = NV_Ith_S(mParameters, 13) * pow(var_chaste_interface__fast_transient_outward_potassium_current__ato_f, 3.0) * var_chaste_interface__fast_transient_outward_potassium_current__ito_f * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_slow_transient_outward_potassium_current__i_Kto_s = 0.0 * var_chaste_interface__slow_transient_outward_potassium_current__ato_s * var_chaste_interface__slow_transient_outward_potassium_current__ito_s * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_time_independent_potassium_current__i_K1 = (((NV_Ith_S(mParameters, 9) * NV_Ith_S(mParameters, 5)) / (NV_Ith_S(mParameters, 5) + 210.0)) * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K)) / (1.0 + exp(0.0896 * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K))); // picoA_per_picoF
        const double var_slow_delayed_rectifier_potassium_current__i_Ks = NV_Ith_S(mParameters, 11) * pow(var_chaste_interface__slow_delayed_rectifier_potassium_current__nKs, 2.0) * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__i_Kur = 0.16 * var_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__aur * var_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__iur * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_non_inactivating_steady_state_potassium_current__i_Kss = 0.05 * var_chaste_interface__non_inactivating_steady_state_potassium_current__aKss * var_chaste_interface__non_inactivating_steady_state_potassium_current__iKss * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_calcium_activated_chloride_current__i_ClCa = ((10.0 * (0.2 / (1.0 + exp((-(var_chaste_interface__membrane__V - 46.7)) * 0.128205128205))) * var_chaste_interface__calcium_concentration__Cai) / (var_chaste_interface__calcium_concentration__Cai + 10.0)) * (var_chaste_interface__membrane__V -  -40.0); // picoA_per_picoF
        const double var_rapid_delayed_rectifier_potassium_current__i_Kr = NV_Ith_S(mParameters, 10) * var_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K * (var_chaste_interface__membrane__V - (25.6743212435 * log(((0.98 * NV_Ith_S(mParameters, 5)) + 2800.0) / ((0.98 * var_chaste_interface__potassium_concentration__Ki) + (0.02 * var_chaste_interface__sodium_concentration__Nai))))); // picoA_per_picoF
        const double var_chaste_interface__slow_delayed_rectifier_potassium_current__i_Ks = var_slow_delayed_rectifier_potassium_current__i_Ks; // picoA_per_picoF
        const double var_chaste_interface__fast_sodium_current__i_Na = var_fast_sodium_current__i_Na; // picoA_per_picoF
        const double var_chaste_interface__L_type_calcium_current__i_CaL = var_L_type_calcium_current__i_CaL; // picoA_per_picoF
        const double var_chaste_interface__time_independent_potassium_current__i_K1 = var_time_independent_potassium_current__i_K1; // picoA_per_picoF
        const double var_chaste_interface__rapid_delayed_rectifier_potassium_current__i_Kr = var_rapid_delayed_rectifier_potassium_current__i_Kr; // picoA_per_picoF
        const double var_chaste_interface__fast_transient_outward_potassium_current__i_Kto_f = var_fast_transient_outward_potassium_current__i_Kto_f; // picoA_per_picoF
        const double var_chaste_interface__sodium_calcium_exchange_current__i_NaCa = var_sodium_calcium_exchange_current__i_NaCa; // picoA_per_picoF
        var_chaste_interface__i_ionic = (var_chaste_interface__L_type_calcium_current__i_CaL + var_calcium_pump_current__i_pCa + var_chaste_interface__sodium_calcium_exchange_current__i_NaCa + var_calcium_background_current__i_Cab + var_chaste_interface__fast_sodium_current__i_Na + var_sodium_background_current__i_Nab + var_sodium_potassium_pump_current__i_NaK + var_chaste_interface__fast_transient_outward_potassium_current__i_Kto_f + var_slow_transient_outward_potassium_current__i_Kto_s + var_chaste_interface__time_independent_potassium_current__i_K1 + var_chaste_interface__slow_delayed_rectifier_potassium_current__i_Ks + var_ultra_rapidly_activating_delayed_rectifier_potassium_current__i_Kur + var_non_inactivating_steady_state_potassium_current__i_Kss + var_chaste_interface__rapid_delayed_rectifier_potassium_current__i_Kr + var_calcium_activated_chloride_current__i_ClCa) * HeartConfig::Instance()->GetCapacitance(); // uA_per_cm2
        
        const double i_ionic = var_chaste_interface__i_ionic;
        EXCEPT_IF_NOT(!std::isnan(i_ionic));
        return i_ionic;
    }
    
    void Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::EvaluateRhs(double var_chaste_interface__environment__time, const N_Vector rY, N_Vector rDY)
    {
        // Inputs:
        // Time units: millisecond
        double var_chaste_interface__membrane__V = NV_Ith_S(rY, 0);
        // Units: millivolt; Initial value: -82.4202
        double var_chaste_interface__calcium_concentration__Cai = NV_Ith_S(rY, 1);
        // Units: micromolar; Initial value: 0.115001
        double var_chaste_interface__calcium_concentration__Cass = NV_Ith_S(rY, 2);
        // Units: micromolar; Initial value: 0.115001
        double var_chaste_interface__calcium_concentration__CaJSR = NV_Ith_S(rY, 3);
        // Units: micromolar; Initial value: 1299.5
        double var_chaste_interface__calcium_concentration__CaNSR = NV_Ith_S(rY, 4);
        // Units: micromolar; Initial value: 1299.5
        double var_chaste_interface__calcium_fluxes__P_RyR = NV_Ith_S(rY, 5);
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__calcium_buffering__LTRPN_Ca = NV_Ith_S(rY, 6);
        // Units: micromolar; Initial value: 11.2684
        double var_chaste_interface__calcium_buffering__HTRPN_Ca = NV_Ith_S(rY, 7);
        // Units: micromolar; Initial value: 125.29
        double var_chaste_interface__ryanodine_receptors__P_O1 = NV_Ith_S(rY, 8);
        // Units: dimensionless; Initial value: 0.149102e-4
        double var_chaste_interface__ryanodine_receptors__P_O2 = NV_Ith_S(rY, 9);
        // Units: dimensionless; Initial value: 0.951726e-10
        double var_chaste_interface__ryanodine_receptors__P_C2 = NV_Ith_S(rY, 10);
        // Units: dimensionless; Initial value: 0.16774e-3
        double var_chaste_interface__L_type_calcium_current__O = NV_Ith_S(rY, 11);
        // Units: dimensionless; Initial value: 0.930308e-18
        double var_chaste_interface__L_type_calcium_current__C2 = NV_Ith_S(rY, 12);
        // Units: dimensionless; Initial value: 0.124216e-3
        double var_chaste_interface__L_type_calcium_current__C3 = NV_Ith_S(rY, 13);
        // Units: dimensionless; Initial value: 0.578679e-8
        double var_chaste_interface__L_type_calcium_current__C4 = NV_Ith_S(rY, 14);
        // Units: dimensionless; Initial value: 0.119816e-12
        double var_chaste_interface__L_type_calcium_current__I1 = NV_Ith_S(rY, 15);
        // Units: dimensionless; Initial value: 0.497923e-18
        double var_chaste_interface__L_type_calcium_current__I2 = NV_Ith_S(rY, 16);
        // Units: dimensionless; Initial value: 0.345847e-13
        double var_chaste_interface__L_type_calcium_current__I3 = NV_Ith_S(rY, 17);
        // Units: dimensionless; Initial value: 0.185106e-13
        double var_chaste_interface__sodium_concentration__Nai = NV_Ith_S(rY, 18);
        // Units: micromolar; Initial value: 14237.1
        double var_chaste_interface__fast_sodium_current__O_Na = NV_Ith_S(rY, 19);
        // Units: dimensionless; Initial value: 0.713483e-6
        double var_chaste_interface__fast_sodium_current__C_Na1 = NV_Ith_S(rY, 20);
        // Units: dimensionless; Initial value: 0.279132e-3
        double var_chaste_interface__fast_sodium_current__C_Na2 = NV_Ith_S(rY, 21);
        // Units: dimensionless; Initial value: 0.020752
        double var_chaste_interface__fast_sodium_current__I1_Na = NV_Ith_S(rY, 22);
        // Units: dimensionless; Initial value: 0.673345e-6
        double var_chaste_interface__fast_sodium_current__I2_Na = NV_Ith_S(rY, 23);
        // Units: dimensionless; Initial value: 0.155787e-8
        double var_chaste_interface__fast_sodium_current__IF_Na = NV_Ith_S(rY, 24);
        // Units: dimensionless; Initial value: 0.153176e-3
        double var_chaste_interface__fast_sodium_current__IC_Na2 = NV_Ith_S(rY, 25);
        // Units: dimensionless; Initial value: 0.0113879
        double var_chaste_interface__fast_sodium_current__IC_Na3 = NV_Ith_S(rY, 26);
        // Units: dimensionless; Initial value: 0.34278
        double var_chaste_interface__potassium_concentration__Ki = NV_Ith_S(rY, 27);
        // Units: micromolar; Initial value: 143720
        double var_chaste_interface__fast_transient_outward_potassium_current__ato_f = NV_Ith_S(rY, 28);
        // Units: dimensionless; Initial value: 0.265563e-2
        double var_chaste_interface__fast_transient_outward_potassium_current__ito_f = NV_Ith_S(rY, 29);
        // Units: dimensionless; Initial value: 0.999977
        double var_chaste_interface__slow_transient_outward_potassium_current__ato_s = NV_Ith_S(rY, 30);
        // Units: dimensionless; Initial value: 0.417069e-3
        double var_chaste_interface__slow_transient_outward_potassium_current__ito_s = NV_Ith_S(rY, 31);
        // Units: dimensionless; Initial value: 0.998543
        double var_chaste_interface__slow_delayed_rectifier_potassium_current__nKs = NV_Ith_S(rY, 32);
        // Units: dimensionless; Initial value: 0.262753e-3
        double var_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__aur = NV_Ith_S(rY, 33);
        // Units: dimensionless; Initial value: 0.417069e-3
        double var_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__iur = NV_Ith_S(rY, 34);
        // Units: dimensionless; Initial value: 0.998543
        double var_chaste_interface__non_inactivating_steady_state_potassium_current__aKss = NV_Ith_S(rY, 35);
        // Units: dimensionless; Initial value: 0.417069e-3
        double var_chaste_interface__non_inactivating_steady_state_potassium_current__iKss = NV_Ith_S(rY, 36);
        // Units: dimensionless; Initial value: 1
        double var_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K = NV_Ith_S(rY, 37);
        // Units: dimensionless; Initial value: 0.175298e-3
        double var_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K1 = NV_Ith_S(rY, 38);
        // Units: dimensionless; Initial value: 0.992513e-3
        double var_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K2 = NV_Ith_S(rY, 39);
        // Units: dimensionless; Initial value: 0.641229e-3
        double var_chaste_interface__rapid_delayed_rectifier_potassium_current__I_K = NV_Ith_S(rY, 40);
        // Units: dimensionless; Initial value: 0.319129e-4
        
        
        // Mathematics
        double d_dt_chaste_interface__membrane__V;
        var_membrane__Cm = 1.0; // microF_per_cm2
        const double var_L_type_calcium_current__i_CaL = NV_Ith_S(mParameters, 6) * var_chaste_interface__L_type_calcium_current__O * (var_chaste_interface__membrane__V - 63.0); // picoA_per_picoF
        const double var_calcium_pump_current__i_pCa = (1.0 * pow(var_chaste_interface__calcium_concentration__Cai, 2.0)) / (0.25 + pow(var_chaste_interface__calcium_concentration__Cai, 2.0)); // picoA_per_picoF
        const double var_sodium_calcium_exchange_current__i_NaCa = ((((((NV_Ith_S(mParameters, 12) * 1.0) * 2.92918243772e-16) * 1.0) / (1380.0 + NV_Ith_S(mParameters, 4))) * 1.0) / (1.0 + (0.1 * exp((var_chaste_interface__membrane__V *  -62.725) * 0.000403620964396)))) * ((exp((var_chaste_interface__membrane__V * 33.775) * 0.000403620964396) * pow(var_chaste_interface__sodium_concentration__Nai, 3.0) * NV_Ith_S(mParameters, 4)) - (exp((var_chaste_interface__membrane__V *  -62.725) * 0.000403620964396) * 2.744e+15 * var_chaste_interface__calcium_concentration__Cai)); // picoA_per_picoF
        const double var_calcium_background_current__i_Cab = 0.000367 * (var_chaste_interface__membrane__V - (12.8371606218 * log(NV_Ith_S(mParameters, 4) / var_chaste_interface__calcium_concentration__Cai))); // picoA_per_picoF
        const double var_fast_sodium_current__E_Na = 25.6743212435 * log((126000.0 + (0.1 * NV_Ith_S(mParameters, 5))) / ((0.9 * var_chaste_interface__sodium_concentration__Nai) + (0.1 * var_chaste_interface__potassium_concentration__Ki))); // millivolt
        const double var_fast_sodium_current__i_Na = NV_Ith_S(mParameters, 7) * var_chaste_interface__fast_sodium_current__O_Na * (var_chaste_interface__membrane__V - var_fast_sodium_current__E_Na); // picoA_per_picoF
        const double var_sodium_background_current__i_Nab = 0.0026 * (var_chaste_interface__membrane__V - var_fast_sodium_current__E_Na); // picoA_per_picoF
        const double var_sodium_potassium_pump_current__i_NaK = ((((1.0 / (1.0 + (0.1245 * exp((var_chaste_interface__membrane__V *  -9.65) * 0.000403620964396)) + (exp(((-var_chaste_interface__membrane__V) * 96.5) * 0.000403620964396) * 0.0365332261305))) * 0.88) / (1.0 + pow(21000.0 / var_chaste_interface__sodium_concentration__Nai, 1.5))) * NV_Ith_S(mParameters, 5)) / (NV_Ith_S(mParameters, 5) + 1500.0); // picoA_per_picoF
        const double var_fast_transient_outward_potassium_current__E_K = 25.6743212435 * log(NV_Ith_S(mParameters, 5) / var_chaste_interface__potassium_concentration__Ki); // millivolt
        const double var_fast_transient_outward_potassium_current__i_Kto_f = NV_Ith_S(mParameters, 13) * pow(var_chaste_interface__fast_transient_outward_potassium_current__ato_f, 3.0) * var_chaste_interface__fast_transient_outward_potassium_current__ito_f * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_slow_transient_outward_potassium_current__i_Kto_s = 0.0 * var_chaste_interface__slow_transient_outward_potassium_current__ato_s * var_chaste_interface__slow_transient_outward_potassium_current__ito_s * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_time_independent_potassium_current__i_K1 = (((NV_Ith_S(mParameters, 9) * NV_Ith_S(mParameters, 5)) / (NV_Ith_S(mParameters, 5) + 210.0)) * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K)) / (1.0 + exp(0.0896 * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K))); // picoA_per_picoF
        const double var_slow_delayed_rectifier_potassium_current__i_Ks = NV_Ith_S(mParameters, 11) * pow(var_chaste_interface__slow_delayed_rectifier_potassium_current__nKs, 2.0) * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_ultra_rapidly_activating_delayed_rectifier_potassium_current__i_Kur = 0.16 * var_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__aur * var_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__iur * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_non_inactivating_steady_state_potassium_current__i_Kss = 0.05 * var_chaste_interface__non_inactivating_steady_state_potassium_current__aKss * var_chaste_interface__non_inactivating_steady_state_potassium_current__iKss * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_rapid_delayed_rectifier_potassium_current__i_Kr = NV_Ith_S(mParameters, 10) * var_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K * (var_chaste_interface__membrane__V - (25.6743212435 * log(((0.98 * NV_Ith_S(mParameters, 5)) + 2800.0) / ((0.98 * var_chaste_interface__potassium_concentration__Ki) + (0.02 * var_chaste_interface__sodium_concentration__Nai))))); // picoA_per_picoF
        const double var_calcium_fluxes__J_leak = NV_Ith_S(mParameters, 0) * (var_chaste_interface__calcium_concentration__CaNSR - var_chaste_interface__calcium_concentration__Cai); // micromolar_per_millisecond
        const double var_calcium_fluxes__J_rel = NV_Ith_S(mParameters, 1) * (var_chaste_interface__ryanodine_receptors__P_O1 + var_chaste_interface__ryanodine_receptors__P_O2) * (var_chaste_interface__calcium_concentration__CaJSR - var_chaste_interface__calcium_concentration__Cass) * var_chaste_interface__calcium_fluxes__P_RyR; // micromolar_per_millisecond
        const double var_calcium_fluxes__J_up = (NV_Ith_S(mParameters, 2) * pow(var_chaste_interface__calcium_concentration__Cai, 2.0)) / (0.25 + pow(var_chaste_interface__calcium_concentration__Cai, 2.0)); // micromolar_per_millisecond
        const double var_calcium_fluxes__J_tr = (var_chaste_interface__calcium_concentration__CaNSR - var_chaste_interface__calcium_concentration__CaJSR) * 0.05; // micromolar_per_millisecond
        const double var_calcium_fluxes__J_xfer = (var_chaste_interface__calcium_concentration__Cass - var_chaste_interface__calcium_concentration__Cai) * 0.125; // micromolar_per_millisecond
        const double var_L_type_calcium_current__alpha = (0.4 * exp((var_chaste_interface__membrane__V + 12.0) * 0.1) * ((1.0 + (0.7 * exp((-pow(var_chaste_interface__membrane__V + 40.0, 2.0)) * 0.1))) - (0.75 * exp((-pow(var_chaste_interface__membrane__V + 20.0, 2.0)) * 0.0025)))) / (1.0 + (0.12 * exp((var_chaste_interface__membrane__V + 12.0) * 0.1))); // per_millisecond
        const double var_L_type_calcium_current__beta = 0.05 * exp((-(var_chaste_interface__membrane__V + 12.0)) * 0.0769230769231); // per_millisecond
        const double var_L_type_calcium_current__gamma = (0.23324 * var_chaste_interface__calcium_concentration__Cass) / (20.0 + var_chaste_interface__calcium_concentration__Cass); // per_millisecond
        const double var_L_type_calcium_current__Kpcf = 13.0 * (1.0 - exp((-pow(var_chaste_interface__membrane__V + 14.5, 2.0)) * 0.01)); // per_millisecond
        const double var_fast_sodium_current__C_Na3 = 1.0 - (var_chaste_interface__fast_sodium_current__O_Na + var_chaste_interface__fast_sodium_current__C_Na1 + var_chaste_interface__fast_sodium_current__C_Na2 + var_chaste_interface__fast_sodium_current__IF_Na + var_chaste_interface__fast_sodium_current__I1_Na + var_chaste_interface__fast_sodium_current__I2_Na + var_chaste_interface__fast_sodium_current__IC_Na2 + var_chaste_interface__fast_sodium_current__IC_Na3); // dimensionless
        const double var_fast_sodium_current__alpha_Na11 = 3.802 / ((0.1027 * exp((-(var_chaste_interface__membrane__V + 2.5)) * 0.0588235294118)) + (0.2 * exp((-(var_chaste_interface__membrane__V + 2.5)) * 0.00666666666667))); // per_millisecond
        const double var_fast_sodium_current__beta_Na11 = 0.1917 * exp((-(var_chaste_interface__membrane__V + 2.5)) * 0.0492610837438); // per_millisecond
        const double var_fast_sodium_current__alpha_Na12 = 3.802 / ((0.1027 * exp((-(var_chaste_interface__membrane__V + 2.5)) * 0.0666666666667)) + (0.23 * exp((-(var_chaste_interface__membrane__V + 2.5)) * 0.00666666666667))); // per_millisecond
        const double var_fast_sodium_current__beta_Na12 = 0.2 * exp((-(var_chaste_interface__membrane__V - 2.5)) * 0.0492610837438); // per_millisecond
        const double var_fast_sodium_current__alpha_Na13 = 3.802 / ((0.1027 * exp((-(var_chaste_interface__membrane__V + 2.5)) * 0.0833333333333)) + (0.25 * exp((-(var_chaste_interface__membrane__V + 2.5)) * 0.00666666666667))); // per_millisecond
        const double var_fast_sodium_current__beta_Na13 = 0.22 * exp((-(var_chaste_interface__membrane__V - 7.5)) * 0.0492610837438); // per_millisecond
        const double var_fast_sodium_current__alpha_Na3 = 7e-07 * exp((-(var_chaste_interface__membrane__V + 7.0)) * 0.12987012987); // per_millisecond
        const double var_fast_sodium_current__beta_Na3 = 0.0084 + (2e-05 * (var_chaste_interface__membrane__V + 7.0)); // per_millisecond
        const double var_fast_sodium_current__alpha_Na2 = 1.0 / ((0.188495 * exp((-((var_chaste_interface__membrane__V + 7.0) - NV_Ith_S(mParameters, 8))) * 0.0602409638554)) + 0.393956); // per_millisecond
        const double var_fast_sodium_current__beta_Na2 = (var_fast_sodium_current__alpha_Na13 * var_fast_sodium_current__alpha_Na2 * var_fast_sodium_current__alpha_Na3) / (var_fast_sodium_current__beta_Na13 * var_fast_sodium_current__beta_Na3); // per_millisecond
        const double var_fast_sodium_current__alpha_Na4 = var_fast_sodium_current__alpha_Na2 * 0.001; // per_millisecond
        const double var_fast_sodium_current__beta_Na4 = var_fast_sodium_current__alpha_Na3; // per_millisecond
        const double var_fast_sodium_current__alpha_Na5 = var_fast_sodium_current__alpha_Na2 * 1.05263157895e-05; // per_millisecond
        const double var_fast_sodium_current__beta_Na5 = var_fast_sodium_current__alpha_Na3 * 0.02; // per_millisecond
        const double var_slow_transient_outward_potassium_current__ass = 1.0 / (1.0 + exp((-(var_chaste_interface__membrane__V + 22.5)) * 0.12987012987)); // dimensionless
        const double var_slow_transient_outward_potassium_current__iss = 1.0 / (1.0 + exp((var_chaste_interface__membrane__V + 45.2) * 0.175438596491)); // dimensionless
        const double var_rapid_delayed_rectifier_potassium_current__alpha_a1 = 0.013733 * exp(0.038198 * var_chaste_interface__membrane__V); // per_millisecond
        const double var_rapid_delayed_rectifier_potassium_current__beta_a1 = 6.89e-05 * exp( -0.04178 * var_chaste_interface__membrane__V); // per_millisecond
        const double var_rapid_delayed_rectifier_potassium_current__alpha_i = 0.090821 * exp(0.023391 * (var_chaste_interface__membrane__V + 5.0)); // per_millisecond
        const double var_rapid_delayed_rectifier_potassium_current__beta_i = 0.006497 * exp( -0.03268 * (var_chaste_interface__membrane__V + 5.0)); // per_millisecond
        const double d_dt_chaste_interface__calcium_concentration__Cai = pow(1.0 + (11.9 / pow(0.238 + var_chaste_interface__calcium_concentration__Cai, 2.0)),  -1.0) * ((var_calcium_fluxes__J_leak + var_calcium_fluxes__J_xfer) - (var_calcium_fluxes__J_up + (((0.00237 * var_chaste_interface__calcium_concentration__Cai * (140.0 - var_chaste_interface__calcium_buffering__HTRPN_Ca)) + (0.0327 * var_chaste_interface__calcium_concentration__Cai * (70.0 - var_chaste_interface__calcium_buffering__LTRPN_Ca))) - ((3.2e-05 * var_chaste_interface__calcium_buffering__HTRPN_Ca) + (0.0196 * var_chaste_interface__calcium_buffering__LTRPN_Ca))) + ((((var_calcium_background_current__i_Cab + var_calcium_pump_current__i_pCa) - (2.0 * var_sodium_calcium_exchange_current__i_NaCa)) * 0.0001534 * var_membrane__Cm) * 200.516530583))); // 'micromole per litre per millisecond'
        const double d_dt_chaste_interface__calcium_concentration__Cass = pow(1.0 + (11.9 / pow(0.238 + var_chaste_interface__calcium_concentration__Cass, 2.0)),  -1.0) * (((var_calcium_fluxes__J_rel * 1.2e-07) * 673400673.401) - (((var_calcium_fluxes__J_xfer * 2.584e-05) * 673400673.401) + ((var_L_type_calcium_current__i_CaL * 0.0001534 * var_membrane__Cm) * 3489122.66011))); // 'micromole per litre per millisecond'
        const double d_dt_chaste_interface__calcium_concentration__CaJSR = pow(1.0 + (12000000.0 / pow(800.0 + var_chaste_interface__calcium_concentration__CaJSR, 2.0)),  -1.0) * (var_calcium_fluxes__J_tr - var_calcium_fluxes__J_rel); // 'micromole per litre per millisecond'
        const double d_dt_chaste_interface__calcium_concentration__CaNSR = (((var_calcium_fluxes__J_up - var_calcium_fluxes__J_leak) * 2.584e-05) * 476644.42326) - ((var_calcium_fluxes__J_tr * 1.2e-07) * 476644.42326); // 'micromole per litre per millisecond'
        const double d_dt_chaste_interface__calcium_fluxes__P_RyR = ( -0.04 * var_chaste_interface__calcium_fluxes__P_RyR) - (((0.1 * var_L_type_calcium_current__i_CaL) * 0.142857142857) * exp((-pow(var_chaste_interface__membrane__V - 5.0, 2.0)) * 0.00154320987654)); // per_millisecond
        const double d_dt_chaste_interface__calcium_buffering__LTRPN_Ca = (0.0327 * var_chaste_interface__calcium_concentration__Cai * (70.0 - var_chaste_interface__calcium_buffering__LTRPN_Ca)) - (0.0196 * var_chaste_interface__calcium_buffering__LTRPN_Ca); // 'micromole per litre per millisecond'
        const double d_dt_chaste_interface__calcium_buffering__HTRPN_Ca = (0.00237 * var_chaste_interface__calcium_concentration__Cai * (140.0 - var_chaste_interface__calcium_buffering__HTRPN_Ca)) - (3.2e-05 * var_chaste_interface__calcium_buffering__HTRPN_Ca); // 'micromole per litre per millisecond'
        const double d_dt_chaste_interface__ryanodine_receptors__P_O1 = ((0.006075 * pow(var_chaste_interface__calcium_concentration__Cass, 4.0) * (1.0 - (var_chaste_interface__ryanodine_receptors__P_C2 + var_chaste_interface__ryanodine_receptors__P_O1 + var_chaste_interface__ryanodine_receptors__P_O2))) + (0.965 * var_chaste_interface__ryanodine_receptors__P_O2) + (0.0008 * var_chaste_interface__ryanodine_receptors__P_C2)) - ((0.07125 * var_chaste_interface__ryanodine_receptors__P_O1) + (0.00405 * pow(var_chaste_interface__calcium_concentration__Cass, 3.0) * var_chaste_interface__ryanodine_receptors__P_O1) + (0.009 * var_chaste_interface__ryanodine_receptors__P_O1)); // per_millisecond
        const double d_dt_chaste_interface__ryanodine_receptors__P_O2 = (0.00405 * pow(var_chaste_interface__calcium_concentration__Cass, 3.0) * var_chaste_interface__ryanodine_receptors__P_O1) - (0.965 * var_chaste_interface__ryanodine_receptors__P_O2); // per_millisecond
        const double d_dt_chaste_interface__ryanodine_receptors__P_C2 = (0.009 * var_chaste_interface__ryanodine_receptors__P_O1) - (0.0008 * var_chaste_interface__ryanodine_receptors__P_C2); // per_millisecond
        const double d_dt_chaste_interface__L_type_calcium_current__O = ((var_L_type_calcium_current__alpha * var_chaste_interface__L_type_calcium_current__C4) + (0.0005 * var_chaste_interface__L_type_calcium_current__I1) + (0.001 * ((var_L_type_calcium_current__alpha * var_chaste_interface__L_type_calcium_current__I2) - (var_L_type_calcium_current__Kpcf * var_chaste_interface__L_type_calcium_current__O)))) - ((4.0 * var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__O) + (var_L_type_calcium_current__gamma * var_chaste_interface__L_type_calcium_current__O)); // per_millisecond
        const double d_dt_chaste_interface__L_type_calcium_current__C2 = ((4.0 * var_L_type_calcium_current__alpha * (1.0 - (var_chaste_interface__L_type_calcium_current__O + var_chaste_interface__L_type_calcium_current__C2 + var_chaste_interface__L_type_calcium_current__C3 + var_chaste_interface__L_type_calcium_current__C4 + var_chaste_interface__L_type_calcium_current__I1 + var_chaste_interface__L_type_calcium_current__I2 + var_chaste_interface__L_type_calcium_current__I3))) + (2.0 * var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__C3)) - ((var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__C2) + (3.0 * var_L_type_calcium_current__alpha * var_chaste_interface__L_type_calcium_current__C2)); // per_millisecond
        const double d_dt_chaste_interface__L_type_calcium_current__C3 = ((3.0 * var_L_type_calcium_current__alpha * var_chaste_interface__L_type_calcium_current__C2) + (3.0 * var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__C4)) - ((2.0 * var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__C3) + (2.0 * var_L_type_calcium_current__alpha * var_chaste_interface__L_type_calcium_current__C3)); // per_millisecond
        const double d_dt_chaste_interface__L_type_calcium_current__C4 = ((2.0 * var_L_type_calcium_current__alpha * var_chaste_interface__L_type_calcium_current__C3) + (4.0 * var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__O) + (0.01 * ((var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__I1 * 0.002) - (var_L_type_calcium_current__alpha * var_L_type_calcium_current__gamma * var_chaste_interface__L_type_calcium_current__C4))) + (0.002 * ((4.0 * var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__I2) - (var_L_type_calcium_current__Kpcf * var_chaste_interface__L_type_calcium_current__C4))) + (var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__I3 * 0.002)) - ((3.0 * var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__C4) + (var_L_type_calcium_current__alpha * var_chaste_interface__L_type_calcium_current__C4) + (1.0 * var_L_type_calcium_current__gamma * var_L_type_calcium_current__Kpcf * var_chaste_interface__L_type_calcium_current__C4)); // per_millisecond
        const double d_dt_chaste_interface__L_type_calcium_current__I1 = ((var_L_type_calcium_current__gamma * var_chaste_interface__L_type_calcium_current__O) + (0.001 * ((var_L_type_calcium_current__alpha * var_chaste_interface__L_type_calcium_current__I3) - (var_L_type_calcium_current__Kpcf * var_chaste_interface__L_type_calcium_current__I1))) + (0.01 * ((var_L_type_calcium_current__alpha * var_L_type_calcium_current__gamma * var_chaste_interface__L_type_calcium_current__C4) - (4.0 * var_L_type_calcium_current__beta * var_L_type_calcium_current__Kpcf * var_chaste_interface__L_type_calcium_current__I1)))) - (0.0005 * var_chaste_interface__L_type_calcium_current__I1); // per_millisecond
        const double d_dt_chaste_interface__L_type_calcium_current__I2 = ((0.001 * ((var_L_type_calcium_current__Kpcf * var_chaste_interface__L_type_calcium_current__O) - (var_L_type_calcium_current__alpha * var_chaste_interface__L_type_calcium_current__I2))) + (0.0005 * var_chaste_interface__L_type_calcium_current__I3) + (0.002 * ((var_L_type_calcium_current__Kpcf * var_chaste_interface__L_type_calcium_current__C4) - (4.0 * var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__I2)))) - (var_L_type_calcium_current__gamma * var_chaste_interface__L_type_calcium_current__I2); // per_millisecond
        const double d_dt_chaste_interface__L_type_calcium_current__I3 = ((0.001 * ((var_L_type_calcium_current__Kpcf * var_chaste_interface__L_type_calcium_current__I1) - (var_L_type_calcium_current__alpha * var_chaste_interface__L_type_calcium_current__I3))) + (var_L_type_calcium_current__gamma * var_chaste_interface__L_type_calcium_current__I2) + (1.0 * var_L_type_calcium_current__gamma * var_L_type_calcium_current__Kpcf * var_chaste_interface__L_type_calcium_current__C4)) - ((var_L_type_calcium_current__beta * var_chaste_interface__L_type_calcium_current__I3 * 0.002) + (0.0005 * var_chaste_interface__L_type_calcium_current__I3)); // per_millisecond
        const double d_dt_chaste_interface__sodium_concentration__Nai = ((-NV_Ith_S(mParameters, 3)) * (var_fast_sodium_current__i_Na + var_sodium_background_current__i_Nab + (3.0 * var_sodium_potassium_pump_current__i_NaK) + (3.0 * var_sodium_calcium_exchange_current__i_NaCa)) * 0.0001534 * var_membrane__Cm) * 401.033061166; // 'micromole per litre per millisecond'
        const double d_dt_chaste_interface__fast_sodium_current__O_Na = ((var_fast_sodium_current__alpha_Na13 * var_chaste_interface__fast_sodium_current__C_Na1) + (var_fast_sodium_current__beta_Na2 * var_chaste_interface__fast_sodium_current__IF_Na)) - ((var_fast_sodium_current__beta_Na13 * var_chaste_interface__fast_sodium_current__O_Na) + (var_fast_sodium_current__alpha_Na2 * var_chaste_interface__fast_sodium_current__O_Na)); // per_millisecond
        const double d_dt_chaste_interface__fast_sodium_current__C_Na1 = ((var_fast_sodium_current__alpha_Na12 * var_chaste_interface__fast_sodium_current__C_Na2) + (var_fast_sodium_current__beta_Na13 * var_chaste_interface__fast_sodium_current__O_Na) + (var_fast_sodium_current__alpha_Na3 * var_chaste_interface__fast_sodium_current__IF_Na)) - ((var_fast_sodium_current__beta_Na12 * var_chaste_interface__fast_sodium_current__C_Na1) + (var_fast_sodium_current__alpha_Na13 * var_chaste_interface__fast_sodium_current__C_Na1) + (var_fast_sodium_current__beta_Na3 * var_chaste_interface__fast_sodium_current__C_Na1)); // per_millisecond
        const double d_dt_chaste_interface__fast_sodium_current__C_Na2 = ((var_fast_sodium_current__alpha_Na11 * var_fast_sodium_current__C_Na3) + (var_fast_sodium_current__beta_Na12 * var_chaste_interface__fast_sodium_current__C_Na1) + (var_fast_sodium_current__alpha_Na3 * var_chaste_interface__fast_sodium_current__IC_Na2)) - ((var_fast_sodium_current__beta_Na11 * var_chaste_interface__fast_sodium_current__C_Na2) + (var_fast_sodium_current__alpha_Na12 * var_chaste_interface__fast_sodium_current__C_Na2) + (var_fast_sodium_current__beta_Na3 * var_chaste_interface__fast_sodium_current__C_Na2)); // per_millisecond
        const double d_dt_chaste_interface__fast_sodium_current__I1_Na = ((var_fast_sodium_current__alpha_Na4 * var_chaste_interface__fast_sodium_current__IF_Na) + (var_fast_sodium_current__beta_Na5 * var_chaste_interface__fast_sodium_current__I2_Na)) - ((var_fast_sodium_current__beta_Na4 * var_chaste_interface__fast_sodium_current__I1_Na) + (var_fast_sodium_current__alpha_Na5 * var_chaste_interface__fast_sodium_current__I1_Na)); // per_millisecond
        const double d_dt_chaste_interface__fast_sodium_current__I2_Na = (var_fast_sodium_current__alpha_Na5 * var_chaste_interface__fast_sodium_current__I1_Na) - (var_fast_sodium_current__beta_Na5 * var_chaste_interface__fast_sodium_current__I2_Na); // per_millisecond
        const double d_dt_chaste_interface__fast_sodium_current__IF_Na = ((var_fast_sodium_current__alpha_Na2 * var_chaste_interface__fast_sodium_current__O_Na) + (var_fast_sodium_current__beta_Na3 * var_chaste_interface__fast_sodium_current__C_Na1) + (var_fast_sodium_current__beta_Na4 * var_chaste_interface__fast_sodium_current__I1_Na) + (var_fast_sodium_current__alpha_Na12 * var_chaste_interface__fast_sodium_current__IC_Na2)) - ((var_fast_sodium_current__beta_Na2 * var_chaste_interface__fast_sodium_current__IF_Na) + (var_fast_sodium_current__alpha_Na3 * var_chaste_interface__fast_sodium_current__IF_Na) + (var_fast_sodium_current__alpha_Na4 * var_chaste_interface__fast_sodium_current__IF_Na) + (var_fast_sodium_current__beta_Na12 * var_chaste_interface__fast_sodium_current__IF_Na)); // per_millisecond
        const double d_dt_chaste_interface__fast_sodium_current__IC_Na2 = ((var_fast_sodium_current__alpha_Na11 * var_chaste_interface__fast_sodium_current__IC_Na3) + (var_fast_sodium_current__beta_Na12 * var_chaste_interface__fast_sodium_current__IF_Na) + (var_fast_sodium_current__beta_Na3 * var_chaste_interface__fast_sodium_current__C_Na2)) - ((var_fast_sodium_current__beta_Na11 * var_chaste_interface__fast_sodium_current__IC_Na2) + (var_fast_sodium_current__alpha_Na12 * var_chaste_interface__fast_sodium_current__IC_Na2) + (var_fast_sodium_current__alpha_Na3 * var_chaste_interface__fast_sodium_current__IC_Na2)); // per_millisecond
        const double d_dt_chaste_interface__fast_sodium_current__IC_Na3 = ((var_fast_sodium_current__beta_Na11 * var_chaste_interface__fast_sodium_current__IC_Na2) + (var_fast_sodium_current__beta_Na3 * var_fast_sodium_current__C_Na3)) - ((var_fast_sodium_current__alpha_Na11 * var_chaste_interface__fast_sodium_current__IC_Na3) + (var_fast_sodium_current__alpha_Na3 * var_chaste_interface__fast_sodium_current__IC_Na3)); // per_millisecond
        const double d_dt_chaste_interface__potassium_concentration__Ki = ((-NV_Ith_S(mParameters, 3)) * ((var_fast_transient_outward_potassium_current__i_Kto_f + var_slow_transient_outward_potassium_current__i_Kto_s + var_time_independent_potassium_current__i_K1 + var_slow_delayed_rectifier_potassium_current__i_Ks + var_non_inactivating_steady_state_potassium_current__i_Kss + var_ultra_rapidly_activating_delayed_rectifier_potassium_current__i_Kur + var_rapid_delayed_rectifier_potassium_current__i_Kr) - (2.0 * var_sodium_potassium_pump_current__i_NaK)) * 0.0001534 * var_membrane__Cm) * 401.033061166; // 'micromole per litre per millisecond'
        const double d_dt_chaste_interface__fast_transient_outward_potassium_current__ato_f = ((0.18064 * exp(0.03577 * (var_chaste_interface__membrane__V + 30.0))) * (1.0 - var_chaste_interface__fast_transient_outward_potassium_current__ato_f)) - ((0.3956 * exp( -0.06237 * (var_chaste_interface__membrane__V + 30.0))) * var_chaste_interface__fast_transient_outward_potassium_current__ato_f); // per_millisecond
        const double d_dt_chaste_interface__fast_transient_outward_potassium_current__ito_f = (((0.000152 * exp((-(var_chaste_interface__membrane__V + 13.5)) * 0.142857142857)) / ((0.0067083 * exp((-(var_chaste_interface__membrane__V + 33.5)) * 0.142857142857)) + 1.0)) * (1.0 - var_chaste_interface__fast_transient_outward_potassium_current__ito_f)) - (((0.00095 * exp((var_chaste_interface__membrane__V + 33.5) * 0.142857142857)) / ((0.051335 * exp((var_chaste_interface__membrane__V + 33.5) * 0.142857142857)) + 1.0)) * var_chaste_interface__fast_transient_outward_potassium_current__ito_f); // per_millisecond
        const double d_dt_chaste_interface__slow_transient_outward_potassium_current__ato_s = (var_slow_transient_outward_potassium_current__ass - var_chaste_interface__slow_transient_outward_potassium_current__ato_s) / ((0.493 * exp( -0.0629 * var_chaste_interface__membrane__V)) + 2.058); // per_millisecond
        const double d_dt_chaste_interface__slow_transient_outward_potassium_current__ito_s = (var_slow_transient_outward_potassium_current__iss - var_chaste_interface__slow_transient_outward_potassium_current__ito_s) / (270.0 + (1050.0 / (1.0 + exp((var_chaste_interface__membrane__V + 45.2) * 0.175438596491)))); // per_millisecond
        const double d_dt_chaste_interface__slow_delayed_rectifier_potassium_current__nKs = (((4.81333e-06 * (var_chaste_interface__membrane__V + 26.5)) / (1.0 - exp( -0.128 * (var_chaste_interface__membrane__V + 26.5)))) * (1.0 - var_chaste_interface__slow_delayed_rectifier_potassium_current__nKs)) - ((9.53333e-05 * exp( -0.038 * (var_chaste_interface__membrane__V + 26.5))) * var_chaste_interface__slow_delayed_rectifier_potassium_current__nKs); // per_millisecond
        const double d_dt_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__aur = (var_slow_transient_outward_potassium_current__ass - var_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__aur) / ((0.493 * exp( -0.0629 * var_chaste_interface__membrane__V)) + 2.058); // per_millisecond
        const double d_dt_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__iur = (var_slow_transient_outward_potassium_current__iss - var_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__iur) / (1200.0 - (170.0 / (1.0 + exp((var_chaste_interface__membrane__V + 45.2) * 0.175438596491)))); // per_millisecond
        const double d_dt_chaste_interface__non_inactivating_steady_state_potassium_current__aKss = (var_slow_transient_outward_potassium_current__ass - var_chaste_interface__non_inactivating_steady_state_potassium_current__aKss) / ((39.3 * exp( -0.0862 * var_chaste_interface__membrane__V)) + 13.17); // per_millisecond
        const double d_dt_chaste_interface__non_inactivating_steady_state_potassium_current__iKss = 0.0; // per_millisecond
        const double d_dt_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K = ((var_rapid_delayed_rectifier_potassium_current__alpha_a1 * var_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K2) + (var_rapid_delayed_rectifier_potassium_current__beta_i * var_chaste_interface__rapid_delayed_rectifier_potassium_current__I_K)) - ((var_rapid_delayed_rectifier_potassium_current__beta_a1 * var_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K) + (var_rapid_delayed_rectifier_potassium_current__alpha_i * var_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K)); // per_millisecond
        const double d_dt_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K1 = (((0.022348 * exp(0.01176 * var_chaste_interface__membrane__V)) * (1.0 - (var_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K1 + var_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K2 + var_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K + var_chaste_interface__rapid_delayed_rectifier_potassium_current__I_K))) + (0.036778 * var_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K2)) - (((0.047002 * exp( -0.0631 * var_chaste_interface__membrane__V)) * var_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K1) + (0.023761 * var_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K1)); // per_millisecond
        const double d_dt_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K2 = ((0.023761 * var_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K1) + (var_rapid_delayed_rectifier_potassium_current__beta_a1 * var_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K)) - ((0.036778 * var_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K2) + (var_rapid_delayed_rectifier_potassium_current__alpha_a1 * var_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K2)); // per_millisecond
        const double d_dt_chaste_interface__rapid_delayed_rectifier_potassium_current__I_K = (var_rapid_delayed_rectifier_potassium_current__alpha_i * var_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K) - (var_rapid_delayed_rectifier_potassium_current__beta_i * var_chaste_interface__rapid_delayed_rectifier_potassium_current__I_K); // per_millisecond
        
        if (mSetVoltageDerivativeToZero)
        {
            d_dt_chaste_interface__membrane__V = 0.0;
        }
        else
        {
            var_chaste_interface__membrane__i_stim = GetIntracellularAreaStimulus(var_chaste_interface__environment__time);
            const double var_calcium_activated_chloride_current__i_ClCa = ((10.0 * (0.2 / (1.0 + exp((-(var_chaste_interface__membrane__V - 46.7)) * 0.128205128205))) * var_chaste_interface__calcium_concentration__Cai) / (var_chaste_interface__calcium_concentration__Cai + 10.0)) * (var_chaste_interface__membrane__V -  -40.0); // picoA_per_picoF
            d_dt_chaste_interface__membrane__V = -(var_L_type_calcium_current__i_CaL + var_calcium_pump_current__i_pCa + var_sodium_calcium_exchange_current__i_NaCa + var_calcium_background_current__i_Cab + var_fast_sodium_current__i_Na + var_sodium_background_current__i_Nab + var_sodium_potassium_pump_current__i_NaK + var_fast_transient_outward_potassium_current__i_Kto_f + var_slow_transient_outward_potassium_current__i_Kto_s + var_time_independent_potassium_current__i_K1 + var_slow_delayed_rectifier_potassium_current__i_Ks + var_ultra_rapidly_activating_delayed_rectifier_potassium_current__i_Kur + var_non_inactivating_steady_state_potassium_current__i_Kss + var_rapid_delayed_rectifier_potassium_current__i_Kr + var_calcium_activated_chloride_current__i_ClCa + (var_chaste_interface__membrane__i_stim / HeartConfig::Instance()->GetCapacitance())); // 'millivolt per millisecond'
        }
        
        NV_Ith_S(rDY, 0) = d_dt_chaste_interface__membrane__V;
        NV_Ith_S(rDY, 1) = d_dt_chaste_interface__calcium_concentration__Cai;
        NV_Ith_S(rDY, 2) = d_dt_chaste_interface__calcium_concentration__Cass;
        NV_Ith_S(rDY, 3) = d_dt_chaste_interface__calcium_concentration__CaJSR;
        NV_Ith_S(rDY, 4) = d_dt_chaste_interface__calcium_concentration__CaNSR;
        NV_Ith_S(rDY, 5) = d_dt_chaste_interface__calcium_fluxes__P_RyR;
        NV_Ith_S(rDY, 6) = d_dt_chaste_interface__calcium_buffering__LTRPN_Ca;
        NV_Ith_S(rDY, 7) = d_dt_chaste_interface__calcium_buffering__HTRPN_Ca;
        NV_Ith_S(rDY, 8) = d_dt_chaste_interface__ryanodine_receptors__P_O1;
        NV_Ith_S(rDY, 9) = d_dt_chaste_interface__ryanodine_receptors__P_O2;
        NV_Ith_S(rDY, 10) = d_dt_chaste_interface__ryanodine_receptors__P_C2;
        NV_Ith_S(rDY, 11) = d_dt_chaste_interface__L_type_calcium_current__O;
        NV_Ith_S(rDY, 12) = d_dt_chaste_interface__L_type_calcium_current__C2;
        NV_Ith_S(rDY, 13) = d_dt_chaste_interface__L_type_calcium_current__C3;
        NV_Ith_S(rDY, 14) = d_dt_chaste_interface__L_type_calcium_current__C4;
        NV_Ith_S(rDY, 15) = d_dt_chaste_interface__L_type_calcium_current__I1;
        NV_Ith_S(rDY, 16) = d_dt_chaste_interface__L_type_calcium_current__I2;
        NV_Ith_S(rDY, 17) = d_dt_chaste_interface__L_type_calcium_current__I3;
        NV_Ith_S(rDY, 18) = d_dt_chaste_interface__sodium_concentration__Nai;
        NV_Ith_S(rDY, 19) = d_dt_chaste_interface__fast_sodium_current__O_Na;
        NV_Ith_S(rDY, 20) = d_dt_chaste_interface__fast_sodium_current__C_Na1;
        NV_Ith_S(rDY, 21) = d_dt_chaste_interface__fast_sodium_current__C_Na2;
        NV_Ith_S(rDY, 22) = d_dt_chaste_interface__fast_sodium_current__I1_Na;
        NV_Ith_S(rDY, 23) = d_dt_chaste_interface__fast_sodium_current__I2_Na;
        NV_Ith_S(rDY, 24) = d_dt_chaste_interface__fast_sodium_current__IF_Na;
        NV_Ith_S(rDY, 25) = d_dt_chaste_interface__fast_sodium_current__IC_Na2;
        NV_Ith_S(rDY, 26) = d_dt_chaste_interface__fast_sodium_current__IC_Na3;
        NV_Ith_S(rDY, 27) = d_dt_chaste_interface__potassium_concentration__Ki;
        NV_Ith_S(rDY, 28) = d_dt_chaste_interface__fast_transient_outward_potassium_current__ato_f;
        NV_Ith_S(rDY, 29) = d_dt_chaste_interface__fast_transient_outward_potassium_current__ito_f;
        NV_Ith_S(rDY, 30) = d_dt_chaste_interface__slow_transient_outward_potassium_current__ato_s;
        NV_Ith_S(rDY, 31) = d_dt_chaste_interface__slow_transient_outward_potassium_current__ito_s;
        NV_Ith_S(rDY, 32) = d_dt_chaste_interface__slow_delayed_rectifier_potassium_current__nKs;
        NV_Ith_S(rDY, 33) = d_dt_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__aur;
        NV_Ith_S(rDY, 34) = d_dt_chaste_interface__ultra_rapidly_activating_delayed_rectifier_potassium_current__iur;
        NV_Ith_S(rDY, 35) = d_dt_chaste_interface__non_inactivating_steady_state_potassium_current__aKss;
        NV_Ith_S(rDY, 36) = d_dt_chaste_interface__non_inactivating_steady_state_potassium_current__iKss;
        NV_Ith_S(rDY, 37) = d_dt_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K;
        NV_Ith_S(rDY, 38) = d_dt_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K1;
        NV_Ith_S(rDY, 39) = d_dt_chaste_interface__rapid_delayed_rectifier_potassium_current__C_K2;
        NV_Ith_S(rDY, 40) = d_dt_chaste_interface__rapid_delayed_rectifier_potassium_current__I_K;
    }
    
    N_Vector Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode::ComputeDerivedQuantities(double var_chaste_interface__environment__time, const N_Vector & rY)
    {
        // Inputs:
        // Time units: millisecond
        double var_chaste_interface__membrane__V = NV_Ith_S(rY, 0);
        // Units: millivolt; Initial value: -82.4202
        double var_chaste_interface__calcium_concentration__Cai = NV_Ith_S(rY, 1);
        // Units: micromolar; Initial value: 0.115001
        double var_chaste_interface__calcium_concentration__Cass = NV_Ith_S(rY, 2);
        // Units: micromolar; Initial value: 0.115001
        double var_chaste_interface__calcium_concentration__CaJSR = NV_Ith_S(rY, 3);
        // Units: micromolar; Initial value: 1299.5
        double var_chaste_interface__calcium_fluxes__P_RyR = NV_Ith_S(rY, 5);
        // Units: dimensionless; Initial value: 0
        double var_chaste_interface__ryanodine_receptors__P_O1 = NV_Ith_S(rY, 8);
        // Units: dimensionless; Initial value: 0.149102e-4
        double var_chaste_interface__ryanodine_receptors__P_O2 = NV_Ith_S(rY, 9);
        // Units: dimensionless; Initial value: 0.951726e-10
        double var_chaste_interface__L_type_calcium_current__O = NV_Ith_S(rY, 11);
        // Units: dimensionless; Initial value: 0.930308e-18
        double var_chaste_interface__sodium_concentration__Nai = NV_Ith_S(rY, 18);
        // Units: micromolar; Initial value: 14237.1
        double var_chaste_interface__fast_sodium_current__O_Na = NV_Ith_S(rY, 19);
        // Units: dimensionless; Initial value: 0.713483e-6
        double var_chaste_interface__potassium_concentration__Ki = NV_Ith_S(rY, 27);
        // Units: micromolar; Initial value: 143720
        double var_chaste_interface__fast_transient_outward_potassium_current__ato_f = NV_Ith_S(rY, 28);
        // Units: dimensionless; Initial value: 0.265563e-2
        double var_chaste_interface__fast_transient_outward_potassium_current__ito_f = NV_Ith_S(rY, 29);
        // Units: dimensionless; Initial value: 0.999977
        double var_chaste_interface__slow_delayed_rectifier_potassium_current__nKs = NV_Ith_S(rY, 32);
        // Units: dimensionless; Initial value: 0.262753e-3
        double var_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K = NV_Ith_S(rY, 37);
        // Units: dimensionless; Initial value: 0.175298e-3
        
        
        // Mathematics
        var_chaste_interface__membrane__i_stim = GetIntracellularAreaStimulus(var_chaste_interface__environment__time);
        const double var_L_type_calcium_current__i_CaL = NV_Ith_S(mParameters, 6) * var_chaste_interface__L_type_calcium_current__O * (var_chaste_interface__membrane__V - 63.0); // picoA_per_picoF
        const double var_sodium_calcium_exchange_current__i_NaCa = ((((((NV_Ith_S(mParameters, 12) * 1.0) * 2.92918243772e-16) * 1.0) / (1380.0 + NV_Ith_S(mParameters, 4))) * 1.0) / (1.0 + (0.1 * exp((var_chaste_interface__membrane__V *  -62.725) * 0.000403620964396)))) * ((exp((var_chaste_interface__membrane__V * 33.775) * 0.000403620964396) * pow(var_chaste_interface__sodium_concentration__Nai, 3.0) * NV_Ith_S(mParameters, 4)) - (exp((var_chaste_interface__membrane__V *  -62.725) * 0.000403620964396) * 2.744e+15 * var_chaste_interface__calcium_concentration__Cai)); // picoA_per_picoF
        const double var_fast_sodium_current__E_Na = 25.6743212435 * log((126000.0 + (0.1 * NV_Ith_S(mParameters, 5))) / ((0.9 * var_chaste_interface__sodium_concentration__Nai) + (0.1 * var_chaste_interface__potassium_concentration__Ki))); // millivolt
        const double var_fast_sodium_current__i_Na = NV_Ith_S(mParameters, 7) * var_chaste_interface__fast_sodium_current__O_Na * (var_chaste_interface__membrane__V - var_fast_sodium_current__E_Na); // picoA_per_picoF
        const double var_fast_transient_outward_potassium_current__E_K = 25.6743212435 * log(NV_Ith_S(mParameters, 5) / var_chaste_interface__potassium_concentration__Ki); // millivolt
        const double var_fast_transient_outward_potassium_current__i_Kto_f = NV_Ith_S(mParameters, 13) * pow(var_chaste_interface__fast_transient_outward_potassium_current__ato_f, 3.0) * var_chaste_interface__fast_transient_outward_potassium_current__ito_f * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_time_independent_potassium_current__i_K1 = (((NV_Ith_S(mParameters, 9) * NV_Ith_S(mParameters, 5)) / (NV_Ith_S(mParameters, 5) + 210.0)) * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K)) / (1.0 + exp(0.0896 * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K))); // picoA_per_picoF
        const double var_slow_delayed_rectifier_potassium_current__i_Ks = NV_Ith_S(mParameters, 11) * pow(var_chaste_interface__slow_delayed_rectifier_potassium_current__nKs, 2.0) * (var_chaste_interface__membrane__V - var_fast_transient_outward_potassium_current__E_K); // picoA_per_picoF
        const double var_rapid_delayed_rectifier_potassium_current__i_Kr = NV_Ith_S(mParameters, 10) * var_chaste_interface__rapid_delayed_rectifier_potassium_current__O_K * (var_chaste_interface__membrane__V - (25.6743212435 * log(((0.98 * NV_Ith_S(mParameters, 5)) + 2800.0) / ((0.98 * var_chaste_interface__potassium_concentration__Ki) + (0.02 * var_chaste_interface__sodium_concentration__Nai))))); // picoA_per_picoF
        const double var_calcium_fluxes__J_rel = NV_Ith_S(mParameters, 1) * (var_chaste_interface__ryanodine_receptors__P_O1 + var_chaste_interface__ryanodine_receptors__P_O2) * (var_chaste_interface__calcium_concentration__CaJSR - var_chaste_interface__calcium_concentration__Cass) * var_chaste_interface__calcium_fluxes__P_RyR; // micromolar_per_millisecond
        const double var_chaste_interface__slow_delayed_rectifier_potassium_current__i_Ks = var_slow_delayed_rectifier_potassium_current__i_Ks; // picoA_per_picoF
        const double var_chaste_interface__fast_sodium_current__i_Na = var_fast_sodium_current__i_Na; // picoA_per_picoF
        const double var_chaste_interface__L_type_calcium_current__i_CaL = var_L_type_calcium_current__i_CaL; // picoA_per_picoF
        const double var_chaste_interface__time_independent_potassium_current__i_K1 = var_time_independent_potassium_current__i_K1; // picoA_per_picoF
        const double var_chaste_interface__rapid_delayed_rectifier_potassium_current__i_Kr = var_rapid_delayed_rectifier_potassium_current__i_Kr; // picoA_per_picoF
        const double var_chaste_interface__fast_transient_outward_potassium_current__i_Kto_f = var_fast_transient_outward_potassium_current__i_Kto_f; // picoA_per_picoF
        const double var_chaste_interface__sodium_calcium_exchange_current__i_NaCa = var_sodium_calcium_exchange_current__i_NaCa; // picoA_per_picoF
        
        N_Vector dqs = N_VNew_Serial(10);
        NV_Ith_S(dqs, 0) = var_calcium_fluxes__J_rel;
        NV_Ith_S(dqs, 1) = var_chaste_interface__L_type_calcium_current__i_CaL;
        NV_Ith_S(dqs, 2) = var_chaste_interface__fast_sodium_current__i_Na;
        NV_Ith_S(dqs, 3) = var_chaste_interface__time_independent_potassium_current__i_K1;
        NV_Ith_S(dqs, 4) = var_chaste_interface__rapid_delayed_rectifier_potassium_current__i_Kr;
        NV_Ith_S(dqs, 5) = var_chaste_interface__slow_delayed_rectifier_potassium_current__i_Ks;
        NV_Ith_S(dqs, 6) = var_chaste_interface__sodium_calcium_exchange_current__i_NaCa;
        NV_Ith_S(dqs, 7) = var_chaste_interface__membrane__i_stim;
        NV_Ith_S(dqs, 8) = var_chaste_interface__fast_transient_outward_potassium_current__i_Kto_f;
        NV_Ith_S(dqs, 9) = var_chaste_interface__environment__time;
        return dqs;
    }
    
template<>
void OdeSystemInformation<Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode>::Initialise(void)
{
    // Time units: millisecond
    // 
    this->mSystemName = "bondarenko_2004_apical";
    
    this->mVariableNames.push_back("membrane_voltage");
    this->mVariableUnits.push_back("millivolt");
    this->mInitialConditions.push_back(-82.4202);

    this->mVariableNames.push_back("cytosolic_calcium_concentration");
    this->mVariableUnits.push_back("micromolar");
    this->mInitialConditions.push_back(0.115001);

    this->mVariableNames.push_back("diadicspace_calcium_concentration");
    this->mVariableUnits.push_back("micromolar");
    this->mInitialConditions.push_back(0.115001);

    this->mVariableNames.push_back("JSR_calcium_concentration");
    this->mVariableUnits.push_back("micromolar");
    this->mInitialConditions.push_back(1299.5);

    this->mVariableNames.push_back("calcium_concentration__CaNSR");
    this->mVariableUnits.push_back("micromolar");
    this->mInitialConditions.push_back(1299.5);

    this->mVariableNames.push_back("calcium_fluxes__P_RyR");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0);

    this->mVariableNames.push_back("calcium_buffering__LTRPN_Ca");
    this->mVariableUnits.push_back("micromolar");
    this->mInitialConditions.push_back(11.2684);

    this->mVariableNames.push_back("calcium_buffering__HTRPN_Ca");
    this->mVariableUnits.push_back("micromolar");
    this->mInitialConditions.push_back(125.29);

    this->mVariableNames.push_back("ryanodine_receptors__P_O1");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.149102e-4);

    this->mVariableNames.push_back("ryanodine_receptors__P_O2");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.951726e-10);

    this->mVariableNames.push_back("ryanodine_receptors__P_C2");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.16774e-3);

    this->mVariableNames.push_back("L_type_calcium_current__O");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.930308e-18);

    this->mVariableNames.push_back("L_type_calcium_current__C2");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.124216e-3);

    this->mVariableNames.push_back("L_type_calcium_current__C3");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.578679e-8);

    this->mVariableNames.push_back("L_type_calcium_current__C4");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.119816e-12);

    this->mVariableNames.push_back("L_type_calcium_current__I1");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.497923e-18);

    this->mVariableNames.push_back("L_type_calcium_current__I2");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.345847e-13);

    this->mVariableNames.push_back("L_type_calcium_current__I3");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.185106e-13);

    this->mVariableNames.push_back("cytosolic_sodium_concentration");
    this->mVariableUnits.push_back("micromolar");
    this->mInitialConditions.push_back(14237.1);

    this->mVariableNames.push_back("fast_sodium_current__O_Na");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.713483e-6);

    this->mVariableNames.push_back("fast_sodium_current__C_Na1");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.279132e-3);

    this->mVariableNames.push_back("fast_sodium_current__C_Na2");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.020752);

    this->mVariableNames.push_back("fast_sodium_current__I1_Na");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.673345e-6);

    this->mVariableNames.push_back("fast_sodium_current__I2_Na");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.155787e-8);

    this->mVariableNames.push_back("fast_sodium_current__IF_Na");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.153176e-3);

    this->mVariableNames.push_back("fast_sodium_current__IC_Na2");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0113879);

    this->mVariableNames.push_back("fast_sodium_current__IC_Na3");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.34278);

    this->mVariableNames.push_back("cytosolic_potassium_concentration");
    this->mVariableUnits.push_back("micromolar");
    this->mInitialConditions.push_back(143720);

    this->mVariableNames.push_back("fast_transient_outward_potassium_current__ato_f");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.265563e-2);

    this->mVariableNames.push_back("fast_transient_outward_potassium_current__ito_f");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.999977);

    this->mVariableNames.push_back("slow_transient_outward_potassium_current__ato_s");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.417069e-3);

    this->mVariableNames.push_back("slow_transient_outward_potassium_current__ito_s");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.998543);

    this->mVariableNames.push_back("slow_delayed_rectifier_potassium_current__nKs");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.262753e-3);

    this->mVariableNames.push_back("ultra_rapidly_activating_delayed_rectifier_potassium_current__aur");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.417069e-3);

    this->mVariableNames.push_back("ultra_rapidly_activating_delayed_rectifier_potassium_current__iur");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.998543);

    this->mVariableNames.push_back("non_inactivating_steady_state_potassium_current__aKss");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.417069e-3);

    this->mVariableNames.push_back("non_inactivating_steady_state_potassium_current__iKss");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(1);

    this->mVariableNames.push_back("rapid_delayed_rectifier_potassium_current__O_K");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.175298e-3);

    this->mVariableNames.push_back("rapid_delayed_rectifier_potassium_current__C_K1");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.992513e-3);

    this->mVariableNames.push_back("rapid_delayed_rectifier_potassium_current__C_K2");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.641229e-3);

    this->mVariableNames.push_back("rapid_delayed_rectifier_potassium_current__I_K");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.319129e-4);

    this->mParameterNames.push_back("SR_leak_current_max");
    this->mParameterUnits.push_back("per_millisecond");
    
    this->mParameterNames.push_back("SR_release_current_max");
    this->mParameterUnits.push_back("per_millisecond");
    
    this->mParameterNames.push_back("SR_uptake_current_max");
    this->mParameterUnits.push_back("micromolar_per_millisecond");
    
    this->mParameterNames.push_back("concentration_clamp_onoff");
    this->mParameterUnits.push_back("dimensionless");
    
    this->mParameterNames.push_back("extracellular_calcium_concentration");
    this->mParameterUnits.push_back("micromolar");
    
    this->mParameterNames.push_back("extracellular_potassium_concentration");
    this->mParameterUnits.push_back("micromolar");
    
    this->mParameterNames.push_back("membrane_L_type_calcium_current_conductance");
    this->mParameterUnits.push_back("milliS_per_microF");
    
    this->mParameterNames.push_back("membrane_fast_sodium_current_conductance");
    this->mParameterUnits.push_back("milliS_per_microF");
    
    this->mParameterNames.push_back("membrane_fast_sodium_current_shift_inactivation");
    this->mParameterUnits.push_back("millivolt");
    
    this->mParameterNames.push_back("membrane_inward_rectifier_potassium_current_conductance");
    this->mParameterUnits.push_back("milliS_per_microF");
    
    this->mParameterNames.push_back("membrane_rapid_delayed_rectifier_potassium_current_conductance");
    this->mParameterUnits.push_back("milliS_per_microF");
    
    this->mParameterNames.push_back("membrane_slow_delayed_rectifier_potassium_current_conductance");
    this->mParameterUnits.push_back("milliS_per_microF");
    
    this->mParameterNames.push_back("membrane_sodium_calcium_exchanger_current_conductance");
    this->mParameterUnits.push_back("picoA_per_picoF");
    
    this->mParameterNames.push_back("membrane_transient_outward_current_conductance");
    this->mParameterUnits.push_back("milliS_per_microF");
    
    this->mDerivedQuantityNames.push_back("SR_release_current");
    this->mDerivedQuantityUnits.push_back("micromolar_per_millisecond");
    
    this->mDerivedQuantityNames.push_back("membrane_L_type_calcium_current");
    this->mDerivedQuantityUnits.push_back("picoA_per_picoF");
    
    this->mDerivedQuantityNames.push_back("membrane_fast_sodium_current");
    this->mDerivedQuantityUnits.push_back("picoA_per_picoF");
    
    this->mDerivedQuantityNames.push_back("membrane_inward_rectifier_potassium_current");
    this->mDerivedQuantityUnits.push_back("picoA_per_picoF");
    
    this->mDerivedQuantityNames.push_back("membrane_rapid_delayed_rectifier_potassium_current");
    this->mDerivedQuantityUnits.push_back("picoA_per_picoF");
    
    this->mDerivedQuantityNames.push_back("membrane_slow_delayed_rectifier_potassium_current");
    this->mDerivedQuantityUnits.push_back("picoA_per_picoF");
    
    this->mDerivedQuantityNames.push_back("membrane_sodium_calcium_exchanger_current");
    this->mDerivedQuantityUnits.push_back("picoA_per_picoF");
    
    this->mDerivedQuantityNames.push_back("membrane_stimulus_current");
    this->mDerivedQuantityUnits.push_back("uA_per_cm2");
    
    this->mDerivedQuantityNames.push_back("membrane_transient_outward_current");
    this->mDerivedQuantityUnits.push_back("picoA_per_picoF");
    
    this->mDerivedQuantityNames.push_back("time");
    this->mDerivedQuantityUnits.push_back("millisecond");
    
    this->mInitialised = true;
}


extern "C"
{
    AbstractCardiacCellInterface* MakeCardiacCell(
            boost::shared_ptr<AbstractIvpOdeSolver> pSolver,
            boost::shared_ptr<AbstractStimulusFunction> pStimulus)
    {
        return new Dynamicbondarenko_szigeti_bett_kim_rasmusson_2004_apicalFromCellMLCvode(pSolver, pStimulus);
    }
    
}

#endif // CHASTE_CVODE
