# Gnuplot script file generated by Chaste.
# Second plot is of the resulting restitution curve.
set terminal postscript eps enhanced size 3, 2 font 16
set output "/export/wolf1768/testoutput/CellModelTests/corrias_purkinje_2011/ICaL/corrias_purkinje_2011_ICaL_IV_curve.eps"
set title "Corrias Purkinje 2011"
set xlabel "Test Voltage (mV)"
set ylabel "Maximum Current ({/Symbol m}A/cm^{2})" 0.75,0.0
set grid
set autoscale
set xrange [-60:80]
set key off
plot "/export/wolf1768/testoutput/CellModelTests/corrias_purkinje_2011/ICaL/outputs_ICaL_IV_curve.dat" using 1:4 with linespoints pointtype 7 title "[Cao] = 1",\
"/export/wolf1768/testoutput/CellModelTests/corrias_purkinje_2011/ICaL/outputs_ICaL_IV_curve.dat" using 2:5 with linespoints pointtype 7 title "[Cao] = 2",\
"/export/wolf1768/testoutput/CellModelTests/corrias_purkinje_2011/ICaL/outputs_ICaL_IV_curve.dat" using 3:6 with linespoints pointtype 7 title "[Cao] = 3"

