# Gnuplot script file generated by Chaste.
# Second plot is of the resulting restitution curve.
set terminal postscript eps size 3, 2 font 16
set output "/export/wolf1768/testoutput/CellModelTests/aslanidi_Purkinje_model_2009/S1S2/aslanidi_Purkinje_model_2009_s1s2_curve.eps"
set title "Aslanidi Purkinje Model 2009"
set xlabel "Diastolic Interval (ms)"
set xtics 400
set ylabel "APD90 (ms)"
set grid
set autoscale
set key off
plot "/export/wolf1768/testoutput/CellModelTests/aslanidi_Purkinje_model_2009/S1S2/s1s2_curve.dat" using 1:2 with linespoints pointtype 7
