#ifdef CHASTE_CVODE
#ifndef DYNAMICASLANIDI_PURKINJE_MODEL_2009FROMCELLMLCVODE_HPP_
#define DYNAMICASLANIDI_PURKINJE_MODEL_2009FROMCELLMLCVODE_HPP_

//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: aslanidi_2009
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translators: 12282, pycml: 12383, optimize: 12047)
//! on Tue Apr 12 18:20:17 2011
//! 
//! <autogenerated>

#include "AbstractCvodeCell.hpp"
#include "AbstractDynamicallyLoadableEntity.hpp"
#include "AbstractSystemWithOutputs.hpp"
#include "AbstractStimulusFunction.hpp"

class Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode : public AbstractCvodeCell, public AbstractDynamicallyLoadableEntity, public AbstractSystemWithOutputs<N_Vector >
{
    // 
    // Settable parameters and readable variables
    // 
    double var_chaste_interface__Ca_JSR__Ca_JSR;
    double var_q_rel__q_rel;
    double var_chaste_interface__Ca_i__Ca_i;
    double var_chaste_interface__intracellular_ion_concentrations__K_i;
    double var_chaste_interface__intracellular_ion_concentrations__Na_i;
    double var_chaste_interface__Ca_r__Ca_r;
    double var_chaste_interface__i_ionic;
    double var_i_Ca_L__i_Ca_L;
    double var_chaste_interface__i_Ca_L_d_gate__d;
    double var_chaste_interface__i_Ca_L_f2_gate__f2;
    double var_i_Ca_L_f2_gate__tau_f2;
    double var_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2;
    double var_i_Ca_L_f_Ca2_gate__tau_f_Ca2;
    double var_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca;
    double var_i_Ca_L_f_Ca_gate__tau_f_Ca;
    double var_chaste_interface__i_Ca_L_f_gate__f;
    double var_i_Ca_L_f_gate__tau_f;
    double var_i_Na__i_Na;
    double var_chaste_interface__i_Na_h_gate__h;
    double var_i_Na_h_gate__tau_h;
    double var_chaste_interface__i_Na_j_gate__j;
    double var_i_Na_j_gate__tau_j;
    double var_chaste_interface__i_Na_m_gate__m;
    double var_i_K1__i_K1;
    double var_i_K1__g_K1;
    double var_i_Kr__i_Kr;
    double var_i_Ks__i_Ks;
    double var_i_Ks__g_Ks;
    double var_i_NaCa__i_NaCa;
    double var_chaste_interface__membrane__i_stim;
    double var_chaste_interface__membrane__stim_amplitude;
    double var_chaste_interface__membrane__stim_duration;
    double var_chaste_interface__membrane__stim_start;
    double var_chaste_interface__membrane__stim_period;
    double var_i_to_1__i_to_1;
    double var_chaste_interface__membrane__V;
    double var_chaste_interface__environment__time;
    
public:
    double Get_chaste_interface__Ca_JSR__Ca_JSR();
    double Get_q_rel__q_rel();
    double Get_chaste_interface__Ca_i__Ca_i();
    double Get_chaste_interface__intracellular_ion_concentrations__K_i();
    double Get_chaste_interface__intracellular_ion_concentrations__Na_i();
    double Get_chaste_interface__Ca_r__Ca_r();
    double Get_chaste_interface__i_ionic();
    double Get_i_Ca_L__i_Ca_L();
    double Get_chaste_interface__i_Ca_L_d_gate__d();
    double Get_chaste_interface__i_Ca_L_f2_gate__f2();
    double Get_i_Ca_L_f2_gate__tau_f2();
    double Get_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2();
    double Get_i_Ca_L_f_Ca2_gate__tau_f_Ca2();
    double Get_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca();
    double Get_i_Ca_L_f_Ca_gate__tau_f_Ca();
    double Get_chaste_interface__i_Ca_L_f_gate__f();
    double Get_i_Ca_L_f_gate__tau_f();
    double Get_i_Na__i_Na();
    double Get_chaste_interface__i_Na_h_gate__h();
    double Get_i_Na_h_gate__tau_h();
    double Get_chaste_interface__i_Na_j_gate__j();
    double Get_i_Na_j_gate__tau_j();
    double Get_chaste_interface__i_Na_m_gate__m();
    double Get_i_K1__i_K1();
    double Get_i_K1__g_K1();
    double Get_i_Kr__i_Kr();
    double Get_i_Ks__i_Ks();
    double Get_i_Ks__g_Ks();
    double Get_i_NaCa__i_NaCa();
    double Get_chaste_interface__membrane__i_stim();
    double Get_chaste_interface__membrane__stim_amplitude();
    double Get_chaste_interface__membrane__stim_duration();
    double Get_chaste_interface__membrane__stim_start();
    double Get_chaste_interface__membrane__stim_period();
    double Get_i_to_1__i_to_1();
    double Get_chaste_interface__membrane__V();
    double Get_chaste_interface__environment__time();
    double Get_SR_leak_current_max_constant();
    double Get_SR_release_current_max_constant();
    double Get_SR_uptake_current_max_constant();
    double Get_concentration_clamp_onoff_constant();
    double Get_extracellular_calcium_concentration_constant();
    double Get_extracellular_potassium_concentration_constant();
    double Get_membrane_L_type_calcium_current_conductance_constant();
    double Get_membrane_fast_sodium_current_conductance_constant();
    double Get_membrane_fast_sodium_current_reduced_inactivation_constant();
    double Get_membrane_fast_sodium_current_shift_inactivation_constant();
    double Get_membrane_inward_rectifier_potassium_current_conductance_constant();
    double Get_membrane_rapid_delayed_rectifier_potassium_current_conductance_constant();
    double Get_membrane_sodium_calcium_exchanger_current_conductance_constant();
    double Get_membrane_stimulus_current_amplitude_constant();
    double Get_membrane_stimulus_current_duration_constant();
    double Get_membrane_stimulus_current_offset_constant();
    double Get_membrane_stimulus_current_period_constant();
    double Get_membrane_transient_outward_current_conductance_constant();
    void UseCellMLDefaultStimulus();
    double GetIntracellularCalciumConcentration();
    Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode(boost::shared_ptr<AbstractIvpOdeSolver> pOdeSolver /* unused; should be empty */, boost::shared_ptr<AbstractStimulusFunction> pIntracellularStimulus);
    ~Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode();
    void VerifyStateVariables();
    double GetIIonic(const std::vector<double>* pStateVariables=NULL);
    void EvaluateRhs(double var_chaste_interface__environment__time, const N_Vector rY, N_Vector rDY);
    N_Vector ComputeDerivedQuantities(double var_chaste_interface__environment__time, const N_Vector & rY);
};


#endif // DYNAMICASLANIDI_PURKINJE_MODEL_2009FROMCELLMLCVODE_HPP_
#endif // CHASTE_CVODE
