#ifdef CHASTE_CVODE
//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: aslanidi_2009
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translators: 12282, pycml: 12383, optimize: 12047)
//! on Tue Apr 12 18:20:17 2011
//! 
//! <autogenerated>

#include "aslanidi_Purkinje_model_2009.hpp"
#include <cmath>
#include <cassert>
#include <memory>
#include "Exception.hpp"
#include "OdeSystemInformation.hpp"
#include "RegularStimulus.hpp"
#include "HeartConfig.hpp"
#include "IsNan.hpp"

    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__Ca_JSR__Ca_JSR()
    {
        return var_chaste_interface__Ca_JSR__Ca_JSR;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_q_rel__q_rel()
    {
        return var_q_rel__q_rel;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__Ca_i__Ca_i()
    {
        return var_chaste_interface__Ca_i__Ca_i;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__intracellular_ion_concentrations__K_i()
    {
        return var_chaste_interface__intracellular_ion_concentrations__K_i;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__intracellular_ion_concentrations__Na_i()
    {
        return var_chaste_interface__intracellular_ion_concentrations__Na_i;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__Ca_r__Ca_r()
    {
        return var_chaste_interface__Ca_r__Ca_r;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__i_ionic()
    {
        return var_chaste_interface__i_ionic;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_Ca_L__i_Ca_L()
    {
        return var_i_Ca_L__i_Ca_L;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__i_Ca_L_d_gate__d()
    {
        return var_chaste_interface__i_Ca_L_d_gate__d;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__i_Ca_L_f2_gate__f2()
    {
        return var_chaste_interface__i_Ca_L_f2_gate__f2;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_Ca_L_f2_gate__tau_f2()
    {
        return var_i_Ca_L_f2_gate__tau_f2;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2()
    {
        return var_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_Ca_L_f_Ca2_gate__tau_f_Ca2()
    {
        return var_i_Ca_L_f_Ca2_gate__tau_f_Ca2;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca()
    {
        return var_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_Ca_L_f_Ca_gate__tau_f_Ca()
    {
        return var_i_Ca_L_f_Ca_gate__tau_f_Ca;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__i_Ca_L_f_gate__f()
    {
        return var_chaste_interface__i_Ca_L_f_gate__f;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_Ca_L_f_gate__tau_f()
    {
        return var_i_Ca_L_f_gate__tau_f;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_Na__i_Na()
    {
        return var_i_Na__i_Na;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__i_Na_h_gate__h()
    {
        return var_chaste_interface__i_Na_h_gate__h;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_Na_h_gate__tau_h()
    {
        return var_i_Na_h_gate__tau_h;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__i_Na_j_gate__j()
    {
        return var_chaste_interface__i_Na_j_gate__j;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_Na_j_gate__tau_j()
    {
        return var_i_Na_j_gate__tau_j;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__i_Na_m_gate__m()
    {
        return var_chaste_interface__i_Na_m_gate__m;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_K1__i_K1()
    {
        return var_i_K1__i_K1;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_K1__g_K1()
    {
        return var_i_K1__g_K1;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_Kr__i_Kr()
    {
        return var_i_Kr__i_Kr;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_Ks__i_Ks()
    {
        return var_i_Ks__i_Ks;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_Ks__g_Ks()
    {
        return var_i_Ks__g_Ks;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_NaCa__i_NaCa()
    {
        return var_i_NaCa__i_NaCa;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__membrane__i_stim()
    {
        return var_chaste_interface__membrane__i_stim;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__membrane__stim_amplitude()
    {
        return var_chaste_interface__membrane__stim_amplitude;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__membrane__stim_duration()
    {
        return var_chaste_interface__membrane__stim_duration;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__membrane__stim_start()
    {
        return var_chaste_interface__membrane__stim_start;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__membrane__stim_period()
    {
        return var_chaste_interface__membrane__stim_period;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_i_to_1__i_to_1()
    {
        return var_i_to_1__i_to_1;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__membrane__V()
    {
        return var_chaste_interface__membrane__V;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_chaste_interface__environment__time()
    {
        return var_chaste_interface__environment__time;
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_SR_leak_current_max_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 0);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_SR_release_current_max_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 1);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_SR_uptake_current_max_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 2);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_concentration_clamp_onoff_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 3);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_extracellular_calcium_concentration_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 4);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_extracellular_potassium_concentration_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 5);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_L_type_calcium_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 6);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_fast_sodium_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 7);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_fast_sodium_current_reduced_inactivation_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 8);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_fast_sodium_current_shift_inactivation_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 9);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_inward_rectifier_potassium_current_conductance_constant()
    {
        // Constant value given in CellML
        const double var_i_K1__g_K1 = 0.25 * sqrt(NV_Ith_S(mParameters, 5) * 0.185185185185); // milliS_per_microF
        return var_i_K1__g_K1;
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_rapid_delayed_rectifier_potassium_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 10);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_sodium_calcium_exchanger_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 11);
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_stimulus_current_amplitude_constant()
    {
        // Constant value given in CellML
        var_chaste_interface__membrane__stim_amplitude =  -80.0 * HeartConfig::Instance()->GetCapacitance(); // uA_per_cm2
        return var_chaste_interface__membrane__stim_amplitude;
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_stimulus_current_duration_constant()
    {
        // Constant value given in CellML
        var_chaste_interface__membrane__stim_duration = 1.0; // millisecond
        return var_chaste_interface__membrane__stim_duration;
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_stimulus_current_offset_constant()
    {
        // Constant value given in CellML
        var_chaste_interface__membrane__stim_start = 100.0; // millisecond
        return var_chaste_interface__membrane__stim_start;
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_stimulus_current_period_constant()
    {
        // Constant value given in CellML
        var_chaste_interface__membrane__stim_period = 800.0; // millisecond
        return var_chaste_interface__membrane__stim_period;
    }
    
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Get_membrane_transient_outward_current_conductance_constant()
    {
        // Constant value given in CellML
        return NV_Ith_S(mParameters, 12);
    }
    
    
    void Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::UseCellMLDefaultStimulus()
    {
        // Use the default stimulus specified by CellML metadata
        var_chaste_interface__membrane__stim_start = 100.0; // millisecond
        var_chaste_interface__membrane__stim_period = 800.0; // millisecond
        var_chaste_interface__membrane__stim_duration = 1.0; // millisecond
        var_chaste_interface__membrane__stim_amplitude =  -80.0 * HeartConfig::Instance()->GetCapacitance(); // uA_per_cm2
        mpIntracellularStimulus.reset(new RegularStimulus(
                -fabs(var_chaste_interface__membrane__stim_amplitude),
                var_chaste_interface__membrane__stim_duration,
                var_chaste_interface__membrane__stim_period,
                var_chaste_interface__membrane__stim_start));
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::GetIntracellularCalciumConcentration()
    {
        return NV_Ith_S(mStateVariables, 23);
    }
    
    Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode(boost::shared_ptr<AbstractIvpOdeSolver> pOdeSolver /* unused; should be empty */, boost::shared_ptr<AbstractStimulusFunction> pIntracellularStimulus)
        : AbstractCvodeCell(
                pOdeSolver,
                30,
                0,
                pIntracellularStimulus)
    {
        // Time units: millisecond
        // 
        this->mpSystemInfo = OdeSystemInformation<Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode>::Instance();
        Init();

        // We have a default stimulus specified in the CellML file metadata
        this->mHasDefaultStimulusFromCellML = true;
        NV_Ith_S(this->mParameters, 0) = 0.004375; // (c,q_leak__q_leak_max) [millimolar_per_millisecond]
        NV_Ith_S(this->mParameters, 1) = 3000; // (c,q_rel__g_rel_max) [per_millisecond]
        NV_Ith_S(this->mParameters, 2) = 0.004375; // (c,q_up__q_up_max) [millimolar_per_millisecond]
        NV_Ith_S(this->mParameters, 3) = 1; // (c,intracellular_ion_concentrations__conc_clamp) [dimensionless]
        NV_Ith_S(this->mParameters, 4) = 1.8; // (c,model_parameters__Ca_o) [millimolar]
        NV_Ith_S(this->mParameters, 5) = 5.4; // (c,model_parameters__K_o) [millimolar]
        NV_Ith_S(this->mParameters, 6) = 0.3392328; // (c,i_Ca_L__g_Ca_L) [dimensionless]
        NV_Ith_S(this->mParameters, 7) = 8; // (c,i_Na__g_Na) [milliS_per_microF]
        NV_Ith_S(this->mParameters, 8) = 0; // (c,i_Na__perc_reduced_inact_for_IpNa) [dimensionless]
        NV_Ith_S(this->mParameters, 9) = 0; // (c,i_Na__shift_INa_inact) [millivolt]
        NV_Ith_S(this->mParameters, 10) = 0.040008488; // (c,i_Kr__g_Kr_max) [milliS_per_microF]
        NV_Ith_S(this->mParameters, 11) = 4.5; // (c,i_NaCa__i_NaCa_max) [microA_per_microF]
        NV_Ith_S(this->mParameters, 12) = 0.14135944; // (c,i_to_1__g_to_1) [milliS_per_microF]
        // Protocol outputs
        this->mOutputsInfo.resize(2);
        this->mOutputsInfo[0] = std::make_pair(0, STATE);
        this->mOutputsInfo[1] = std::make_pair(UNSIGNED_UNSET, FREE);
        
    }
    
    Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::~Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode()
    {
    }
    
    void Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::VerifyStateVariables()
    {
        
    }
    
    double Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::GetIIonic(const std::vector<double>* pStateVariables)
    {
        N_Vector rY = rGetStateVariables();
        double var_chaste_interface__membrane__V = NV_Ith_S(rY, 0);
        // Units: millivolt; Initial value: -83.43812846286808
        double var_chaste_interface__i_Na_m_gate__m = NV_Ith_S(rY, 1);
        // Units: dimensionless; Initial value: 0.002003390432234504
        double var_chaste_interface__i_Na_h_gate__h = NV_Ith_S(rY, 2);
        // Units: dimensionless; Initial value: 0.9786390933308567
        double var_chaste_interface__i_Na_j_gate__j = NV_Ith_S(rY, 3);
        // Units: dimensionless; Initial value: 0.09866447258167589
        double var_chaste_interface__i_Na_L_m_L_gate__m_L = NV_Ith_S(rY, 4);
        // Units: dimensionless; Initial value: 0.002003390432234504
        double var_chaste_interface__i_Na_L_h_L_gate__h_L = NV_Ith_S(rY, 5);
        // Units: dimensionless; Initial value: 0.8946968372659203
        double var_chaste_interface__i_Ca_L_d_gate__d = NV_Ith_S(rY, 6);
        // Units: dimensionless; Initial value: 0.000002322223865147363
        double var_chaste_interface__i_Ca_L_f_gate__f = NV_Ith_S(rY, 7);
        // Units: dimensionless; Initial value: 0.9985607329462358
        double var_chaste_interface__i_Ca_L_f2_gate__f2 = NV_Ith_S(rY, 8);
        // Units: dimensionless; Initial value: 0.8173435436674658
        double var_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca = NV_Ith_S(rY, 9);
        // Units: dimensionless; Initial value: 0.9610551285529658
        double var_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2 = NV_Ith_S(rY, 10);
        // Units: dimensionless; Initial value: 0.868690796671854
        double var_chaste_interface__i_Ca_T_b_gate__b = NV_Ith_S(rY, 11);
        // Units: dimensionless; Initial value: 0.0002563937630984438
        double var_chaste_interface__i_Ca_T_g_gate__g = NV_Ith_S(rY, 12);
        // Units: dimensionless; Initial value: 0.9720432601848331
        double var_chaste_interface__i_to_1_a_gate__a = NV_Ith_S(rY, 13);
        // Units: dimensionless; Initial value: 0.0004238729429342389
        double var_chaste_interface__i_to_1_i_gate__i = NV_Ith_S(rY, 14);
        // Units: dimensionless; Initial value: 0.9990935802459496
        double var_chaste_interface__i_to_1_i2_gate__i2 = NV_Ith_S(rY, 15);
        // Units: dimensionless; Initial value: 0.9777368439681764
        double var_chaste_interface__i_Kr_xr_gate__xr = NV_Ith_S(rY, 16);
        // Units: dimensionless; Initial value: 0.07084939408222911
        double var_chaste_interface__i_Ks_xs1_gate__xs1 = NV_Ith_S(rY, 17);
        // Units: dimensionless; Initial value: 0.0011737654433043125
        double var_chaste_interface__i_Ks_xs2_gate__xs2 = NV_Ith_S(rY, 18);
        // Units: dimensionless; Initial value: 0.001179442867470093
        double var_chaste_interface__i_to_2_a_gate__a = NV_Ith_S(rY, 19);
        // Units: dimensionless; Initial value: 0.0014909437525000811
        double var_chaste_interface__intracellular_ion_concentrations__Na_i = NV_Ith_S(rY, 20);
        // Units: millimolar; Initial value: 9.927155552932733
        double var_chaste_interface__intracellular_ion_concentrations__Cl_i = NV_Ith_S(rY, 21);
        // Units: millimolar; Initial value: 18.904682470140408
        double var_chaste_interface__intracellular_ion_concentrations__K_i = NV_Ith_S(rY, 22);
        // Units: millimolar; Initial value: 141.9670801746057
        double var_chaste_interface__Ca_i__Ca_i = NV_Ith_S(rY, 23);
        // Units: millimolar; Initial value: 0.00022355433459434943
        double var_chaste_interface__Ca_r__Ca_r = NV_Ith_S(rY, 27);
        // Units: millimolar; Initial value: 0.00022418117117903934
        
        const double var_i_Ca_L__i_Ca_L_max = ((((var_chaste_interface__membrane__V - 15.0) * 9048693.2787) * 3.87996927064e-07) * ((1.0 * var_chaste_interface__Ca_r__Ca_r * exp(((var_chaste_interface__membrane__V - 15.0) * 192970.0) * 3.87996927064e-07)) - (0.341 * NV_Ith_S(mParameters, 4)))) / (exp(((var_chaste_interface__membrane__V - 15.0) * 192970.0) * 3.87996927064e-07) - 1.0); // microA_per_microF
        const double var_i_Ca_L__i_Ca_L = NV_Ith_S(mParameters, 6) * var_chaste_interface__i_Ca_L_d_gate__d * var_chaste_interface__i_Ca_L_f_gate__f * var_chaste_interface__i_Ca_L_f2_gate__f2 * var_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca * var_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2 * var_i_Ca_L__i_Ca_L_max; // microA_per_microF
        const double var_equilibrium_potentials__E_Na = 26.7123387055 * log(140.0 / var_chaste_interface__intracellular_ion_concentrations__Na_i); // millivolt
        const double var_background_currents__i_Na_b = 0.0025 * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_Na); // microA_per_microF
        const double var_i_NaK__i_NaK = ((((1.0 / (1.0 + (0.1245 * exp((var_chaste_interface__membrane__V *  -9648.5) * 3.87996927064e-07)) + (exp(( -96485.0 * var_chaste_interface__membrane__V) * 3.87996927064e-07) * 0.0365332261305))) * 0.61875) / (1.0 + pow(10.0 / var_chaste_interface__intracellular_ion_concentrations__Na_i, 2.0))) * NV_Ith_S(mParameters, 5)) / (NV_Ith_S(mParameters, 5) + 1.5); // microA_per_microF
        const double var_i_to_2__i_to_2 = 20.0 * ((((var_chaste_interface__membrane__V * 3723.74209) * 3.87996927064e-07) * (var_chaste_interface__intracellular_ion_concentrations__Cl_i - (100.0 * exp((var_chaste_interface__membrane__V * 96485.0) * 3.87996927064e-07)))) / (1.0 - exp((var_chaste_interface__membrane__V * 96485.0) * 3.87996927064e-07))) * var_chaste_interface__i_to_2_a_gate__a; // microA_per_microF
        const double var_equilibrium_potentials__E_K = 26.7123387055 * log(NV_Ith_S(mParameters, 5) / var_chaste_interface__intracellular_ion_concentrations__K_i); // millivolt
        const double var_i_to_1__i_to_1 = NV_Ith_S(mParameters, 12) * var_chaste_interface__i_to_1_a_gate__a * ((0.8 * var_chaste_interface__i_to_1_i_gate__i) + (0.2 * var_chaste_interface__i_to_1_i2_gate__i2)) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_i_Na__i_Na = NV_Ith_S(mParameters, 7) * pow(var_chaste_interface__i_Na_m_gate__m, 3.0) * ((0.8 * var_chaste_interface__i_Na_h_gate__h) + (0.2 * var_chaste_interface__i_Na_j_gate__j)) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_Na); // microA_per_microF
        const double var_i_K_p__i_K_p = 0.00276 * (1.0 / (1.0 + exp((7.488 - var_chaste_interface__membrane__V) * 0.167224080268))) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_i_Na_L__i_Na_L = 0.037375 * pow(var_chaste_interface__i_Na_L_m_L_gate__m_L, 3.0) * var_chaste_interface__i_Na_L_h_L_gate__h_L * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_Na); // microA_per_microF
        const double var_i_Kr__i_Kr = (NV_Ith_S(mParameters, 10) * sqrt(NV_Ith_S(mParameters, 5) * 0.185185185185)) * var_chaste_interface__i_Kr_xr_gate__xr * (1.0 / (1.0 + exp((var_chaste_interface__membrane__V - 5.4) * 0.0490196078431))) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_i_NaCa__i_NaCa = ((0.4 * NV_Ith_S(mParameters, 11) * pow(var_chaste_interface__intracellular_ion_concentrations__Na_i, 3.0) * NV_Ith_S(mParameters, 4) * exp((var_chaste_interface__membrane__V * 33769.75) * 3.87996927064e-07)) - (var_chaste_interface__Ca_i__Ca_i * exp((var_chaste_interface__membrane__V *  -62715.25) * 3.87996927064e-07) * 4116000.0)) / ((1.0 + pow(0.000125 / (1.5 * var_chaste_interface__Ca_i__Ca_i), 2.0)) * (1.0 + (0.27 * exp((var_chaste_interface__membrane__V *  -62715.25) * 3.87996927064e-07))) * (((1.3 * pow(var_chaste_interface__intracellular_ion_concentrations__Na_i, 3.0)) + (var_chaste_interface__Ca_i__Ca_i * 1004882.8125) + (1860.867 * NV_Ith_S(mParameters, 4) * (1.0 + ((1.5 * var_chaste_interface__Ca_i__Ca_i) * 277.777777778)))) + (((1.0 + (var_chaste_interface__intracellular_ion_concentrations__Na_i * 0.0813008130081)) * 9878.4) + (pow(var_chaste_interface__intracellular_ion_concentrations__Na_i, 3.0) * NV_Ith_S(mParameters, 4)) + (var_chaste_interface__Ca_i__Ca_i * 4116000.0)))); // microA_per_microF
        const double var_background_currents__i_Ca_b = (((var_chaste_interface__membrane__V * 7429.17826389) * 3.87996927064e-07) * ((1.0 * var_chaste_interface__Ca_i__Ca_i * exp((var_chaste_interface__membrane__V * 192970.0) * 3.87996927064e-07)) - (0.341 * NV_Ith_S(mParameters, 4)))) / (exp((var_chaste_interface__membrane__V * 192970.0) * 3.87996927064e-07) - 1.0); // microA_per_microF
        const double var_background_currents__i_K_b = 0.005 * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_equilibrium_potentials__E_Cl =  -26.7123387055 * log(100.0 / var_chaste_interface__intracellular_ion_concentrations__Cl_i); // millivolt
        const double var_background_currents__i_Cl_b = 0.000225 * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_Cl); // microA_per_microF
        const double var_i_Ca_p__i_Ca_p = (0.0575 * var_chaste_interface__Ca_i__Ca_i) / (0.0005 + var_chaste_interface__Ca_i__Ca_i); // microA_per_microF
        const double var_i_Ks__g_Ks = 0.052581329 * (1.0 + (0.6 / (1.0 + pow(3.8e-05 / var_chaste_interface__Ca_i__Ca_i, 1.4)))); // milliS_per_microF
        const double var_i_Ks__i_Ks = var_i_Ks__g_Ks * var_chaste_interface__i_Ks_xs1_gate__xs1 * var_chaste_interface__i_Ks_xs2_gate__xs2 * (var_chaste_interface__membrane__V - (26.7123387055 * log((NV_Ith_S(mParameters, 5) + 2.5662) / (var_chaste_interface__intracellular_ion_concentrations__K_i + (0.01833 * var_chaste_interface__intracellular_ion_concentrations__Na_i))))); // microA_per_microF
        const double var_i_K1__g_K1 = 0.25 * sqrt(NV_Ith_S(mParameters, 5) * 0.185185185185); // milliS_per_microF
        const double var_i_K1_xK1_gate__alpha_xK1 = 1.02 / (1.0 + exp(0.2385 * (var_chaste_interface__membrane__V - (var_equilibrium_potentials__E_K + 59.215)))); // dimensionless
        const double var_i_K1__i_K1 = ((var_i_K1__g_K1 * (var_i_K1_xK1_gate__alpha_xK1 / (var_i_K1_xK1_gate__alpha_xK1 + (((0.49124 * exp(0.08032 * ((var_chaste_interface__membrane__V + 5.476) - var_equilibrium_potentials__E_K))) + exp(0.06175 * (var_chaste_interface__membrane__V - (594.31 + var_equilibrium_potentials__E_K)))) / (1.0 + exp( -0.5143 * ((var_chaste_interface__membrane__V + 4.753) - var_equilibrium_potentials__E_K))))))) + 0.004) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_membrane__i_tot = var_i_Na__i_Na + var_i_Na_L__i_Na_L + var_i_Ca_L__i_Ca_L + (0.13 * var_chaste_interface__i_Ca_T_b_gate__b * var_chaste_interface__i_Ca_T_g_gate__g * (var_chaste_interface__membrane__V - 50.0)) + var_i_to_1__i_to_1 + var_i_to_2__i_to_2 + var_i_Kr__i_Kr + var_i_Ks__i_Ks + var_i_K1__i_K1 + var_i_NaCa__i_NaCa + var_i_NaK__i_NaK + var_background_currents__i_Na_b + var_background_currents__i_K_b + var_background_currents__i_Ca_b + var_background_currents__i_Cl_b + var_i_Ca_p__i_Ca_p + var_i_K_p__i_K_p; // microA_per_microF
        var_chaste_interface__i_ionic = (var_membrane__i_tot) * HeartConfig::Instance()->GetCapacitance(); // uA_per_cm2
        
        const double i_ionic = var_chaste_interface__i_ionic;
        EXCEPT_IF_NOT(!std::isnan(i_ionic));
        return i_ionic;
    }
    
    void Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::EvaluateRhs(double var_chaste_interface__environment__time, const N_Vector rY, N_Vector rDY)
    {
        // Inputs:
        // Time units: millisecond
        double var_chaste_interface__membrane__V = NV_Ith_S(rY, 0);
        // Units: millivolt; Initial value: -83.43812846286808
        double var_chaste_interface__i_Na_m_gate__m = NV_Ith_S(rY, 1);
        // Units: dimensionless; Initial value: 0.002003390432234504
        double var_chaste_interface__i_Na_h_gate__h = NV_Ith_S(rY, 2);
        // Units: dimensionless; Initial value: 0.9786390933308567
        double var_chaste_interface__i_Na_j_gate__j = NV_Ith_S(rY, 3);
        // Units: dimensionless; Initial value: 0.09866447258167589
        double var_chaste_interface__i_Na_L_m_L_gate__m_L = NV_Ith_S(rY, 4);
        // Units: dimensionless; Initial value: 0.002003390432234504
        double var_chaste_interface__i_Na_L_h_L_gate__h_L = NV_Ith_S(rY, 5);
        // Units: dimensionless; Initial value: 0.8946968372659203
        double var_chaste_interface__i_Ca_L_d_gate__d = NV_Ith_S(rY, 6);
        // Units: dimensionless; Initial value: 0.000002322223865147363
        double var_chaste_interface__i_Ca_L_f_gate__f = NV_Ith_S(rY, 7);
        // Units: dimensionless; Initial value: 0.9985607329462358
        double var_chaste_interface__i_Ca_L_f2_gate__f2 = NV_Ith_S(rY, 8);
        // Units: dimensionless; Initial value: 0.8173435436674658
        double var_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca = NV_Ith_S(rY, 9);
        // Units: dimensionless; Initial value: 0.9610551285529658
        double var_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2 = NV_Ith_S(rY, 10);
        // Units: dimensionless; Initial value: 0.868690796671854
        double var_chaste_interface__i_Ca_T_b_gate__b = NV_Ith_S(rY, 11);
        // Units: dimensionless; Initial value: 0.0002563937630984438
        double var_chaste_interface__i_Ca_T_g_gate__g = NV_Ith_S(rY, 12);
        // Units: dimensionless; Initial value: 0.9720432601848331
        double var_chaste_interface__i_to_1_a_gate__a = NV_Ith_S(rY, 13);
        // Units: dimensionless; Initial value: 0.0004238729429342389
        double var_chaste_interface__i_to_1_i_gate__i = NV_Ith_S(rY, 14);
        // Units: dimensionless; Initial value: 0.9990935802459496
        double var_chaste_interface__i_to_1_i2_gate__i2 = NV_Ith_S(rY, 15);
        // Units: dimensionless; Initial value: 0.9777368439681764
        double var_chaste_interface__i_Kr_xr_gate__xr = NV_Ith_S(rY, 16);
        // Units: dimensionless; Initial value: 0.07084939408222911
        double var_chaste_interface__i_Ks_xs1_gate__xs1 = NV_Ith_S(rY, 17);
        // Units: dimensionless; Initial value: 0.0011737654433043125
        double var_chaste_interface__i_Ks_xs2_gate__xs2 = NV_Ith_S(rY, 18);
        // Units: dimensionless; Initial value: 0.001179442867470093
        double var_chaste_interface__i_to_2_a_gate__a = NV_Ith_S(rY, 19);
        // Units: dimensionless; Initial value: 0.0014909437525000811
        double var_chaste_interface__intracellular_ion_concentrations__Na_i = NV_Ith_S(rY, 20);
        // Units: millimolar; Initial value: 9.927155552932733
        double var_chaste_interface__intracellular_ion_concentrations__Cl_i = NV_Ith_S(rY, 21);
        // Units: millimolar; Initial value: 18.904682470140408
        double var_chaste_interface__intracellular_ion_concentrations__K_i = NV_Ith_S(rY, 22);
        // Units: millimolar; Initial value: 141.9670801746057
        double var_chaste_interface__Ca_i__Ca_i = NV_Ith_S(rY, 23);
        // Units: millimolar; Initial value: 0.00022355433459434943
        double var_chaste_interface__Ca_MK_act__Ca_MK_trap = NV_Ith_S(rY, 24);
        // Units: dimensionless; Initial value: 0.000008789168284782809
        double var_chaste_interface__Ca_NSR__Ca_NSR = NV_Ith_S(rY, 25);
        // Units: millimolar; Initial value: 1.2132524695849454
        double var_chaste_interface__Ca_JSR__Ca_JSR = NV_Ith_S(rY, 26);
        // Units: millimolar; Initial value: 1.1433050636518596
        double var_chaste_interface__Ca_r__Ca_r = NV_Ith_S(rY, 27);
        // Units: millimolar; Initial value: 0.00022418117117903934
        double var_chaste_interface__q_rel_ri_gate__ri = NV_Ith_S(rY, 28);
        // Units: dimensionless; Initial value: 0.7802870066567904
        double var_chaste_interface__q_rel_ro_gate__ro = NV_Ith_S(rY, 29);
        // Units: dimensionless; Initial value: 1.2785734760674763e-9
        
        
        // Mathematics
        double d_dt_chaste_interface__membrane__V;
        const double var_i_Ca_L__i_Ca_L_max = ((((var_chaste_interface__membrane__V - 15.0) * 9048693.2787) * 3.87996927064e-07) * ((1.0 * var_chaste_interface__Ca_r__Ca_r * exp(((var_chaste_interface__membrane__V - 15.0) * 192970.0) * 3.87996927064e-07)) - (0.341 * NV_Ith_S(mParameters, 4)))) / (exp(((var_chaste_interface__membrane__V - 15.0) * 192970.0) * 3.87996927064e-07) - 1.0); // microA_per_microF
        const double var_i_Ca_L__i_Ca_L = NV_Ith_S(mParameters, 6) * var_chaste_interface__i_Ca_L_d_gate__d * var_chaste_interface__i_Ca_L_f_gate__f * var_chaste_interface__i_Ca_L_f2_gate__f2 * var_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca * var_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2 * var_i_Ca_L__i_Ca_L_max; // microA_per_microF
        const double var_equilibrium_potentials__E_Na = 26.7123387055 * log(140.0 / var_chaste_interface__intracellular_ion_concentrations__Na_i); // millivolt
        const double var_background_currents__i_Na_b = 0.0025 * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_Na); // microA_per_microF
        const double var_i_NaK__i_NaK = ((((1.0 / (1.0 + (0.1245 * exp((var_chaste_interface__membrane__V *  -9648.5) * 3.87996927064e-07)) + (exp(( -96485.0 * var_chaste_interface__membrane__V) * 3.87996927064e-07) * 0.0365332261305))) * 0.61875) / (1.0 + pow(10.0 / var_chaste_interface__intracellular_ion_concentrations__Na_i, 2.0))) * NV_Ith_S(mParameters, 5)) / (NV_Ith_S(mParameters, 5) + 1.5); // microA_per_microF
        const double var_i_to_2__i_to_2 = 20.0 * ((((var_chaste_interface__membrane__V * 3723.74209) * 3.87996927064e-07) * (var_chaste_interface__intracellular_ion_concentrations__Cl_i - (100.0 * exp((var_chaste_interface__membrane__V * 96485.0) * 3.87996927064e-07)))) / (1.0 - exp((var_chaste_interface__membrane__V * 96485.0) * 3.87996927064e-07))) * var_chaste_interface__i_to_2_a_gate__a; // microA_per_microF
        const double var_equilibrium_potentials__E_K = 26.7123387055 * log(NV_Ith_S(mParameters, 5) / var_chaste_interface__intracellular_ion_concentrations__K_i); // millivolt
        const double var_i_to_1__i_to_1 = NV_Ith_S(mParameters, 12) * var_chaste_interface__i_to_1_a_gate__a * ((0.8 * var_chaste_interface__i_to_1_i_gate__i) + (0.2 * var_chaste_interface__i_to_1_i2_gate__i2)) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_i_Na__i_Na = NV_Ith_S(mParameters, 7) * pow(var_chaste_interface__i_Na_m_gate__m, 3.0) * ((0.8 * var_chaste_interface__i_Na_h_gate__h) + (0.2 * var_chaste_interface__i_Na_j_gate__j)) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_Na); // microA_per_microF
        const double var_i_K_p__i_K_p = 0.00276 * (1.0 / (1.0 + exp((7.488 - var_chaste_interface__membrane__V) * 0.167224080268))) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_i_Na_L__i_Na_L = 0.037375 * pow(var_chaste_interface__i_Na_L_m_L_gate__m_L, 3.0) * var_chaste_interface__i_Na_L_h_L_gate__h_L * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_Na); // microA_per_microF
        const double var_i_Kr__i_Kr = (NV_Ith_S(mParameters, 10) * sqrt(NV_Ith_S(mParameters, 5) * 0.185185185185)) * var_chaste_interface__i_Kr_xr_gate__xr * (1.0 / (1.0 + exp((var_chaste_interface__membrane__V - 5.4) * 0.0490196078431))) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_i_NaCa__i_NaCa = ((0.4 * NV_Ith_S(mParameters, 11) * pow(var_chaste_interface__intracellular_ion_concentrations__Na_i, 3.0) * NV_Ith_S(mParameters, 4) * exp((var_chaste_interface__membrane__V * 33769.75) * 3.87996927064e-07)) - (var_chaste_interface__Ca_i__Ca_i * exp((var_chaste_interface__membrane__V *  -62715.25) * 3.87996927064e-07) * 4116000.0)) / ((1.0 + pow(0.000125 / (1.5 * var_chaste_interface__Ca_i__Ca_i), 2.0)) * (1.0 + (0.27 * exp((var_chaste_interface__membrane__V *  -62715.25) * 3.87996927064e-07))) * (((1.3 * pow(var_chaste_interface__intracellular_ion_concentrations__Na_i, 3.0)) + (var_chaste_interface__Ca_i__Ca_i * 1004882.8125) + (1860.867 * NV_Ith_S(mParameters, 4) * (1.0 + ((1.5 * var_chaste_interface__Ca_i__Ca_i) * 277.777777778)))) + (((1.0 + (var_chaste_interface__intracellular_ion_concentrations__Na_i * 0.0813008130081)) * 9878.4) + (pow(var_chaste_interface__intracellular_ion_concentrations__Na_i, 3.0) * NV_Ith_S(mParameters, 4)) + (var_chaste_interface__Ca_i__Ca_i * 4116000.0)))); // microA_per_microF
        const double var_background_currents__i_Ca_b = (((var_chaste_interface__membrane__V * 7429.17826389) * 3.87996927064e-07) * ((1.0 * var_chaste_interface__Ca_i__Ca_i * exp((var_chaste_interface__membrane__V * 192970.0) * 3.87996927064e-07)) - (0.341 * NV_Ith_S(mParameters, 4)))) / (exp((var_chaste_interface__membrane__V * 192970.0) * 3.87996927064e-07) - 1.0); // microA_per_microF
        const double var_background_currents__i_K_b = 0.005 * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_equilibrium_potentials__E_Cl =  -26.7123387055 * log(100.0 / var_chaste_interface__intracellular_ion_concentrations__Cl_i); // millivolt
        const double var_background_currents__i_Cl_b = 0.000225 * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_Cl); // microA_per_microF
        const double var_i_Ca_p__i_Ca_p = (0.0575 * var_chaste_interface__Ca_i__Ca_i) / (0.0005 + var_chaste_interface__Ca_i__Ca_i); // microA_per_microF
        const double var_i_Ks__g_Ks = 0.052581329 * (1.0 + (0.6 / (1.0 + pow(3.8e-05 / var_chaste_interface__Ca_i__Ca_i, 1.4)))); // milliS_per_microF
        const double var_i_Ks__i_Ks = var_i_Ks__g_Ks * var_chaste_interface__i_Ks_xs1_gate__xs1 * var_chaste_interface__i_Ks_xs2_gate__xs2 * (var_chaste_interface__membrane__V - (26.7123387055 * log((NV_Ith_S(mParameters, 5) + 2.5662) / (var_chaste_interface__intracellular_ion_concentrations__K_i + (0.01833 * var_chaste_interface__intracellular_ion_concentrations__Na_i))))); // microA_per_microF
        const double var_i_K1__g_K1 = 0.25 * sqrt(NV_Ith_S(mParameters, 5) * 0.185185185185); // milliS_per_microF
        const double var_i_K1_xK1_gate__alpha_xK1 = 1.02 / (1.0 + exp(0.2385 * (var_chaste_interface__membrane__V - (var_equilibrium_potentials__E_K + 59.215)))); // dimensionless
        const double var_i_K1__i_K1 = ((var_i_K1__g_K1 * (var_i_K1_xK1_gate__alpha_xK1 / (var_i_K1_xK1_gate__alpha_xK1 + (((0.49124 * exp(0.08032 * ((var_chaste_interface__membrane__V + 5.476) - var_equilibrium_potentials__E_K))) + exp(0.06175 * (var_chaste_interface__membrane__V - (594.31 + var_equilibrium_potentials__E_K)))) / (1.0 + exp( -0.5143 * ((var_chaste_interface__membrane__V + 4.753) - var_equilibrium_potentials__E_K))))))) + 0.004) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_i_Na_m_gate__beta_m = 0.08 * exp((-var_chaste_interface__membrane__V) * 0.0909090909091); // per_millisecond
        const double var_i_Na_m_gate__alpha_m = (0.32 * (var_chaste_interface__membrane__V + 47.13)) / (1.0 - exp( -0.1 * (var_chaste_interface__membrane__V + 47.13))); // per_millisecond
        const double var_i_Na_h_gate__beta_h = (var_chaste_interface__membrane__V <  -40.0) ? ((3.56 * exp(0.079 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9)))) + (310000.0 * exp(0.35 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9))))) : (1.0 / (0.13 * (1.0 + exp(((var_chaste_interface__membrane__V + 10.66) - NV_Ith_S(mParameters, 9)) *  -0.0900900900901)))); // per_millisecond
        const double var_i_Na_h_gate__alpha_h = (var_chaste_interface__membrane__V <  -40.0) ? (0.135 * exp(((var_chaste_interface__membrane__V + 80.0) - NV_Ith_S(mParameters, 9)) *  -0.147058823529)) : 0.0; // per_millisecond
        const double var_i_Na_h_gate__tau_h = 1.0 / (var_i_Na_h_gate__alpha_h + var_i_Na_h_gate__beta_h); // millisecond
        const double var_i_Na_j_gate__beta_j = (var_chaste_interface__membrane__V <  -40.0) ? ((0.1212 * exp( -0.01052 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9)))) / (1.0 + exp( -0.1378 * ((var_chaste_interface__membrane__V + 40.14) - NV_Ith_S(mParameters, 9))))) : ((0.3 * exp( -2.535e-07 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9)))) / (1.0 + exp( -0.1 * ((var_chaste_interface__membrane__V + 32.0) - NV_Ith_S(mParameters, 9))))); // per_millisecond
        const double var_i_Na_j_gate__alpha_j = (var_chaste_interface__membrane__V <  -40.0) ? (((( -127140.0 * exp(0.2444 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9)))) - (3.474e-05 * exp( -0.04391 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9))))) * (var_chaste_interface__membrane__V + 37.78)) / (1.0 + exp(0.311 * ((var_chaste_interface__membrane__V + 79.23) - NV_Ith_S(mParameters, 9))))) : 0.0; // per_millisecond
        const double var_i_Na_j_gate__tau_j = 1.0 / (var_i_Na_j_gate__alpha_j + var_i_Na_j_gate__beta_j); // millisecond
        const double var_i_Na_L_m_L_gate__beta_m_L = 0.08 * exp((-var_chaste_interface__membrane__V) * 0.0909090909091); // per_millisecond
        const double var_i_Na_L_m_L_gate__alpha_m_L = (0.32 * (var_chaste_interface__membrane__V + 47.13)) / (1.0 - exp( -0.1 * (var_chaste_interface__membrane__V + 47.13))); // per_millisecond
        const double var_Ca_MK_act__Ca_MK_bound = (0.05 * (1.0 - var_chaste_interface__Ca_MK_act__Ca_MK_trap)) / (1.0 + (0.15 / var_chaste_interface__Ca_r__Ca_r)); // dimensionless
        const double var_Ca_MK_act__Ca_MK_act = var_Ca_MK_act__Ca_MK_bound + var_chaste_interface__Ca_MK_act__Ca_MK_trap; // dimensionless
        const double var_i_Ca_L_f_gate__tau_f = 4.0 + (0.005 * pow(var_chaste_interface__membrane__V - 2.5, 2.0)); // millisecond
        const double var_i_Ca_L_f2_gate__tau_f2 = 38.0 + (0.07 * pow(var_chaste_interface__membrane__V - 18.6, 2.0)); // millisecond
        const double var_i_Ca_L_f_Ca_gate__tau_f_Ca = 0.5 + ((var_Ca_MK_act__Ca_MK_act * 10.0) / ((1.0 * var_Ca_MK_act__Ca_MK_act) + 0.15)) + (1.0 / (1.0 + (var_chaste_interface__Ca_r__Ca_r * 333.333333333))); // millisecond
        const double var_i_Ca_L_f_Ca2_gate__tau_f_Ca2 = 125.0 + (300.0 / (1.0 + exp(((-var_i_Ca_L__i_Ca_L) - 0.175) * 25.0))); // millisecond
        const double var_i_to_1_a_gate__beta_a = (25.0 * exp((-(var_chaste_interface__membrane__V + 54.0)) * 0.05)) / (1.0 + exp((-(var_chaste_interface__membrane__V + 54.0)) * 0.05)); // per_millisecond
        const double var_i_to_1_a_gate__alpha_a = (25.0 * exp((var_chaste_interface__membrane__V - 76.0) * 0.05)) / (1.0 + exp((var_chaste_interface__membrane__V - 76.0) * 0.05)); // per_millisecond
        const double var_i_to_1_i_gate__alpha_i = 0.03 / (1.0 + exp((var_chaste_interface__membrane__V + 25.0) * 0.0666666666667)); // per_millisecond
        const double var_i_to_1_i2_gate__alpha_i2 = 0.00442 / (1.0 + exp((var_chaste_interface__membrane__V + 26.0) * 0.0666666666667)); // per_millisecond
        const double var_CT_K_Cl__CT_K_Cl = (7.0756e-06 * (var_equilibrium_potentials__E_K - var_equilibrium_potentials__E_Cl)) / ((var_equilibrium_potentials__E_K + 87.8251) - var_equilibrium_potentials__E_Cl); // millimolar_per_millisecond
        const double var_CT_Na_Cl__CT_Na_Cl = (9.8443e-06 * pow(var_equilibrium_potentials__E_Na - var_equilibrium_potentials__E_Cl, 4.0)) / (pow(var_equilibrium_potentials__E_Na - var_equilibrium_potentials__E_Cl, 4.0) + 59494197.6407); // millimolar_per_millisecond
        const double var_q_up__q_up = (0.5 * (((var_Ca_MK_act__Ca_MK_act * 0.75) / (0.15 + (var_Ca_MK_act__Ca_MK_act * 1.0))) + 1.0) * NV_Ith_S(mParameters, 2) * var_chaste_interface__Ca_i__Ca_i) / ((var_chaste_interface__Ca_i__Ca_i + 0.00092) - ((var_Ca_MK_act__Ca_MK_act * 0.00017) / (0.15 + (var_Ca_MK_act__Ca_MK_act * 1.0)))); // millimolar_per_millisecond
        const double var_q_leak__q_leak = (NV_Ith_S(mParameters, 0) * var_chaste_interface__Ca_NSR__Ca_NSR) * 0.0666666666667; // millimolar_per_millisecond
        const double var_Ca_r__q_diff = (var_chaste_interface__Ca_r__Ca_r - var_chaste_interface__Ca_i__Ca_i) * 5.0; // millimolar_per_millisecond
        const double var_q_tr__q_tr = (var_chaste_interface__Ca_NSR__Ca_NSR - var_chaste_interface__Ca_JSR__Ca_JSR) * 0.00833333333333; // millimolar_per_millisecond
        const double var_q_rel__q_rel = (NV_Ith_S(mParameters, 1) * (1.0 / (1.0 + exp(((NV_Ith_S(mParameters, 6) * var_i_Ca_L__i_Ca_L_max) + 13.0) * 0.2)))) * var_chaste_interface__q_rel_ro_gate__ro * var_chaste_interface__q_rel_ri_gate__ri * (var_chaste_interface__Ca_JSR__Ca_JSR - var_chaste_interface__Ca_r__Ca_r); // millimolar_per_millisecond
        const double var_q_rel_ri_gate__Ca_fac = 1.0 / (1.0 + exp((var_i_Ca_L__i_Ca_L + 0.05) * 66.6666666667)); // millimolar
        const double var_q_rel_ri_gate__tau_Ca_MK = (var_Ca_MK_act__Ca_MK_act * 10.0) / (0.15 + (1.0 * var_Ca_MK_act__Ca_MK_act)); // millisecond
        const double d_dt_chaste_interface__i_Na_m_gate__m = ((var_i_Na_m_gate__alpha_m / (var_i_Na_m_gate__alpha_m + var_i_Na_m_gate__beta_m)) - var_chaste_interface__i_Na_m_gate__m) / (1.0 / (var_i_Na_m_gate__alpha_m + var_i_Na_m_gate__beta_m)); // per_millisecond
        const double d_dt_chaste_interface__i_Na_h_gate__h = ((((var_i_Na_h_gate__alpha_h * (1.0 - (NV_Ith_S(mParameters, 8) * 0.01))) / (var_i_Na_h_gate__alpha_h + var_i_Na_h_gate__beta_h)) + (NV_Ith_S(mParameters, 8) * 0.01)) - var_chaste_interface__i_Na_h_gate__h) / var_i_Na_h_gate__tau_h; // per_millisecond
        const double d_dt_chaste_interface__i_Na_j_gate__j = ((((var_i_Na_j_gate__alpha_j * (1.0 - (NV_Ith_S(mParameters, 8) * 0.01))) / (var_i_Na_j_gate__alpha_j + var_i_Na_j_gate__beta_j)) + (NV_Ith_S(mParameters, 8) * 0.01)) - var_chaste_interface__i_Na_j_gate__j) / var_i_Na_j_gate__tau_j; // per_millisecond
        const double d_dt_chaste_interface__i_Na_L_m_L_gate__m_L = ((var_i_Na_L_m_L_gate__alpha_m_L / (var_i_Na_L_m_L_gate__alpha_m_L + var_i_Na_L_m_L_gate__beta_m_L)) - var_chaste_interface__i_Na_L_m_L_gate__m_L) / (1.0 / (var_i_Na_L_m_L_gate__alpha_m_L + var_i_Na_L_m_L_gate__beta_m_L)); // per_millisecond
        const double d_dt_chaste_interface__i_Na_L_h_L_gate__h_L = ((1.0 / (1.0 + exp((var_chaste_interface__membrane__V + 69.0) * 0.16393442623))) - var_chaste_interface__i_Na_L_h_L_gate__h_L) / (175.0 + (125.0 / (1.0 + exp((-(var_chaste_interface__membrane__V + 25.0)) * 0.166666666667)))); // per_millisecond
        const double d_dt_chaste_interface__i_Ca_L_d_gate__d = ((1.0 / (1.0 + exp((-(var_chaste_interface__membrane__V - 4.0)) * 0.148367952522))) - var_chaste_interface__i_Ca_L_d_gate__d) / (0.59 + ((0.8 * exp(0.052 * (var_chaste_interface__membrane__V + 13.0))) / (1.0 + exp(0.132 * (var_chaste_interface__membrane__V + 13.0))))); // per_millisecond
        const double d_dt_chaste_interface__i_Ca_L_f_gate__f = ((1.0 / (1.0 + exp((var_chaste_interface__membrane__V + 18.0) * 0.1))) - var_chaste_interface__i_Ca_L_f_gate__f) / var_i_Ca_L_f_gate__tau_f; // per_millisecond
        const double d_dt_chaste_interface__i_Ca_L_f2_gate__f2 = ((1.0 / (1.0 + exp((var_chaste_interface__membrane__V + 18.0) * 0.1))) - var_chaste_interface__i_Ca_L_f2_gate__f2) / var_i_Ca_L_f2_gate__tau_f2; // per_millisecond
        const double d_dt_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca = (((0.3 / (1.0 - (var_i_Ca_L__i_Ca_L * 20.0))) + (0.55 / (1.0 + (var_chaste_interface__Ca_r__Ca_r * 333.333333333))) + 0.15) - var_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca) / var_i_Ca_L_f_Ca_gate__tau_f_Ca; // per_millisecond
        const double d_dt_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2 = ((1.0 / (1.0 - (var_i_Ca_L__i_Ca_L * 100.0))) - var_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2) / var_i_Ca_L_f_Ca2_gate__tau_f_Ca2; // per_millisecond
        const double d_dt_chaste_interface__i_Ca_T_b_gate__b = ((1.0 / (1.0 + exp((-(var_chaste_interface__membrane__V + 33.0)) * 0.16393442623))) - var_chaste_interface__i_Ca_T_b_gate__b) / (1.0 / ((1.068 * exp((var_chaste_interface__membrane__V + 16.3) * 0.0333333333333)) + (1.068 * exp((-(var_chaste_interface__membrane__V + 16.3)) * 0.0333333333333)))); // per_millisecond
        const double d_dt_chaste_interface__i_Ca_T_g_gate__g = ((1.0 / (1.0 + exp((var_chaste_interface__membrane__V + 60.0) * 0.151515151515))) - var_chaste_interface__i_Ca_T_g_gate__g) / (1.0 / ((0.015 * exp((-(var_chaste_interface__membrane__V + 71.7)) * 0.0120048019208)) + (0.015 * exp((var_chaste_interface__membrane__V + 71.7) * 0.0649350649351)))); // per_millisecond
        const double d_dt_chaste_interface__i_to_1_a_gate__a = ((var_i_to_1_a_gate__alpha_a / (var_i_to_1_a_gate__alpha_a + var_i_to_1_a_gate__beta_a)) - var_chaste_interface__i_to_1_a_gate__a) / (1.0 / (var_i_to_1_a_gate__alpha_a + var_i_to_1_a_gate__beta_a)); // per_millisecond
        const double d_dt_chaste_interface__i_to_1_i_gate__i = ((var_i_to_1_i_gate__alpha_i / (var_i_to_1_i_gate__alpha_i + ((0.1 * exp((var_chaste_interface__membrane__V - 40.0) * 0.0666666666667)) / (1.0 + exp((var_chaste_interface__membrane__V - 40.0) * 0.0666666666667))))) - var_chaste_interface__i_to_1_i_gate__i) / (6.0 + (5.0 / (1.0 + exp((var_chaste_interface__membrane__V - 16.5) * 0.1)))); // per_millisecond
        const double d_dt_chaste_interface__i_to_1_i2_gate__i2 = ((var_i_to_1_i2_gate__alpha_i2 / (var_i_to_1_i2_gate__alpha_i2 + ((0.05 * exp((var_chaste_interface__membrane__V - 10.0) * 0.0666666666667)) / (1.0 + exp((var_chaste_interface__membrane__V - 10.0) * 0.0666666666667))))) - var_chaste_interface__i_to_1_i2_gate__i2) / (21.5 + (30.0 / (1.0 + exp((var_chaste_interface__membrane__V - 25.0) * 0.1)))); // per_millisecond
        const double d_dt_chaste_interface__i_Kr_xr_gate__xr = ((1.0 / (1.0 + exp((-(var_chaste_interface__membrane__V + 0.085)) * 0.0816326530612))) - var_chaste_interface__i_Kr_xr_gate__xr) / ((900.0 / (1.0 + exp(var_chaste_interface__membrane__V * 0.2))) + 100.0); // per_millisecond
        const double d_dt_chaste_interface__i_Ks_xs1_gate__xs1 = ((1.0 / (1.0 + exp((-(var_chaste_interface__membrane__V - 9.0)) * 0.0729927007299))) - var_chaste_interface__i_Ks_xs1_gate__xs1) / (1.0 / (((7.61e-05 * (var_chaste_interface__membrane__V + 44.6)) / (1.0 - exp( -9.97 * (var_chaste_interface__membrane__V + 44.6)))) + ((0.00036 * (var_chaste_interface__membrane__V - 0.55)) / (exp(0.128 * (var_chaste_interface__membrane__V - 0.55)) - 1.0)))); // per_millisecond
        const double d_dt_chaste_interface__i_Ks_xs2_gate__xs2 = ((1.0 / (1.0 + exp((-(var_chaste_interface__membrane__V - 9.0)) * 0.0729927007299))) - var_chaste_interface__i_Ks_xs2_gate__xs2) / (2.0 / (((7.61e-05 * (var_chaste_interface__membrane__V + 44.6)) / (1.0 - exp( -9.97 * (var_chaste_interface__membrane__V + 44.6)))) + ((0.00036 * (var_chaste_interface__membrane__V - 0.55)) / (exp(0.128 * (var_chaste_interface__membrane__V - 0.55)) - 1.0)))); // per_millisecond
        const double d_dt_chaste_interface__i_to_2_a_gate__a = ((1.0 / (1.0 + (0.1502 / var_chaste_interface__Ca_r__Ca_r))) - var_chaste_interface__i_to_2_a_gate__a) * 1.0; // per_millisecond
        const double d_dt_chaste_interface__intracellular_ion_concentrations__Na_i = NV_Ith_S(mParameters, 3) * ((((var_i_Na__i_Na + var_i_Na_L__i_Na_L + var_background_currents__i_Na_b + (3.0 * var_i_NaK__i_NaK) + (3.0 * var_i_NaCa__i_NaCa)) *  -0.0001533576) * 4.41274623303e-05) + var_CT_Na_Cl__CT_Na_Cl); // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__intracellular_ion_concentrations__Cl_i = NV_Ith_S(mParameters, 3) * ((((var_i_to_2__i_to_2 + var_background_currents__i_Cl_b) *  -0.0001533576) * 4.41274623303e-05) + var_CT_Na_Cl__CT_Na_Cl + var_CT_K_Cl__CT_K_Cl); // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__intracellular_ion_concentrations__K_i = NV_Ith_S(mParameters, 3) * (((((var_i_to_1__i_to_1 + var_i_K1__i_K1 + var_i_Kr__i_Kr + var_i_Ks__i_Ks + var_i_K_p__i_K_p + var_background_currents__i_K_b) - (2.0 * var_i_NaK__i_NaK)) *  -0.0001533576) * 4.41274623303e-05) + var_CT_K_Cl__CT_K_Cl); // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__Ca_i__Ca_i = (-(1.0 / (1.0 + ((var_chaste_interface__Ca_i__Ca_i * 0.14) / pow(var_chaste_interface__Ca_i__Ca_i + 0.0005, 2.0)) + ((var_chaste_interface__Ca_i__Ca_i * 0.1) / pow(var_chaste_interface__Ca_i__Ca_i + 0.00238, 2.0))))) * ((((((var_background_currents__i_Ca_b + var_i_Ca_p__i_Ca_p) - (2.0 * var_i_NaCa__i_NaCa)) * 0.0001533576) * 2.20637311651e-05) + (((var_q_up__q_up - var_q_leak__q_leak) * 0.01906608) * 4.25763820294)) - ((var_Ca_r__q_diff * 0.006908) * 4.25763820294)); // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__Ca_MK_act__Ca_MK_trap = (0.05 * var_Ca_MK_act__Ca_MK_bound * (var_Ca_MK_act__Ca_MK_bound + var_chaste_interface__Ca_MK_act__Ca_MK_trap)) - (0.00068 * var_chaste_interface__Ca_MK_act__Ca_MK_trap); // per_millisecond
        const double d_dt_chaste_interface__Ca_NSR__Ca_NSR = var_q_up__q_up - (var_q_leak__q_leak + ((var_q_tr__q_tr * 0.00165792) * 52.4491662681)); // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__Ca_JSR__Ca_JSR = (var_q_tr__q_tr - var_q_rel__q_rel) / (1.0 + (8.0 / pow(0.8 + var_chaste_interface__Ca_JSR__Ca_JSR, 2.0))); // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__Ca_r__Ca_r = (1.0 / (1.0 + ((var_chaste_interface__Ca_r__Ca_r * 0.094) / pow(var_chaste_interface__Ca_r__Ca_r + 0.00087, 2.0)) + ((var_chaste_interface__Ca_r__Ca_r * 2.248) / pow(var_chaste_interface__Ca_r__Ca_r + 0.0087, 2.0)))) * ((((var_i_Ca_L__i_Ca_L *  -0.0001533576) * 0.000750166859615) + ((var_q_rel__q_rel * 0.00165792) * 144.7596989)) - var_Ca_r__q_diff); // 'millimole per litre per millisecond'
        const double d_dt_chaste_interface__q_rel_ri_gate__ri = ((1.0 / (1.0 + exp(((var_chaste_interface__Ca_r__Ca_r - 0.0004) + (0.002 * var_q_rel_ri_gate__Ca_fac)) * 40000.0))) - var_chaste_interface__q_rel_ri_gate__ri) / (((350.0 - var_q_rel_ri_gate__tau_Ca_MK) / (1.0 + exp(((var_chaste_interface__Ca_r__Ca_r - 0.003) + (0.003 * var_q_rel_ri_gate__Ca_fac)) * 5000.0))) + 3.0 + var_q_rel_ri_gate__tau_Ca_MK); // per_millisecond
        const double d_dt_chaste_interface__q_rel_ro_gate__ro = ((((pow(var_chaste_interface__Ca_JSR__Ca_JSR, 1.9) / (pow(var_chaste_interface__Ca_JSR__Ca_JSR, 1.9) + pow((49.28 * var_chaste_interface__Ca_r__Ca_r) / (var_chaste_interface__Ca_r__Ca_r + 0.0028), 1.9))) * pow(var_i_Ca_L__i_Ca_L, 2.0)) / (pow(var_i_Ca_L__i_Ca_L, 2.0) + 1.0)) - var_chaste_interface__q_rel_ro_gate__ro) * 0.333333333333; // per_millisecond
        
        if (mSetVoltageDerivativeToZero)
        {
            d_dt_chaste_interface__membrane__V = 0.0;
        }
        else
        {
            var_chaste_interface__membrane__i_stim = GetIntracellularAreaStimulus(var_chaste_interface__environment__time);
            const double var_membrane__i_tot = var_i_Na__i_Na + var_i_Na_L__i_Na_L + var_i_Ca_L__i_Ca_L + (0.13 * var_chaste_interface__i_Ca_T_b_gate__b * var_chaste_interface__i_Ca_T_g_gate__g * (var_chaste_interface__membrane__V - 50.0)) + var_i_to_1__i_to_1 + var_i_to_2__i_to_2 + var_i_Kr__i_Kr + var_i_Ks__i_Ks + var_i_K1__i_K1 + var_i_NaCa__i_NaCa + var_i_NaK__i_NaK + var_background_currents__i_Na_b + var_background_currents__i_K_b + var_background_currents__i_Ca_b + var_background_currents__i_Cl_b + var_i_Ca_p__i_Ca_p + var_i_K_p__i_K_p; // microA_per_microF
            d_dt_chaste_interface__membrane__V = -(var_membrane__i_tot + (var_chaste_interface__membrane__i_stim / HeartConfig::Instance()->GetCapacitance())); // 'millivolt per millisecond'
        }
        
        NV_Ith_S(rDY, 0) = d_dt_chaste_interface__membrane__V;
        NV_Ith_S(rDY, 1) = d_dt_chaste_interface__i_Na_m_gate__m;
        NV_Ith_S(rDY, 2) = d_dt_chaste_interface__i_Na_h_gate__h;
        NV_Ith_S(rDY, 3) = d_dt_chaste_interface__i_Na_j_gate__j;
        NV_Ith_S(rDY, 4) = d_dt_chaste_interface__i_Na_L_m_L_gate__m_L;
        NV_Ith_S(rDY, 5) = d_dt_chaste_interface__i_Na_L_h_L_gate__h_L;
        NV_Ith_S(rDY, 6) = d_dt_chaste_interface__i_Ca_L_d_gate__d;
        NV_Ith_S(rDY, 7) = d_dt_chaste_interface__i_Ca_L_f_gate__f;
        NV_Ith_S(rDY, 8) = d_dt_chaste_interface__i_Ca_L_f2_gate__f2;
        NV_Ith_S(rDY, 9) = d_dt_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca;
        NV_Ith_S(rDY, 10) = d_dt_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2;
        NV_Ith_S(rDY, 11) = d_dt_chaste_interface__i_Ca_T_b_gate__b;
        NV_Ith_S(rDY, 12) = d_dt_chaste_interface__i_Ca_T_g_gate__g;
        NV_Ith_S(rDY, 13) = d_dt_chaste_interface__i_to_1_a_gate__a;
        NV_Ith_S(rDY, 14) = d_dt_chaste_interface__i_to_1_i_gate__i;
        NV_Ith_S(rDY, 15) = d_dt_chaste_interface__i_to_1_i2_gate__i2;
        NV_Ith_S(rDY, 16) = d_dt_chaste_interface__i_Kr_xr_gate__xr;
        NV_Ith_S(rDY, 17) = d_dt_chaste_interface__i_Ks_xs1_gate__xs1;
        NV_Ith_S(rDY, 18) = d_dt_chaste_interface__i_Ks_xs2_gate__xs2;
        NV_Ith_S(rDY, 19) = d_dt_chaste_interface__i_to_2_a_gate__a;
        NV_Ith_S(rDY, 20) = d_dt_chaste_interface__intracellular_ion_concentrations__Na_i;
        NV_Ith_S(rDY, 21) = d_dt_chaste_interface__intracellular_ion_concentrations__Cl_i;
        NV_Ith_S(rDY, 22) = d_dt_chaste_interface__intracellular_ion_concentrations__K_i;
        NV_Ith_S(rDY, 23) = d_dt_chaste_interface__Ca_i__Ca_i;
        NV_Ith_S(rDY, 24) = d_dt_chaste_interface__Ca_MK_act__Ca_MK_trap;
        NV_Ith_S(rDY, 25) = d_dt_chaste_interface__Ca_NSR__Ca_NSR;
        NV_Ith_S(rDY, 26) = d_dt_chaste_interface__Ca_JSR__Ca_JSR;
        NV_Ith_S(rDY, 27) = d_dt_chaste_interface__Ca_r__Ca_r;
        NV_Ith_S(rDY, 28) = d_dt_chaste_interface__q_rel_ri_gate__ri;
        NV_Ith_S(rDY, 29) = d_dt_chaste_interface__q_rel_ro_gate__ro;
    }
    
    N_Vector Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode::ComputeDerivedQuantities(double var_chaste_interface__environment__time, const N_Vector & rY)
    {
        // Inputs:
        // Time units: millisecond
        double var_chaste_interface__membrane__V = NV_Ith_S(rY, 0);
        // Units: millivolt; Initial value: -83.43812846286808
        double var_chaste_interface__i_Na_m_gate__m = NV_Ith_S(rY, 1);
        // Units: dimensionless; Initial value: 0.002003390432234504
        double var_chaste_interface__i_Na_h_gate__h = NV_Ith_S(rY, 2);
        // Units: dimensionless; Initial value: 0.9786390933308567
        double var_chaste_interface__i_Na_j_gate__j = NV_Ith_S(rY, 3);
        // Units: dimensionless; Initial value: 0.09866447258167589
        double var_chaste_interface__i_Ca_L_d_gate__d = NV_Ith_S(rY, 6);
        // Units: dimensionless; Initial value: 0.000002322223865147363
        double var_chaste_interface__i_Ca_L_f_gate__f = NV_Ith_S(rY, 7);
        // Units: dimensionless; Initial value: 0.9985607329462358
        double var_chaste_interface__i_Ca_L_f2_gate__f2 = NV_Ith_S(rY, 8);
        // Units: dimensionless; Initial value: 0.8173435436674658
        double var_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca = NV_Ith_S(rY, 9);
        // Units: dimensionless; Initial value: 0.9610551285529658
        double var_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2 = NV_Ith_S(rY, 10);
        // Units: dimensionless; Initial value: 0.868690796671854
        double var_chaste_interface__i_to_1_a_gate__a = NV_Ith_S(rY, 13);
        // Units: dimensionless; Initial value: 0.0004238729429342389
        double var_chaste_interface__i_to_1_i_gate__i = NV_Ith_S(rY, 14);
        // Units: dimensionless; Initial value: 0.9990935802459496
        double var_chaste_interface__i_to_1_i2_gate__i2 = NV_Ith_S(rY, 15);
        // Units: dimensionless; Initial value: 0.9777368439681764
        double var_chaste_interface__i_Kr_xr_gate__xr = NV_Ith_S(rY, 16);
        // Units: dimensionless; Initial value: 0.07084939408222911
        double var_chaste_interface__i_Ks_xs1_gate__xs1 = NV_Ith_S(rY, 17);
        // Units: dimensionless; Initial value: 0.0011737654433043125
        double var_chaste_interface__i_Ks_xs2_gate__xs2 = NV_Ith_S(rY, 18);
        // Units: dimensionless; Initial value: 0.001179442867470093
        double var_chaste_interface__intracellular_ion_concentrations__Na_i = NV_Ith_S(rY, 20);
        // Units: millimolar; Initial value: 9.927155552932733
        double var_chaste_interface__intracellular_ion_concentrations__K_i = NV_Ith_S(rY, 22);
        // Units: millimolar; Initial value: 141.9670801746057
        double var_chaste_interface__Ca_i__Ca_i = NV_Ith_S(rY, 23);
        // Units: millimolar; Initial value: 0.00022355433459434943
        double var_chaste_interface__Ca_MK_act__Ca_MK_trap = NV_Ith_S(rY, 24);
        // Units: dimensionless; Initial value: 0.000008789168284782809
        double var_chaste_interface__Ca_JSR__Ca_JSR = NV_Ith_S(rY, 26);
        // Units: millimolar; Initial value: 1.1433050636518596
        double var_chaste_interface__Ca_r__Ca_r = NV_Ith_S(rY, 27);
        // Units: millimolar; Initial value: 0.00022418117117903934
        double var_chaste_interface__q_rel_ri_gate__ri = NV_Ith_S(rY, 28);
        // Units: dimensionless; Initial value: 0.7802870066567904
        double var_chaste_interface__q_rel_ro_gate__ro = NV_Ith_S(rY, 29);
        // Units: dimensionless; Initial value: 1.2785734760674763e-9
        
        
        // Mathematics
        var_chaste_interface__membrane__i_stim = GetIntracellularAreaStimulus(var_chaste_interface__environment__time);
        const double var_i_Ca_L__i_Ca_L_max = ((((var_chaste_interface__membrane__V - 15.0) * 9048693.2787) * 3.87996927064e-07) * ((1.0 * var_chaste_interface__Ca_r__Ca_r * exp(((var_chaste_interface__membrane__V - 15.0) * 192970.0) * 3.87996927064e-07)) - (0.341 * NV_Ith_S(mParameters, 4)))) / (exp(((var_chaste_interface__membrane__V - 15.0) * 192970.0) * 3.87996927064e-07) - 1.0); // microA_per_microF
        const double var_i_Ca_L__i_Ca_L = NV_Ith_S(mParameters, 6) * var_chaste_interface__i_Ca_L_d_gate__d * var_chaste_interface__i_Ca_L_f_gate__f * var_chaste_interface__i_Ca_L_f2_gate__f2 * var_chaste_interface__i_Ca_L_f_Ca_gate__f_Ca * var_chaste_interface__i_Ca_L_f_Ca2_gate__f_Ca2 * var_i_Ca_L__i_Ca_L_max; // microA_per_microF
        const double var_equilibrium_potentials__E_Na = 26.7123387055 * log(140.0 / var_chaste_interface__intracellular_ion_concentrations__Na_i); // millivolt
        const double var_equilibrium_potentials__E_K = 26.7123387055 * log(NV_Ith_S(mParameters, 5) / var_chaste_interface__intracellular_ion_concentrations__K_i); // millivolt
        const double var_i_to_1__i_to_1 = NV_Ith_S(mParameters, 12) * var_chaste_interface__i_to_1_a_gate__a * ((0.8 * var_chaste_interface__i_to_1_i_gate__i) + (0.2 * var_chaste_interface__i_to_1_i2_gate__i2)) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_i_Na__i_Na = NV_Ith_S(mParameters, 7) * pow(var_chaste_interface__i_Na_m_gate__m, 3.0) * ((0.8 * var_chaste_interface__i_Na_h_gate__h) + (0.2 * var_chaste_interface__i_Na_j_gate__j)) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_Na); // microA_per_microF
        const double var_i_Kr__i_Kr = (NV_Ith_S(mParameters, 10) * sqrt(NV_Ith_S(mParameters, 5) * 0.185185185185)) * var_chaste_interface__i_Kr_xr_gate__xr * (1.0 / (1.0 + exp((var_chaste_interface__membrane__V - 5.4) * 0.0490196078431))) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_i_NaCa__i_NaCa = ((0.4 * NV_Ith_S(mParameters, 11) * pow(var_chaste_interface__intracellular_ion_concentrations__Na_i, 3.0) * NV_Ith_S(mParameters, 4) * exp((var_chaste_interface__membrane__V * 33769.75) * 3.87996927064e-07)) - (var_chaste_interface__Ca_i__Ca_i * exp((var_chaste_interface__membrane__V *  -62715.25) * 3.87996927064e-07) * 4116000.0)) / ((1.0 + pow(0.000125 / (1.5 * var_chaste_interface__Ca_i__Ca_i), 2.0)) * (1.0 + (0.27 * exp((var_chaste_interface__membrane__V *  -62715.25) * 3.87996927064e-07))) * (((1.3 * pow(var_chaste_interface__intracellular_ion_concentrations__Na_i, 3.0)) + (var_chaste_interface__Ca_i__Ca_i * 1004882.8125) + (1860.867 * NV_Ith_S(mParameters, 4) * (1.0 + ((1.5 * var_chaste_interface__Ca_i__Ca_i) * 277.777777778)))) + (((1.0 + (var_chaste_interface__intracellular_ion_concentrations__Na_i * 0.0813008130081)) * 9878.4) + (pow(var_chaste_interface__intracellular_ion_concentrations__Na_i, 3.0) * NV_Ith_S(mParameters, 4)) + (var_chaste_interface__Ca_i__Ca_i * 4116000.0)))); // microA_per_microF
        const double var_i_Ks__g_Ks = 0.052581329 * (1.0 + (0.6 / (1.0 + pow(3.8e-05 / var_chaste_interface__Ca_i__Ca_i, 1.4)))); // milliS_per_microF
        const double var_i_Ks__i_Ks = var_i_Ks__g_Ks * var_chaste_interface__i_Ks_xs1_gate__xs1 * var_chaste_interface__i_Ks_xs2_gate__xs2 * (var_chaste_interface__membrane__V - (26.7123387055 * log((NV_Ith_S(mParameters, 5) + 2.5662) / (var_chaste_interface__intracellular_ion_concentrations__K_i + (0.01833 * var_chaste_interface__intracellular_ion_concentrations__Na_i))))); // microA_per_microF
        const double var_i_K1__g_K1 = 0.25 * sqrt(NV_Ith_S(mParameters, 5) * 0.185185185185); // milliS_per_microF
        const double var_i_K1_xK1_gate__alpha_xK1 = 1.02 / (1.0 + exp(0.2385 * (var_chaste_interface__membrane__V - (var_equilibrium_potentials__E_K + 59.215)))); // dimensionless
        const double var_i_K1__i_K1 = ((var_i_K1__g_K1 * (var_i_K1_xK1_gate__alpha_xK1 / (var_i_K1_xK1_gate__alpha_xK1 + (((0.49124 * exp(0.08032 * ((var_chaste_interface__membrane__V + 5.476) - var_equilibrium_potentials__E_K))) + exp(0.06175 * (var_chaste_interface__membrane__V - (594.31 + var_equilibrium_potentials__E_K)))) / (1.0 + exp( -0.5143 * ((var_chaste_interface__membrane__V + 4.753) - var_equilibrium_potentials__E_K))))))) + 0.004) * (var_chaste_interface__membrane__V - var_equilibrium_potentials__E_K); // microA_per_microF
        const double var_i_Na_h_gate__beta_h = (var_chaste_interface__membrane__V <  -40.0) ? ((3.56 * exp(0.079 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9)))) + (310000.0 * exp(0.35 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9))))) : (1.0 / (0.13 * (1.0 + exp(((var_chaste_interface__membrane__V + 10.66) - NV_Ith_S(mParameters, 9)) *  -0.0900900900901)))); // per_millisecond
        const double var_i_Na_h_gate__alpha_h = (var_chaste_interface__membrane__V <  -40.0) ? (0.135 * exp(((var_chaste_interface__membrane__V + 80.0) - NV_Ith_S(mParameters, 9)) *  -0.147058823529)) : 0.0; // per_millisecond
        const double var_i_Na_h_gate__tau_h = 1.0 / (var_i_Na_h_gate__alpha_h + var_i_Na_h_gate__beta_h); // millisecond
        const double var_i_Na_j_gate__beta_j = (var_chaste_interface__membrane__V <  -40.0) ? ((0.1212 * exp( -0.01052 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9)))) / (1.0 + exp( -0.1378 * ((var_chaste_interface__membrane__V + 40.14) - NV_Ith_S(mParameters, 9))))) : ((0.3 * exp( -2.535e-07 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9)))) / (1.0 + exp( -0.1 * ((var_chaste_interface__membrane__V + 32.0) - NV_Ith_S(mParameters, 9))))); // per_millisecond
        const double var_i_Na_j_gate__alpha_j = (var_chaste_interface__membrane__V <  -40.0) ? (((( -127140.0 * exp(0.2444 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9)))) - (3.474e-05 * exp( -0.04391 * (var_chaste_interface__membrane__V - NV_Ith_S(mParameters, 9))))) * (var_chaste_interface__membrane__V + 37.78)) / (1.0 + exp(0.311 * ((var_chaste_interface__membrane__V + 79.23) - NV_Ith_S(mParameters, 9))))) : 0.0; // per_millisecond
        const double var_i_Na_j_gate__tau_j = 1.0 / (var_i_Na_j_gate__alpha_j + var_i_Na_j_gate__beta_j); // millisecond
        const double var_Ca_MK_act__Ca_MK_bound = (0.05 * (1.0 - var_chaste_interface__Ca_MK_act__Ca_MK_trap)) / (1.0 + (0.15 / var_chaste_interface__Ca_r__Ca_r)); // dimensionless
        const double var_Ca_MK_act__Ca_MK_act = var_Ca_MK_act__Ca_MK_bound + var_chaste_interface__Ca_MK_act__Ca_MK_trap; // dimensionless
        const double var_i_Ca_L_f_gate__tau_f = 4.0 + (0.005 * pow(var_chaste_interface__membrane__V - 2.5, 2.0)); // millisecond
        const double var_i_Ca_L_f2_gate__tau_f2 = 38.0 + (0.07 * pow(var_chaste_interface__membrane__V - 18.6, 2.0)); // millisecond
        const double var_i_Ca_L_f_Ca_gate__tau_f_Ca = 0.5 + ((var_Ca_MK_act__Ca_MK_act * 10.0) / ((1.0 * var_Ca_MK_act__Ca_MK_act) + 0.15)) + (1.0 / (1.0 + (var_chaste_interface__Ca_r__Ca_r * 333.333333333))); // millisecond
        const double var_i_Ca_L_f_Ca2_gate__tau_f_Ca2 = 125.0 + (300.0 / (1.0 + exp(((-var_i_Ca_L__i_Ca_L) - 0.175) * 25.0))); // millisecond
        const double var_q_rel__q_rel = (NV_Ith_S(mParameters, 1) * (1.0 / (1.0 + exp(((NV_Ith_S(mParameters, 6) * var_i_Ca_L__i_Ca_L_max) + 13.0) * 0.2)))) * var_chaste_interface__q_rel_ro_gate__ro * var_chaste_interface__q_rel_ri_gate__ri * (var_chaste_interface__Ca_JSR__Ca_JSR - var_chaste_interface__Ca_r__Ca_r); // millimolar_per_millisecond
        
        N_Vector dqs = N_VNew_Serial(18);
        NV_Ith_S(dqs, 0) = var_q_rel__q_rel;
        NV_Ith_S(dqs, 1) = var_i_Ca_L__i_Ca_L;
        NV_Ith_S(dqs, 2) = var_i_Ca_L_f2_gate__tau_f2;
        NV_Ith_S(dqs, 3) = var_i_Ca_L_f_Ca2_gate__tau_f_Ca2;
        NV_Ith_S(dqs, 4) = var_i_Ca_L_f_Ca_gate__tau_f_Ca;
        NV_Ith_S(dqs, 5) = var_i_Ca_L_f_gate__tau_f;
        NV_Ith_S(dqs, 6) = var_i_Na__i_Na;
        NV_Ith_S(dqs, 7) = var_i_Na_h_gate__tau_h;
        NV_Ith_S(dqs, 8) = var_i_Na_j_gate__tau_j;
        NV_Ith_S(dqs, 9) = var_i_K1__i_K1;
        NV_Ith_S(dqs, 10) = var_i_K1__g_K1;
        NV_Ith_S(dqs, 11) = var_i_Kr__i_Kr;
        NV_Ith_S(dqs, 12) = var_i_Ks__i_Ks;
        NV_Ith_S(dqs, 13) = var_i_Ks__g_Ks;
        NV_Ith_S(dqs, 14) = var_i_NaCa__i_NaCa;
        NV_Ith_S(dqs, 15) = var_chaste_interface__membrane__i_stim;
        NV_Ith_S(dqs, 16) = var_i_to_1__i_to_1;
        NV_Ith_S(dqs, 17) = var_chaste_interface__environment__time;
        return dqs;
    }
    
template<>
void OdeSystemInformation<Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode>::Initialise(void)
{
    // Time units: millisecond
    // 
    this->mSystemName = "aslanidi_2009";
    
    this->mVariableNames.push_back("membrane_voltage");
    this->mVariableUnits.push_back("millivolt");
    this->mInitialConditions.push_back(-83.43812846286808);

    this->mVariableNames.push_back("membrane_fast_sodium_current_m_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.002003390432234504);

    this->mVariableNames.push_back("membrane_fast_sodium_current_h_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9786390933308567);

    this->mVariableNames.push_back("membrane_fast_sodium_current_j_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.09866447258167589);

    this->mVariableNames.push_back("i_Na_L_m_L_gate__m_L");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.002003390432234504);

    this->mVariableNames.push_back("i_Na_L_h_L_gate__h_L");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.8946968372659203);

    this->mVariableNames.push_back("membrane_L_type_calcium_current_d_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.000002322223865147363);

    this->mVariableNames.push_back("membrane_L_type_calcium_current_f_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9985607329462358);

    this->mVariableNames.push_back("membrane_L_type_calcium_current_f2_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.8173435436674658);

    this->mVariableNames.push_back("membrane_L_type_calcium_current_fCa_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9610551285529658);

    this->mVariableNames.push_back("membrane_L_type_calcium_current_fCa2_gate");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.868690796671854);

    this->mVariableNames.push_back("i_Ca_T_b_gate__b");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0002563937630984438);

    this->mVariableNames.push_back("i_Ca_T_g_gate__g");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9720432601848331);

    this->mVariableNames.push_back("i_to_1_a_gate__a");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0004238729429342389);

    this->mVariableNames.push_back("i_to_1_i_gate__i");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9990935802459496);

    this->mVariableNames.push_back("i_to_1_i2_gate__i2");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.9777368439681764);

    this->mVariableNames.push_back("i_Kr_xr_gate__xr");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.07084939408222911);

    this->mVariableNames.push_back("i_Ks_xs1_gate__xs1");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0011737654433043125);

    this->mVariableNames.push_back("i_Ks_xs2_gate__xs2");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.001179442867470093);

    this->mVariableNames.push_back("i_to_2_a_gate__a");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0014909437525000811);

    this->mVariableNames.push_back("cytosolic_sodium_concentration");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(9.927155552932733);

    this->mVariableNames.push_back("intracellular_ion_concentrations__Cl_i");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(18.904682470140408);

    this->mVariableNames.push_back("cytosolic_potassium_concentration");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(141.9670801746057);

    this->mVariableNames.push_back("cytosolic_calcium_concentration");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(0.00022355433459434943);

    this->mVariableNames.push_back("Ca_MK_act__Ca_MK_trap");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.000008789168284782809);

    this->mVariableNames.push_back("Ca_NSR__Ca_NSR");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(1.2132524695849454);

    this->mVariableNames.push_back("JSR_calcium_concentration");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(1.1433050636518596);

    this->mVariableNames.push_back("diadicspace_calcium_concentration");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(0.00022418117117903934);

    this->mVariableNames.push_back("q_rel_ri_gate__ri");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.7802870066567904);

    this->mVariableNames.push_back("q_rel_ro_gate__ro");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(1.2785734760674763e-9);

    this->mParameterNames.push_back("SR_leak_current_max");
    this->mParameterUnits.push_back("millimolar_per_millisecond");
    
    this->mParameterNames.push_back("SR_release_current_max");
    this->mParameterUnits.push_back("per_millisecond");
    
    this->mParameterNames.push_back("SR_uptake_current_max");
    this->mParameterUnits.push_back("millimolar_per_millisecond");
    
    this->mParameterNames.push_back("concentration_clamp_onoff");
    this->mParameterUnits.push_back("dimensionless");
    
    this->mParameterNames.push_back("extracellular_calcium_concentration");
    this->mParameterUnits.push_back("millimolar");
    
    this->mParameterNames.push_back("extracellular_potassium_concentration");
    this->mParameterUnits.push_back("millimolar");
    
    this->mParameterNames.push_back("membrane_L_type_calcium_current_conductance");
    this->mParameterUnits.push_back("dimensionless");
    
    this->mParameterNames.push_back("membrane_fast_sodium_current_conductance");
    this->mParameterUnits.push_back("milliS_per_microF");
    
    this->mParameterNames.push_back("membrane_fast_sodium_current_reduced_inactivation");
    this->mParameterUnits.push_back("dimensionless");
    
    this->mParameterNames.push_back("membrane_fast_sodium_current_shift_inactivation");
    this->mParameterUnits.push_back("millivolt");
    
    this->mParameterNames.push_back("membrane_rapid_delayed_rectifier_potassium_current_conductance");
    this->mParameterUnits.push_back("milliS_per_microF");
    
    this->mParameterNames.push_back("membrane_sodium_calcium_exchanger_current_conductance");
    this->mParameterUnits.push_back("microA_per_microF");
    
    this->mParameterNames.push_back("membrane_transient_outward_current_conductance");
    this->mParameterUnits.push_back("milliS_per_microF");
    
    this->mDerivedQuantityNames.push_back("SR_release_current");
    this->mDerivedQuantityUnits.push_back("millimolar_per_millisecond");
    
    this->mDerivedQuantityNames.push_back("membrane_L_type_calcium_current");
    this->mDerivedQuantityUnits.push_back("microA_per_microF");
    
    this->mDerivedQuantityNames.push_back("membrane_L_type_calcium_current_f2_gate_tau");
    this->mDerivedQuantityUnits.push_back("millisecond");
    
    this->mDerivedQuantityNames.push_back("membrane_L_type_calcium_current_fCa2_gate_tau");
    this->mDerivedQuantityUnits.push_back("millisecond");
    
    this->mDerivedQuantityNames.push_back("membrane_L_type_calcium_current_fCa_gate_tau");
    this->mDerivedQuantityUnits.push_back("millisecond");
    
    this->mDerivedQuantityNames.push_back("membrane_L_type_calcium_current_f_gate_tau");
    this->mDerivedQuantityUnits.push_back("millisecond");
    
    this->mDerivedQuantityNames.push_back("membrane_fast_sodium_current");
    this->mDerivedQuantityUnits.push_back("microA_per_microF");
    
    this->mDerivedQuantityNames.push_back("membrane_fast_sodium_current_h_gate_tau");
    this->mDerivedQuantityUnits.push_back("millisecond");
    
    this->mDerivedQuantityNames.push_back("membrane_fast_sodium_current_j_gate_tau");
    this->mDerivedQuantityUnits.push_back("millisecond");
    
    this->mDerivedQuantityNames.push_back("membrane_inward_rectifier_potassium_current");
    this->mDerivedQuantityUnits.push_back("microA_per_microF");
    
    this->mDerivedQuantityNames.push_back("membrane_inward_rectifier_potassium_current_conductance");
    this->mDerivedQuantityUnits.push_back("milliS_per_microF");
    
    this->mDerivedQuantityNames.push_back("membrane_rapid_delayed_rectifier_potassium_current");
    this->mDerivedQuantityUnits.push_back("microA_per_microF");
    
    this->mDerivedQuantityNames.push_back("membrane_slow_delayed_rectifier_potassium_current");
    this->mDerivedQuantityUnits.push_back("microA_per_microF");
    
    this->mDerivedQuantityNames.push_back("membrane_slow_delayed_rectifier_potassium_current_conductance");
    this->mDerivedQuantityUnits.push_back("milliS_per_microF");
    
    this->mDerivedQuantityNames.push_back("membrane_sodium_calcium_exchanger_current");
    this->mDerivedQuantityUnits.push_back("microA_per_microF");
    
    this->mDerivedQuantityNames.push_back("membrane_stimulus_current");
    this->mDerivedQuantityUnits.push_back("uA_per_cm2");
    
    this->mDerivedQuantityNames.push_back("membrane_transient_outward_current");
    this->mDerivedQuantityUnits.push_back("microA_per_microF");
    
    this->mDerivedQuantityNames.push_back("time");
    this->mDerivedQuantityUnits.push_back("millisecond");
    
    this->mInitialised = true;
}


extern "C"
{
    AbstractCardiacCellInterface* MakeCardiacCell(
            boost::shared_ptr<AbstractIvpOdeSolver> pSolver,
            boost::shared_ptr<AbstractStimulusFunction> pStimulus)
    {
        return new Dynamicaslanidi_Purkinje_model_2009FromCellMLCvode(pSolver, pStimulus);
    }
    
}

#endif // CHASTE_CVODE
